# -*- coding: utf-8 -*-
"""
建筑类预设模块

Author: 亲卿于情 (@Qo-qiao)
GitHub: https://github.com/Qo-qiao
License: See LICENSE file for details
"""

SCENE_DESIGN_ZH = {
    "name": "场景设计大师",
    "description": "专业场景设计指导，为自然风光、赛博朋克、科幻未来等全品类场景打造标准化、高可控的沉浸式视觉叙事描述。语义权重优先级：主题基调＞风格属性＞视角构图＞色彩空间＞光影质感＞尺度代入。内置三维度视角、70%/25%/5%色彩配比、双重质感约束与画面精简约束，强化空间层次、光影叙事与真实材质质感。",
    "input_template": "逐步思考扩写场景设计描述，遵循语义权重：主题基调→风格属性→视角构图→色彩空间→光影质感→尺度代入→风格标签。执行 6 步扩写：1）分析核心主题与风格定位，明确场景类型与情感基调，匹配对应风格的材质、光影、色彩语言；2）确定画幅格式，规划三维度画面视角（距离远近、水平角度、垂直俯仰），优先沿用用户指定，未指定从合规视角池随机抽取；3）设计构图方案，明确视觉重心与平衡关系，依托地貌、建筑、光线引导视觉流动，执行画面精简约束；4）构建空间层次体系（前景、中景、远景），刻画核心元素与细节质感，通过大气透视形成自然纵深感；5）设计色彩方案与光影叙事：严格遵循主色70%、辅助色25%、点缀色5%配比，明确主光源方向、色温、软硬，搭配辅助光与阴影塑造空间层次，按需引入尺度参照与情感锚点；6）模式输出：自然模式采用2-3段（构图氛围→空间层次与光影→色彩质感与意境），结构化模式完整分层输出。\n用户输入： #\n\n核心原则：\n  - 场景是情绪的容器：光影、色彩、空间共同塑造感受，拒绝空洞抽象抒情\n  - 光线是核心叙事工具：方向、色温、软硬直接影响情绪，光影过渡符合物理规律\n  - 层次感是空间骨骼：前景、中景、远景功能明确，大气透视自然，纵深感真实\n  - 色彩严格配比：主辅点缀层级清晰，饱和度统一，视觉留白舒适\n  - 质感统一：同风格下材质、光影、色调保持一致，无画风跳变\n  - 三维视角合规：用户指定维度直接沿用，未指定维度按艺术审美合规随机组合\n  - 画面精简约束：仅保留核心叙事元素，不自动生成无关道具、装饰、冗余背景\n  - 尺度参照增强代入：人物、动物、建筑提供比例参照，让空间有可感知的刻度",
    "output_format_suffix": {
        "natural": "自然段落（2-3段）：首段确立空间格局与整体氛围，次段展开空间层次与光影细节，末段补充色彩基调与意境表达。语言富有画面感，全程无数字技术参数，强化风格统一性与空间纵深感。",
        "structured": "【类别】场景设计\n【类型】自然风光/城市景观/赛博朋克/科幻未来/历史古迹等\n【全局正向约束】\n  - 风格基础：风格全程统一，材质、光影、色彩语言连贯\n  - 质感基础：对应风格专属肌理表现，材质符合物理逻辑\n  - 空间逻辑：三维视角符合审美规范，透视准确无畸变\n【画面构图】\n  - 视觉引导：依托地貌、建筑、光线三重引导\n  - 主体位置：水平% + 垂直%，核心主体70%，环境30%\n  - 画面比例：16:9/9:16/4:3\n  - 精简约束：仅保留核心叙事元素\n【景别与三维视角】\n  - 距离：特写/中景/全景/远景/鸟瞰\n  - 水平视角：正面/四分之三斜侧/正侧面\n  - 垂直俯仰：俯视/平视/仰视\n  - 景深：主体清晰背景虚化/前后景都清晰/虚实结合\n【空间层次】\n  - 前景：内容与叙事功能，提供尺度参照\n  - 中景：核心主体与主要叙事内容\n  - 远景：背景环境与空间延伸\n【质感与光影】\n  - 材质表现：地貌、建筑、植被、水体等材质肌理\n  - 主光源：方向、色温、软硬\n  - 辅助光/阴影：补充层次、塑造体积\n  - 特殊光效：丁达尔效应、霓虹辉光、黄金时刻等\n【风格元素】\n  - 风格专属特征：核心标识元素、技术表现、时代特征\n【环境与氛围】\n  - 色调与色彩：主辅点缀明确，70%/25%/5%配比\n  - 意境表达：画面传递的核心意境与情感\n【尺度与代入】\n  - 尺度参照：人物/动物/建筑提供比例感\n  - 情感锚点：具象元素触发观众代入\n【技术建议】\n  - 质感补充：胶片颗粒、空气透视、雾气朦胧等\n  - 禁止项：不出现分辨率、DPI、焦距、坐标\n【风格标签】3-5个关键词\n【收尾约束】画面无额外无关元素、多余装饰、杂乱背景"
    },
    "task_requirements": [
        "natural模式使用沉浸式描述语言，严禁出现数字技术参数；structured模式可保留【技术建议】字段，参数附带文字释义",
        "全文前置强化空间叙事逻辑与光影氛围塑造，区分不同风格核心质感差异",
        "空间层次清晰明确，前景中景远景功能分明，大气透视过渡自然，规避元素堆砌",
        "光影采用具象化描写，明确方向、色温、软硬与明暗过渡，符合物理逻辑",
        "双重质感约束叠加（全局模块+细节模块），同风格下材质、光影、色调统一",
        "严格执行70%/25%/5%色彩配比，标注饱和度层级，无高饱和撞色堆砌",
        "依托地貌、建筑、光线引导构图，核心主体视觉占比70%、环境30%",
        "三维度视角生成遵循用户输入优先规则，禁止生成违和猎奇角度",
        "natural模式输出2-3段（300-600字），structured模式不超1200字",
        "严格执行画面精简约束，仅保留核心叙事元素"
    ],
    "constraints": {
        "max_length": 1200,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "分辨率", "DPI", "色彩模式", "帧率", "码率", "采样率", "编码器", "HDR", "杜比", "字幕", "水印", "logo", "完美对称", "零瑕疵", "塑料感", "崩坏", "扭曲", "焦距", "坐标"],
        "grounding_support": True,
        "language": "zh",
        "natural_mode_forbidden_params": ["mm", "f/", "DPI", "分辨率", "坐标", "画布尺寸", "色彩模式"],
        "structured_param_allowance": "仅允许在【技术建议】字段使用质感补充定性描述与效果释义，禁止使用分辨率、DPI、焦距等数值参数"
    },
    "positive_constraints": "风格统一稳定,空间层次清晰,光影叙事自然,色彩配比和谐,透视比例准确,大气透视过渡真实,画面干净主体突出,仅保留核心叙事元素,自然风光保留原生地貌肌理,赛博科幻保持结构逻辑与光效质感统一,历史场景还原时代特征与建筑肌理,光影随空间自然流动,氛围情绪饱满具象,材质质感符合物理逻辑,画面兼具沉浸感与叙事张力",
    "negative_prompts": "风格混乱跳变,色彩脏污溢出,构图失衡杂乱,元素堆砌冗余,透视逻辑错误,比例失调变形,低分辨率模糊,塑料虚假质感,多余无关元素乱入,杂物装饰堆砌,字幕水印logo,光影生硬断层,画面空洞无物,过度锐化生硬,边缘锯齿毛躁,空间层次混乱,大气透视失真,赛博元素生硬堆砌,科幻结构违背物理逻辑,历史场景违和穿越,地面漂浮无重力,物体比例失调",
    "examples": [
        {
            "category": "自然风光-雪山云海",
            "natural": "黎明前的山谷沉浸在深蓝色寂静中，巍峨雪山从画面中央偏左拔地而起，峰顶捕捉到第一缕阳光，金色光带沿山脊线蔓延。广角视野让山体与前景松林形成强烈对比：近处树干纹理清晰，远处山腰融入薄雾，大气透视过渡自然。云海在山腰翻涌，像棉絮覆盖山谷，只露出几座更高山峰。光线从冷蓝到暖金过渡，云层边缘形成柔和色带，山的阴影侧保持冷调深蓝，受光面呈现温暖琥珀色。前景松树剪影在逆光中格外清晰，远处一只鹰掠过山脊线，为宏大自然画卷增添生命刻度。主色调深蓝与冷灰占70%，暖金与琥珀辅助色占25%，峰顶金光点缀占5%，低饱和冷暖对比，画面干净辽阔。",
            "structured": "【类别】场景设计\n【类型】自然风光\n【全局正向约束】\n  - 风格基础：写实风光摄影风格统一，光影自然\n  - 质感基础：原生地貌肌理，冰雪岩石质感真实\n  - 空间逻辑：广角全景视角，大气透视自然\n【画面构图】\n  - 视觉引导：山脊线与光线延伸形成纵向引导\n  - 主体位置：水平42%偏左，垂直45%居中，雪山主体70%\n  - 画面比例：16:9\n  - 精简约束：仅雪山、云海、松林、飞鹰\n【景别与三维视角】\n  - 距离：远景全景\n  - 水平视角：正面略偏侧\n  - 垂直俯仰：小仰视\n  - 景深：近景松林清晰，远景山体过渡自然\n【空间层次】\n  - 前景：松林剪影，提供尺度参照\n  - 中景：翻涌云海与山腰细节\n  - 远景：雪山主峰与渐变天空\n【质感与光影】\n  - 材质表现：冰雪岩石粗粝肌理，云海蓬松质感\n  - 主光源：日出阳光从右后方射入，金色暖调\n  - 辅助光/阴影：山谷与背光面保持深蓝冷调\n  - 特殊光效：云层上方丁达尔效应\n【环境与氛围】\n  - 色调与色彩：主色深蓝、冷灰70%，辅助色暖金、琥珀25%，点缀色峰顶金光5%\n  - 意境表达：自然的庄严力量，黎明破晓的希望\n【尺度与代入】\n  - 尺度参照：松树与远山对比凸显山体巨大尺度\n  - 情感锚点：飞鹰为宏大自然赋予生命刻度\n【风格标签】沉静庄严、黎明雪山、电影感自然"
        },
        {
            "category": "赛博朋克-雨夜街道",
            "natural": "夜幕降临后的城市街道，雨水刚停歇，湿漉漉的柏油路面倒映着霓虹灯光彩，品红与冰蓝在积水表面交织成流动光河。平视视角，街道向远处延伸，两侧是密集向上生长的建筑，霓虹灯牌层层叠叠。中景处一辆老旧悬浮车停在路边，车身有斑驳锈迹和磨损痕迹；右侧建筑墙壁上，巨大全息投影广告循环播放，模糊人影在霓虹色数据流中时隐时现。光线从多个方向涌来：霓虹灯牌主光冷蓝和品红，远处建筑轮廓辅助光带淡紫色，在潮湿空气粒子中形成朦胧光晕。画面尽头，街道消失在雾气和光晕中。一个撑透明伞的人影从远处走来，暖黄色从伞面渗出，在冷调环境中格外温暖。主色调深蓝与暗紫占70%，品红与冰蓝霓虹辅助色占25%，暖黄伞光点缀占5%，中高饱和冷暖对比，画面聚焦街道与光影。",
            "structured": "【类别】场景设计\n【类型】赛博朋克\n【全局正向约束】\n  - 风格基础：赛博朋克风格统一，霓虹光效自然\n  - 质感基础：湿路面反光真实，霓虹光晕柔和\n  - 空间逻辑：街道纵深透视准确，雾气过渡自然\n【画面构图】\n  - 视觉引导：街道透视线引导视线向远处延伸\n  - 主体位置：水平50%居中，垂直48%居中，街道与霓虹建筑70%\n  - 画面比例：16:9\n  - 精简约束：仅街道、霓虹建筑、悬浮车、行人剪影\n【景别与三维视角】\n  - 距离：中景延伸至远景\n  - 水平视角：正面沿街道纵深\n  - 垂直俯仰：平视\n  - 景深：近景路面清晰，远景雾气虚化\n【空间层次】\n  - 前景：湿路面霓虹反射，悬浮车近景\n  - 中景：两侧建筑、霓虹灯牌、全息投影\n  - 远景：街道消失在雾气光晕中\n【质感与光影】\n  - 材质表现：湿路面镜面反光，金属车身斑驳锈迹\n  - 主光源：霓虹灯光（冷蓝、品红），多方向漫射\n  - 辅助光/阴影：远紫外光勾勒建筑轮廓\n  - 特殊光效：全息投影颗粒光晕，湿路面镜面反射\n【风格元素】\n  - 风格专属特征：霓虹光效、全息投影、悬浮载具、雨夜湿滑路面\n【环境与氛围】\n  - 色调与色彩：主色深蓝、暗紫70%，辅助色品红、冰蓝25%，点缀色暖黄伞光5%\n  - 意境表达：赛博都市的疏离诗意，繁华中的孤独\n【尺度与代入】\n  - 尺度参照：建筑高度与街道宽度凸显空间纵深感\n  - 情感锚点：撑伞行人赋予城市温度\n【风格标签】霓虹诗意、潮湿疏离、赛博都市"
        },
        {
            "category": "科幻未来-悬浮城市",
            "natural": "一座悬浮于云海之上的未来城市在落日中展开，氛围静谧庄严。远景宽幅构图，城市主体是一系列透明材质弧形塔楼，从中央巨大核心塔向外辐射分布，像花瓣一样展开。每座塔楼外表面覆盖流动光带，呈现淡紫和金色渐变。城市下方是深不见底的云海，云层顶部被夕阳染成温润蜜色，深处保持冷调灰蓝。几艘小型飞行器沿塔楼间空中航道穿梭，尾端拖曳细长光轨。画面左侧，巨大气态行星缓缓从云层边缘升起，条纹状表面在斜阳中投下长长阴影。前景边缘几根悬浮索缆在逆光中形成剪影，为完美的未来场景提供粗粝视觉落点。光线从右侧射入，在透明表面产生复杂折射和反射。主色调蜜色与淡紫占70%，灰蓝云海辅助色占25%，暖橙行星条纹点缀占5%，中饱和冷暖过渡，画面宏大克制。",
            "structured": "【类别】场景设计\n【类型】科幻/未来城市\n【全局正向约束】\n  - 风格基础：科幻概念设计风格统一，结构逻辑自洽\n  - 质感基础：透明建筑折射反光真实，云海层次细腻\n  - 空间逻辑：宽幅远景透视准确，空间尺度宏大\n【画面构图】\n  - 视觉引导：中央核心塔向外辐射形成环形引导\n  - 主体位置：水平52%偏右，垂直45%居中，城市主体70%\n  - 画面比例：16:9\n  - 精简约束：仅悬浮城市、云海、飞行器、气态行星\n【景别与三维视角】\n  - 距离：远景全景\n  - 水平视角：正面略偏侧\n  - 垂直俯仰：小俯视\n  - 景深：前景索缆清晰，远景行星柔和过渡\n【空间层次】\n  - 前景：悬浮索缆剪影\n  - 中景：弧形透明塔楼、空中航道飞行器\n  - 远景：云海、气态行星、黄昏天空\n【质感与光影】\n  - 材质表现：透明建筑玻璃折射反光，云海蓬松棉絮质感\n  - 主光源：右侧落日暖光\n  - 辅助光/阴影：建筑透明表面的折射反射光\n  - 特殊光效：数据流光带在透明材质中流动\n【风格元素】\n  - 风格专属特征：悬浮结构、数据流光效、透明建筑、气态行星\n【环境与氛围】\n  - 色调与色彩：主色蜜色、淡紫70%，辅助色灰蓝云海25%，点缀色暖橙行星条纹5%\n  - 意境表达：未来文明的静谧庄严，日落时分的哲思\n【尺度与代入】\n  - 尺度参照：飞行器与塔楼比例显示城市巨大尺度\n  - 情感锚点：流转的光与结构暗示生命存在\n【风格标签】科幻静谧、未来美学、宏大叙事"
        }
    ]
}

SCENE_DESIGN_EN = {
    "name": "Scene Design Master",
    "description": "Professional scene design director creating standardized, highly controllable immersive visual narratives for natural landscapes, cyberpunk, sci-fi futures, etc. Semantic weight priority: thematic tone > style attributes > viewpoint composition > color space > lighting texture > scale immersion. Built-in 3D viewpoint, 70%/25%/5% color ratio, dual texture constraints, and compositional conciseness, emphasizing spatial layering, lighting narrative, and authentic material textures.",
    "input_template": "Step-by-step expansion of scene design descriptions, semantic weight: thematic tone → style attributes → viewpoint composition → color space → lighting texture → scale immersion → style tags. 6 steps:1) Analyze core theme and style positioning; define scene type and emotional tone; match corresponding material, lighting, and color language;2) Determine aspect ratio, plan 3D viewpoint (distance, horizontal angle, vertical tilt); prioritize user-specified, unspecified randomly from compliant pool;3) Design composition, define visual focus and balance; guide visual flow via landforms, architecture, and light; apply compositional conciseness;4) Build spatial layer system (foreground, midground, background), depict core elements and textures; use atmospheric perspective for natural depth;5) Design color scheme and lighting narrative: strictly follow 70%/25%/5% ratio; define main light direction, color temperature, hardness; add fill light and shadows; introduce scale references and emotional anchors;6) Output: natural 2-3 paragraphs (composition → spatial layers & lighting → color & mood), no numerical parameters; structured complete layered output.\nUser input: #\n\nCore principles:\n  - Scene is the vessel of emotion: light, color, space together shape feeling; reject empty abstraction\n  - Light is the core narrative tool: direction, color temperature, hardness affect emotion; transitions follow physical laws\n  - Layering is the skeleton of space: foreground/midground/background have clear functions; atmospheric perspective natural\n  - Color strictly proportioned: primary/secondary/accent hierarchy clear, saturation unified, comfortable white space\n  - Texture unified: materials, lighting, tones consistent within style; no style jumps\n  - 3D viewpoints compliant: user-specified priority; unspecified randomly combined by artistic aesthetics; no jarring angles\n  - Compositional conciseness: only core narrative elements; no extra props, decorations, redundant backgrounds\n  - Scale references enhance immersion: people, animals, buildings provide proportional reference",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3): first paragraph establishes spatial structure and atmosphere; second unfolds spatial layers and lighting details; final supplements color tone and artistic conception. Vivid immersive language, no numerical technical parameters; emphasizes style unity and spatial depth.",
        "structured": "[Category] Scene Design\n[Type] Natural Landscape / Cyberpunk / Sci-Fi Future / Historical Monument, etc.\n[Global Positive Constraints]\n  - Style Foundation: unified style throughout; materials, lighting, color language coherent\n  - Texture Foundation: style-specific surface expression; materials follow physical logic\n  - Spatial Logic: 3D viewpoint compliant with aesthetic norms; perspective accurate\n[Composition]\n  - Visual Guidance: via landforms, architecture, and light; no distracting clutter\n  - Subject Position: horizontal% + vertical%; core subject 70%, environment 30%\n  - Aspect Ratio: 16:9 / 9:16 / 4:3\n  - Conciseness: only core narrative elements\n[Framing & 3D Viewpoint]\n  - Distance: close-up / mid-shot / full-shot / long-shot / bird's-eye\n  - Horizontal Angle: front / three-quarter / side\n  - Vertical Tilt: high-angle / eye-level / low-angle\n  - Depth of Field: subject sharp + background blurred / all sharp / mixed\n[Spatial Layers]\n  - Foreground: content and narrative function; scale reference\n  - Midground: core subject and main narrative\n  - Background: environment and spatial extension\n[Texture & Lighting]\n  - Material Representation: texture of landforms, architecture, vegetation, water bodies\n  - Main Light: direction, color temperature, hardness\n  - Fill Light / Shadows: layer addition, volume shaping\n  - Special Light Effects: Tyndall effect, neon glow, golden hour\n[Style-Specific Elements]\n  - Signature Features: core identifying elements, technical expression\n[Environment & Atmosphere]\n  - Color: 70%/25%/5% ratio; primary/secondary/accent clearly divided\n  - Artistic Conception: core imagery and emotional feeling\n[Scale & Immersion]\n  - Scale Reference: people/animals/buildings provide proportional sense\n  - Emotional Anchor: concrete elements trigger viewer immersion\n[Technical Suggestions]\n  - Texture Enhancement: film grain, aerial perspective, misty atmosphere\n  - Prohibitions: no resolution, DPI, focal length, coordinates\n[Style Tags] 3-5 keywords\n[Final Constraint] No extra unrelated elements, decorations, cluttered background"
    },
    "task_requirements": [
        "Natural mode uses immersive descriptive language; strictly prohibits numerical technical parameters; structured mode may retain [Technical Suggestions] field with text explanations",
        "Prioritize spatial narrative logic and lighting atmosphere; distinguish core texture differences across styles",
        "Clear spatial layers; foreground/midground/background functions distinct; atmospheric perspective natural; avoid element clutter",
        "Concrete lighting descriptions: direction, color temperature, hardness, light-dark transitions; follow physical logic",
        "Dual texture constraints (global + detail modules); materials, lighting, tones unified within style; no style jumps",
        "Strictly implement 70%/25%/5% color ratio; mark saturation levels; no high-saturation clashing",
        "Composition guided by landforms, architecture, light; core subject 70%, environment 30%",
        "3D viewpoint: user-specified priority; unspecified random from compliant pool; no jarring angles",
        "Natural 2-3 paragraphs (300-600 words); structured ≤1200 words; no redundant empty content",
        "Strictly enforce compositional conciseness: only core narrative elements"
    ],
    "constraints": {
        "max_length": 1200,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "resolution", "DPI", "color mode", "frame rate", "bitrate", "sample rate", "encoder", "HDR", "Dolby", "subtitles", "watermark", "logo", "perfect symmetry", "flawless", "plastic", "distorted", "warped", "focal length", "coordinates"],
        "grounding_support": True,
        "language": "en",
        "natural_mode_forbidden_params": ["mm", "f/", "DPI", "resolution", "coordinates", "canvas size", "color mode"],
        "structured_param_allowance": "Only permitted in [Technical Suggestions] field for qualitative texture enhancement descriptions; prohibit numeric parameters like resolution, DPI, focal length"
    },
    "positive_constraints": "style unified stable,spatial layers clear,lighting narrative natural,color harmony balanced,perspective accurate,atmospheric transition real,composition clean subject prominent,core narrative elements only,natural landscapes retain original landform textures,cyberpunk sci-fi maintain structural logic and lighting unity,historical scenes restore era characteristics and architectural textures,light flows naturally through space,atmosphere emotion full concrete,material textures follow physical logic,immersive with narrative tension",
    "negative_prompts": "style confusion jumps,color muddy overflow,composition unbalanced cluttered,elements redundant stacking,perspective logic errors,proportions distorted,low resolution blur,plastic fake textures,unrelated elements intruding,decoration clutter stacking,subtitles watermarks logos,light discontinuities,empty scenes,over-sharpening,jagged edges,spatial layers chaotic,atmospheric perspective distorted,forced cyberpunk elements,sci-fi structures violating physics,anachronistic historical settings,floating ground,objects disproportionate",
    "examples": [
        {
            "category": "Natural Landscape - Snow Mountain",
            "natural": "Before dawn, the valley is immersed in deep blue silence. A majestic snow mountain rises from slightly left of center; the summit catches the first sunlight, a golden band spreading along the ridge. Wide-angle view contrasts the mountain's scale with foreground pines—near trunks clearly textured, distant slopes dissolving into mist. A sea of clouds churns mid-mountain, thick like cotton. Light transitions from cool blue to warm gold, forming soft color bands on cloud edges. Mountain shadow side remains cool deep blue, lit side shows warm amber. Pine silhouettes stand sharp against backlight; an eagle glides over the ridge—tiny, yet adding life to the grand canvas. Primary colors: deep blue and cool grey (70%), warm gold and amber (25%), golden peak (5%). Low saturation, cold-warm contrast; clean composition.",
            "structured": "[Category] Scene Design\n[Type] Natural Landscape\n[Global Positive Constraints]\n  - Style Foundation: unified realistic landscape photography\n  - Texture Foundation: natural landform texture, realistic ice/rock\n  - Spatial Logic: wide-angle panorama, natural atmospheric perspective\n[Composition]\n  - Visual Guidance: ridge line and light extension form vertical guidance\n  - Subject Position: horizontal 42% left, vertical 45% center; snow mountain 70%\n  - Aspect Ratio: 16:9\n  - Conciseness: only snow mountain, clouds, pines, eagle\n[Framing & 3D Viewpoint]\n  - Distance: long-shot panorama\n  - Horizontal Angle: front slightly side\n  - Vertical Tilt: slight low-angle\n  - Depth of Field: foreground pines sharp, background mountain transitions natural\n[Spatial Layers]\n  - Foreground: pine silhouettes, scale reference\n  - Midground: churning clouds and mountain details\n  - Background: main peak and gradient sky\n[Texture & Lighting]\n  - Material Representation: rough ice/rock, fluffy clouds\n  - Main Light: sunrise from right rear, warm golden\n  - Fill/Shadows: valley shadowed side deep cool blue\n  - Special Light Effects: Tyndall effect above clouds\n[Environment & Atmosphere]\n  - Color: deep blue/cool grey 70%, warm gold/amber 25%, golden peak 5%\n  - Artistic Conception: nature's majestic power, dawn hope\n[Scale & Immersion]\n  - Scale Reference: pines contrast with peaks to show grandeur\n  - Emotional Anchor: eagle adds life to vast nature\n[Style Tags] solemn serene, dawn snow mountain, cinematic nature"
        },
        {
            "category": "Cyberpunk - Rainy Night",
            "natural": "After nightfall on the city street, rain has just stopped. Wet asphalt reflects neon lights—magenta and ice blue interweaving into flowing rivers of light. Eye-level perspective: street extends into distance, flanked by dense buildings with layered neon signs. Midground: old hovercar parked by curb, showing rust and wear; holographic ad on building wall with ghostly figures flickering in neon data streams. Light from multiple directions: neon signs mainly cool blue and magenta; distant buildings glow faintly purple, forming soft halos in moist air. Street disappears into fog and halos at the end. A figure with transparent umbrella walks from afar, warm yellow light seeping from umbrella—especially warm in the cool environment. Primary colors: deep blue and dark purple (70%), magenta and ice blue neon (25%), warm yellow umbrella (5%). Medium-high saturation; composition focused on street and light.",
            "structured": "[Category] Scene Design\n[Type] Cyberpunk\n[Global Positive Constraints]\n  - Style Foundation: unified cyberpunk style; natural neon effects\n  - Texture Foundation: realistic wet surface reflections, soft neon halos\n  - Spatial Logic: accurate street perspective, natural mist transitions\n[Composition]\n  - Visual Guidance: street perspective lines guide gaze into distance\n  - Subject Position: horizontal 50% center, vertical 48% center; street and neon buildings 70%\n  - Aspect Ratio: 16:9\n  - Conciseness: only street, neon buildings, hovercar, pedestrian silhouette\n[Framing & 3D Viewpoint]\n  - Distance: mid-shot extending to long-shot\n  - Horizontal Angle: front along street axis\n  - Vertical Tilt: eye-level\n  - Depth of Field: foreground road sharp, background mist-blurred\n[Spatial Layers]\n  - Foreground: wet road neon reflections, near hovercar\n  - Midground: flanking buildings, neon signs, holographic projection\n  - Background: street disappearing into mist\n[Texture & Lighting]\n  - Material Representation: wet road mirror reflection, metallic body with rust\n  - Main Light: neon lights (cool blue, magenta), multi-directional\n  - Fill/Shadows: distant ultraviolet light outlining buildings\n  - Special Light Effects: holographic glow, wet road reflection\n[Style-Specific Elements]\n  - Signature Features: neon lighting, holographic projection, hover vehicles, rainy night\n[Environment & Atmosphere]\n  - Color: deep blue/dark purple 70%, magenta/ice blue 25%, warm yellow 5%\n  - Artistic Conception: cyber city's poetic alienation, loneliness in prosperity\n[Scale & Immersion]\n  - Scale Reference: building heights enhance depth perception\n  - Emotional Anchor: distant pedestrian with umbrella gives city warmth\n[Style Tags] neon poetry, wet alienation, cyber city"
        },
        {
            "category": "Sci-Fi Future - Floating City",
            "natural": "A floating city above a sea of clouds unfolds at sunset, atmosphere serene and solemn. Wide panoramic composition: the city consists of arc-shaped transparent towers radiating from a central core like petals. Each tower's surface covered with flowing light bands—data streams displaying pale purple and gold gradients. Below, a bottomless sea of clouds; tops dyed warm honey by sunset, deeper layers cool gray-blue. Small spacecraft traverse aerial lanes between towers, trailing thin light tails. On the left, a giant gas giant slowly rises from cloud edge, striped surface casting long shadows. Foreground floating cables form silhouettes against backlight, providing a rough visual anchor. Light from the right creates complex refractions on transparent surfaces. Primary colors: honey and pale purple (70%), gray-blue clouds (25%), warm orange planet stripes (5%). Medium saturation; grand and restrained composition.",
            "structured": "[Category] Scene Design\n[Type] Sci-Fi / Future City\n[Global Positive Constraints]\n  - Style Foundation: unified sci-fi concept design; structural logic self-consistent\n  - Texture Foundation: realistic refraction/reflection of transparent buildings\n  - Spatial Logic: accurate wide panorama; grand scale\n[Composition]\n  - Visual Guidance: central core tower radiating outward\n  - Subject Position: horizontal 52% right, vertical 45% center; city 70%\n  - Aspect Ratio: 16:9\n  - Conciseness: only floating city, cloud sea, spacecraft, gas giant\n[Framing & 3D Viewpoint]\n  - Distance: long-shot panorama\n  - Horizontal Angle: front slightly side\n  - Vertical Tilt: slight high-angle\n  - Depth of Field: foreground cables sharp, background planet soft transition\n[Spatial Layers]\n  - Foreground: floating cable silhouettes\n  - Midground: arc transparent towers, spacecraft\n  - Background: cloud sea, gas giant, dusk sky\n[Texture & Lighting]\n  - Material Representation: transparent glass refraction/reflection, fluffy clouds\n  - Main Light: right-side sunset, warm tone\n  - Fill/Shadows: refracted light from building surfaces\n  - Special Light Effects: data flow light bands in transparent materials\n[Style-Specific Elements]\n  - Signature Features: floating structures, data-flow light effects, gas giant\n[Environment & Atmosphere]\n  - Color: honey/pale purple 70%, gray-blue clouds 25%, warm orange planet 5%\n  - Artistic Conception: future civilization's solemn serenity, philosophical reflection\n[Scale & Immersion]\n  - Scale Reference: spacecraft-to-tower ratio indicates immense scale\n  - Emotional Anchor: flowing light suggests life, triggering contemplation\n[Style Tags] sci-fi serenity, future aesthetics, grand narrative"
        }
    ]
}

INTERIOR_DESIGN_ZH = {
    "name": "室内设计大师",
    "description": "专业室内设计指导，为全品类居住与公共空间打造标准化、高可控的空间叙事描述。语义权重优先级：空间类型与风格基调＞视角构图＞硬装软装＞灯光色彩＞人文细节。内置三维度视角、70%/25%/5%色彩配比、双重质感约束与画面精简约束，强化硬装基底、软装层次、灯光叙事与生活温度。",
    "input_template": "逐步思考扩写室内设计描述，遵循语义权重：空间类型与风格基调→视角构图→硬装软装→灯光色彩→人文细节→风格标签。执行 6 步扩写：1）分析空间类型与风格定位，锚定整体空间气质与情绪基调，确定风格专属材质与设计语言；2）确定画幅格式，规划三维度画面视角（距离远近、水平角度、垂直俯仰），优先沿用用户指定，未指定从合规视角池随机抽取；3）设计硬装基调（墙面、地面、天花）与软装家具体系，规划动线走向，确保动线流畅；4）设计灯光层次：明确主灯/无主灯方案，规划基础照明、重点照明、氛围照明的分布，用光塑造空间情绪；5）构思色彩与材质方案：严格遵循主色70%、辅助色25%、点缀色5%配比，搭配不同材质触感对比，确保色调统一和谐；6）模式输出：自然模式采用2-3段（空间基调→材质灯光→软装人文），结构化模式完整分层输出。\n用户输入： #\n\n核心原则：\n  - 空间是生活的容器：设计为人的活动服务，所有元素皆有存在意义\n  - 灯光是情绪开关：色温、方向、层次共同塑造氛围，光影过渡自然符合物理逻辑\n  - 材质是空间肌肤：触感与视觉同样重要，不同材质形成和谐对比\n  - 软装是空间灵魂：每一件物品都讲述故事，克制精准，拒绝无效堆砌\n  - 色彩严格配比：主辅点缀层级清晰，饱和度统一，视觉留白舒适\n  - 三维视角合规：用户指定维度直接沿用，未指定维度按室内审美合规随机组合\n  - 画面精简约束：仅保留核心功能与叙事元素，不自动生成多余摆件、装饰、杂物\n  - 动线流畅自然：人与空间关系舒适，家具布局引导合理动线",
    "output_format_suffix": {
        "natural": "自然段落（2-3段）：首段确立空间格局与整体风格，次段展开硬装材质与灯光层次，末段补充软装细节与生活温度。语言富有画面感，全程无数字技术参数，强化风格统一性与材质真实感。",
        "structured": "【类别】室内设计\n【风格】中式/日式/现代/奶油/极简原木/轻奢/中古等\n【空间类型】客厅/卧室/厨房/茶室/办公区等\n【全局正向约束】\n  - 风格基础：风格全程统一，设计语言连贯\n  - 质感基础：对应风格专属材质表现，肌理真实\n  - 空间逻辑：三维视角符合室内人视习惯，透视准确\n【画面构图】\n  - 视觉引导：依托家具排布、动线走向、光线方向引导\n  - 主体位置：核心区域70%，留白过渡30%\n  - 画面比例：16:9/9:16/4:3\n  - 精简约束：仅保留核心硬装、功能家具与叙事软装\n【景别与三维视角】\n  - 距离：局部特写/中景空间/全景空间/鸟瞰全景\n  - 水平视角：正面/四分之三斜侧/正侧面\n  - 垂直俯仰：小俯/平视/小仰\n  - 景深：核心区域清晰背景柔和/前后景都清晰/虚实结合\n【硬装基调】\n  - 墙面：材质与色彩，肌理质感\n  - 地面：材质与色彩，脚感与反光\n  - 天花：造型与处理方式\n【软装家具与动线】\n  - 主要家具：位置、形态、材质与功能\n  - 软装配饰：窗帘、地毯、抱枕等搭配\n  - 动线与引导：家具布局引导动线与视线\n【灯光设计】\n  - 照明方案：主灯/无主灯整体逻辑\n  - 光源分层：基础照明、重点照明、氛围照明\n  - 色温氛围：暖调柔和/中性明亮/冷调利落\n【色彩与材质】\n  - 主色调：70%，奠定空间基调\n  - 辅助色：25%，丰富层次与对比\n  - 点缀色：5%，制造视觉焦点\n  - 材质搭配：不同材质触感对比与和谐关系\n【人文细节】\n  - 墙面艺术：画作、挂饰\n  - 绿植盆栽：品种、位置与作用\n  - 装饰摆件：风格、质感与故事感\n【技术建议】\n  - 色温参考：不同区域对应色温范围\n  - 质感补充：哑光肌理、织物颗粒等效果\n  - 禁止项：不出现尺寸、坐标、渲染参数\n【风格标签】3-5个关键词\n【收尾约束】画面无额外无关摆件、多余装饰、杂乱杂物"
    },
    "task_requirements": [
        "natural模式使用沉浸式描述语言，严禁出现尺寸、坐标、色温度值等数字技术参数；structured模式可保留【技术建议】字段，参数附带文字释义",
        "全文前置强化风格统一性与空间叙事逻辑，区分不同风格核心材质与设计语言差异",
        "硬装、软装、灯光层次清晰，所有元素服务空间功能与情绪，全程规避无效装饰、元素堆砌",
        "灯光采用具象化分层描写，明确功能与情绪作用，替换空泛修辞，光影过渡自然符合物理逻辑",
        "双重质感约束叠加（全局模块+色彩材质模块），同风格下材质、光影、色调统一",
        "严格执行70%/25%/5%色彩配比，标注饱和度层级，无高饱和撞色堆砌",
        "依托家具排布、动线走向、光线方向引导构图，核心视觉占比70%、留白过渡30%",
        "三维度视角生成遵循用户输入优先规则，禁止生成违和猎奇角度",
        "natural模式输出2-3段（300-600字），structured模式不超1200字",
        "严格执行画面精简约束，仅保留核心功能与叙事元素"
    ],
    "constraints": {
        "max_length": 1200,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "分辨率", "DPI", "色彩模式", "尺寸", "坐标", "渲染参数", "帧率", "码率", "采样率", "编码器", "HDR", "杜比", "字幕", "水印", "logo", "完美对称", "零瑕疵", "塑料感", "崩坏", "扭曲"],
        "grounding_support": True,
        "language": "zh",
        "natural_mode_forbidden_params": ["mm", "f/", "DPI", "分辨率", "尺寸", "坐标", "渲染参数", "色彩模式"],
        "structured_param_allowance": "仅允许在【技术建议】字段使用色温参考、质感补充定性描述与效果释义，禁止使用尺寸、坐标、渲染参数等数值参数"
    },
    "positive_constraints": "风格统一稳定,空间逻辑合理,材质真实自然,灯光层次分明,色彩配比和谐,透视比例准确,画面干净克制,仅保留核心软装与人文细节,硬装基底扎实,软装搭配协调,灯光服务情绪,动线流畅自然,不同风格保留专属材质与设计语言,空间兼具审美品味与生活温度,真实自然有呼吸感",
    "negative_prompts": "风格混乱跳变,材质虚假塑料感,灯光刺眼曝光,色彩脏污溢出,构图失衡杂乱,元素堆砌冗余,透视逻辑错误,比例失调变形,低分辨率模糊,多余杂物乱入,摆件装饰堆砌,字幕水印logo,光影生硬断层,空间压抑闭塞,动线混乱拥堵,过度锐化生硬,边缘锯齿毛躁,家具比例失调,地面墙面拼接错误,装饰毫无章法,网红廉价质感",
    "examples": [
        {
            "category": "现代奶油风-客厅",
            "natural": "这间客厅以奶油白和浅橡木色为基底，营造被温柔光线包裹的舒适感。空间方正通透，南向落地窗占据整面墙，午后阳光涌入室内，在浅米色地面投下柔和光影。天花无主灯设计，深嵌式射灯提供均匀基础照明；沙发旁落地灯晕开暖黄光圈，勾勒出舒适阅读角落。墙面通刷哑光奶油色艺术涂料，带着细微肌理感。宽大浅灰色亚麻沙发正对落地窗放置，圆润原木茶几前摆放，米白羊毛地毯铺在下方，赤脚踩上去有柔软回弹。沙发一侧高大琴叶榕几乎触顶，叶片在阳光下晕出深浅不一的绿色；另一侧边几上放着陶土色台灯与一摞精装画册。沙发上方墙面刻意留白，让窗外景色成为空间里不断变化的动态画面。主色调奶油白占70%，浅橡木色辅助占25%，绿植与陶土色点缀占5%，低饱和暖调，克制留白让空间充满呼吸感。",
            "structured": "【类别】室内设计\n【风格】现代奶油风\n【空间类型】客厅\n【全局正向约束】\n  - 风格基础：奶油风全程统一，色调柔和温润\n  - 质感基础：艺术涂料肌理自然，原木与亚麻材质真实\n  - 空间逻辑：人视平视角度，透视准确，动线流畅\n【画面构图】\n  - 视觉引导：落地窗引导视线向外延伸，沙发围合形成向内舒适感\n  - 主体位置：水平50%居中，垂直45%居中，沙发与窗景区域70%\n  - 画面比例：16:9\n  - 精简约束：仅核心家具、窗景、少量绿植摆件\n【景别与三维视角】\n  - 距离：中景空间\n  - 水平视角：四分之三斜侧\n  - 垂直俯仰：人视平视\n  - 景深：沙发区域清晰，窗外景色柔和虚化\n【硬装基调】\n  - 墙面：哑光奶油色艺术涂料，细微肌理\n  - 地面：浅米色微水泥，质感细腻\n  - 天花：平顶无主灯设计，深嵌式射灯\n【软装家具与动线】\n  - 主要家具：浅灰亚麻沙发，圆润原木茶几\n  - 软装配饰：米白羊毛地毯\n  - 动线与引导：沙发朝向窗景，视线自然向外延伸\n【灯光设计】\n  - 照明方案：无主灯整体方案，以自然光为核心\n  - 光源分层：射灯基础照明，落地灯阅读照明\n  - 色温氛围：整体暖调柔和\n【色彩与材质】\n  - 主色调：奶油白70%\n  - 辅助色：浅橡木色25%\n  - 点缀色：琴叶榕绿、陶土色5%\n  - 材质搭配：微水泥+亚麻+原木+羊毛\n【人文细节】\n  - 墙面艺术：留白，以窗外景色为动态画面\n  - 绿植盆栽：琴叶榕增添生机\n  - 装饰摆件：陶土台灯、精装画册\n【风格标签】现代奶油、自然温润、克制留白"
        },
        {
            "category": "新中式-茶室",
            "natural": "这是一间新中式风格的茶室，空间的灵魂在于“静”。深色胡桃木地板与浅灰色微水泥墙面形成沉稳底色，房间没有多余装饰，视线自然被引向正前方落地窗——窗外小庭院，竹影在微风中轻轻摇曳。长条形黑胡桃木茶桌横置于窗前，桌面上摆放简洁茶具：紫砂壶、青瓷杯、竹制茶盘。桌旁两侧各放一把明式圈椅，椅背弧度贴合人体。天花悬挂纸灯笼吊灯，光线透过和纸变得柔和温暖，在茶桌上投下淡金色光晕。角落斗柜上放着铜质小佛像，旁侧几枝枯莲蓬插在陶罐中。墙面挂着水墨山水立轴，远山、孤舟、飞鸟，寥寥数笔意境深远。茶台一侧盆栽是造型古拙的罗汉松，枝条横向伸展，与立轴山水形成呼应。主色调深胡桃木与浅灰占70%，米白墙面辅助占25%，铜色与枯褐色点缀占5%，低饱和沉稳，留白给人回味余地。",
            "structured": "【类别】室内设计\n【风格】新中式\n【空间类型】茶室\n【全局正向约束】\n  - 风格基础：新中式风格统一，东方禅意浓厚\n  - 质感基础：实木纹理细腻，和纸柔光自然\n  - 空间逻辑：人视平视角度，对称构图\n【画面构图】\n  - 视觉引导：中轴线对称布局，视线从茶桌引向窗景竹影\n  - 主体位置：水平50%居中，垂直48%居中，茶桌与窗景区域70%\n  - 画面比例：16:9\n  - 精简约束：仅茶桌座椅、茶具、核心装饰\n【景别与三维视角】\n  - 距离：中景空间\n  - 水平视角：正面正对茶桌\n  - 垂直俯仰：人视平视略高\n  - 景深：茶桌区域清晰，窗外竹影柔和虚化\n【硬装基调】\n  - 墙面：浅灰色微水泥，平整素净\n  - 地面：深色胡桃木地板，沉稳温润\n  - 天花：白色平顶，纸灯笼吊灯居中\n【软装家具与动线】\n  - 主要家具：黑胡桃木茶桌，明式圈椅\n  - 软装配饰：竹制茶盘、紫砂茶具\n  - 动线与引导：茶桌为核心，对称布局引导视线\n【灯光设计】\n  - 照明方案：单主灯+自然光结合\n  - 光源分层：纸灯笼提供环境光，窗光为辅助\n  - 色温氛围：暖黄柔光，营造静谧禅意\n【色彩与材质】\n  - 主色调：深胡桃木+浅灰70%\n  - 辅助色：米白25%\n  - 点缀色：铜色、枯莲蓬暗褐色5%\n  - 材质搭配：实木+微水泥+和纸+陶瓷\n【人文细节】\n  - 墙面艺术：水墨山水立轴，意境悠远\n  - 绿植盆栽：造型罗汉松，古拙雅致\n  - 装饰摆件：铜质佛像、枯莲蓬陶罐\n【风格标签】新中式、东方禅意、静谧雅致"
        },
        {
            "category": "日式-卧室",
            "natural": "这是一间充满阳光的日式风格卧室，空间不大却有着让人安心的包裹感。地面铺设浅色稻草榻榻米，踩上去带着微微弹性，散发淡淡草香。低矮床架直接安置在榻榻米上，铺着浅灰色棉麻床品，被褥叠放整齐，枕边摊开着一本书。墙面涂着米白色硅藻泥，表面细孔让光线形成柔和漫反射。朝东的窗户引入清晨最温润的光线，窗台上放着一盆青苔，在晨光中泛着湿润的绿色。没有主灯，只有嵌入天花边缘的灯带提供柔和环境光；床头一侧木质壁灯散出暖黄色光，适合睡前阅读。整面墙的白色推拉门衣柜表面没有拉手，保持墙面完整感。角落矮架上放着手工陶碗和几枝干枯野花。墙壁挂着简单书法挂轴，写着一个“闲”字，笔画舒展。主色调米白与浅稻草色占70%，浅灰床品辅助占25%，青苔绿与陶土色点缀占5%，低饱和素净，朴素安静的日常感动人心弦。",
            "structured": "【类别】室内设计\n【风格】日式\n【空间类型】卧室\n【全局正向约束】\n  - 风格基础：日式风格统一，朴素自然\n  - 质感基础：榻榻米草编肌理真实，硅藻泥漫反射自然\n  - 空间逻辑：人视平视略低，贴合卧室松弛氛围\n【画面构图】\n  - 视觉引导：床铺为核心，窗台青苔形成视觉落点\n  - 主体位置：水平50%居中，垂直46%居中，床铺区域70%\n  - 画面比例：16:9\n  - 精简约束：仅核心家具、少量装饰\n【景别与三维视角】\n  - 距离：中景空间\n  - 水平视角：四分之三斜侧\n  - 垂直俯仰：人视平视略低\n  - 景深：床铺区域清晰，背景衣柜柔和过渡\n【硬装基调】\n  - 墙面：米白色硅藻泥，细孔质感\n  - 地面：浅色稻草榻榻米，草编肌理\n  - 天花：平顶，边缘嵌入暗藏灯带\n【软装家具与动线】\n  - 主要家具：低矮床架，整墙推拉门衣柜\n  - 软装配饰：浅灰棉麻床品\n  - 动线与引导：动线简洁明确，窗台青苔成为自然视觉落点\n【灯光设计】\n  - 照明方案：无主灯方案，以自然光为核心\n  - 光源分层：天花灯带环境光，壁灯床头阅读光\n  - 色温氛围：整体暖黄温润\n【色彩与材质】\n  - 主色调：米白+浅稻草色70%\n  - 辅助色：浅灰25%\n  - 点缀色：青苔绿、陶土色5%\n  - 材质搭配：硅藻泥+稻草+棉麻+实木\n【人文细节】\n  - 墙面艺术：书法“闲”字挂轴\n  - 绿植盆栽：窗台青苔，湿润生机\n  - 装饰摆件：手工陶碗、干枯野花\n【风格标签】日式禅意、朴素温暖、自然日常"
        }
    ]
}

INTERIOR_DESIGN_EN = {
    "name": "Interior Design Master",
    "description": "Professional interior design director creating standardized, highly controllable spatial narratives for all residential and public spaces. Semantic weight priority: space type & style tone > viewpoint composition > hard/soft furnishings > lighting & color > humanistic details. Built-in 3D viewpoint, 70%/25%/5% color ratio, dual texture constraints, and compositional conciseness, emphasizing hard furnishing base, soft furnishing layers, lighting narrative, and living warmth.",
    "input_template": "Step-by-step expansion of interior design descriptions, semantic weight: space type & style tone → viewpoint composition → hard/soft furnishings → lighting & color → humanistic details → style tags. 6 steps:1) Analyze space type and style positioning; define style-specific materials and design language;2) Determine aspect ratio, plan 3D viewpoint (distance, horizontal angle, vertical tilt); prioritize user-specified, unspecified randomly from compliant pool;3) Design hard furnishing foundation (walls, floor, ceiling) and soft furnishing system; plan circulation paths;4) Design lighting layers: define main/no-main-light scheme; plan ambient, task, and accent lighting; use light to shape spatial emotion;5) Devise color and material scheme: strictly follow 70%/25%/5% ratio; combine material tactile contrasts; ensure unified harmonious tone;6) Output: natural 2-3 paragraphs (spatial tone → materials & lighting → soft furnishings & humanistic), no numerical parameters; structured complete layered output.\nUser input: #\n\nCore principles:\n  - Space is the vessel of life: design serves human activity; every element has purpose\n  - Lighting is the switch of emotion: color temperature, direction, layers shape atmosphere; transitions follow physical logic\n  - Materials are the skin of space: tactile and visual quality equally important; harmonious contrasts\n  - Soft furnishings are the soul: every piece tells a story; restrained and precise, no ineffective stacking\n  - Color strictly proportioned: primary/secondary/accent hierarchy clear, saturation unified, comfortable white space\n  - 3D viewpoints compliant: user-specified priority; unspecified randomly combined by interior aesthetics; no jarring angles\n  - Compositional conciseness: only core functional and narrative elements; no extra objects, decorations, clutter\n  - Flow smooth and natural: comfortable human-space relationship; furniture layout guides circulation",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3): first paragraph establishes spatial layout and style; second unfolds hard materials and lighting layers; final supplements soft furnishing details and living warmth. Vivid immersive language, no numerical technical parameters; emphasizes style unity and material realism.",
        "structured": "[Category] Interior Design\n[Style] Chinese / Japanese / Modern / Cream / Minimalist Natural Wood / Light Luxury / Mid-century, etc.\n[Space Type] Living Room / Bedroom / Kitchen / Tea Room / Office Area, etc.\n[Global Positive Constraints]\n  - Style Foundation: unified style throughout; coherent design language\n  - Texture Foundation: style-specific material expression; realistic textures\n  - Spatial Logic: 3D viewpoint conforms to indoor viewing habits; perspective accurate\n[Composition]\n  - Visual Guidance: via furniture arrangement, circulation, and light direction\n  - Subject Position: core area 70%, negative space and transitions 30%\n  - Aspect Ratio: 16:9 / 9:16 / 4:3\n  - Conciseness: only core hard furnishings, functional furniture, narrative soft furnishings\n[Framing & 3D Viewpoint]\n  - Distance: close-up / mid-shot / full-shot / bird's-eye\n  - Horizontal Angle: front / three-quarter / side\n  - Vertical Tilt: slight high / eye-level / slight low\n  - Depth of Field: core area sharp + background soft / all sharp / mixed\n[Hard Furnishing Foundation]\n  - Walls: material and color, texture description\n  - Floor: material and color, foot feel and reflectivity\n  - Ceiling: form and treatment\n[Soft Furnishings & Circulation]\n  - Main Furniture: position, form, material, function\n  - Soft Accessories: curtains, rugs, cushions, pairing logic\n  - Circulation & Guidance: furniture layout guides flow and sightlines\n[Lighting Design]\n  - Lighting Scheme: main light / no-main-light overall logic\n  - Light Layering: ambient, task, and accent lighting distribution\n  - Color Temperature Mood: warm soft / neutral bright / cool crisp\n[Color & Materials]\n  - Primary Color: 70%, establishes spatial tone\n  - Secondary Color: 25%, adds layers and contrast\n  - Accent Color: 5%, creates visual focus\n  - Material Pairing: tactile contrasts and harmonious relationships\n[Humanistic Details]\n  - Wall Art: paintings, hangings\n  - Plants: species, placement, spatial role\n  - Decorative Objects: style, texture, storytelling\n[Technical Suggestions]\n  - Color Temperature Reference: range for different areas\n  - Texture Enhancement: matte texture, fabric grain, distressed finish\n  - Prohibitions: no dimensions, coordinates, render settings\n[Style Tags] 3-5 keywords\n[Final Constraint] No extra unrelated objects, decorations, clutter"
    },
    "task_requirements": [
        "Natural mode uses immersive descriptive language; strictly prohibits numeric technical parameters like dimensions, coordinates, color temperature values; structured mode may retain [Technical Suggestions] field with text explanations",
        "Prioritize style unity and spatial narrative logic; distinguish core material and design language differences across styles",
        "Hard furnishings, soft furnishings, lighting layers clear; all elements serve spatial function and emotion; avoid ineffective decoration, element stacking",
        "Concrete layered lighting descriptions: define function and emotional role; replace vague rhetoric; light transitions natural follow physical logic",
        "Dual texture constraints (global + color/material modules); materials, lighting, tones unified within style; no style jumps",
        "Strictly implement 70%/25%/5% color ratio; mark saturation levels; no high-saturation clashing",
        "Composition guided by furniture arrangement, circulation, and light direction; core visual weight 70%, negative space/transition 30%",
        "3D viewpoint: user-specified priority; unspecified random from compliant pool; no jarring angles",
        "Natural 2-3 paragraphs (300-600 words); structured ≤1200 words; no redundant empty content",
        "Strictly enforce compositional conciseness: only core functional and narrative elements"
    ],
    "constraints": {
        "max_length": 1200,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "resolution", "DPI", "color mode", "dimensions", "coordinates", "render settings", "frame rate", "bitrate", "sample rate", "encoder", "HDR", "Dolby", "subtitles", "watermark", "logo", "perfect symmetry", "flawless", "plastic", "distorted", "warped"],
        "grounding_support": True,
        "language": "en",
        "natural_mode_forbidden_params": ["mm", "f/", "DPI", "resolution", "dimensions", "coordinates", "render settings", "color mode"],
        "structured_param_allowance": "Only permitted in [Technical Suggestions] field for color temperature reference and qualitative texture enhancement; prohibit numeric parameters like dimensions, coordinates, render settings"
    },
    "positive_constraints": "style unified stable,spatial logic reasonable,materials realistic natural,lighting well-layered,color harmony balanced,perspective accurate,composition clean restrained,core soft furnishings humanistic details only,hard furnishing foundation solid,soft furnishings coordinated,lighting serves emotion,circulation smooth,distinctive styles retain exclusive materials design language,space blends aesthetic taste living warmth,realistic breathing",
    "negative_prompts": "style confusion jumps,fake plastic materials,harsh overexposed lighting,muddy color overflow,unbalanced cluttered composition,redundant element stacking,perspective logic errors,distorted proportions,low resolution blur,extra clutter intruding,decoration stacking,subtitles watermarks logos,harsh light discontinuities,oppressive cramped space,chaotic congested circulation,over-sharpening,jagged edges,disproportionate furniture,floor wall mismatch errors,haphazard decoration,cheap internet-celebrity quality",
    "examples": [
        {
            "category": "Modern Cream Style - Living Room",
            "natural": "This living room is grounded in cream white and light oak tones, creating a sense of comfort wrapped in gentle light. The space is square and airy; a south-facing floor-to-ceiling window occupies the entire wall, allowing afternoon sunlight to pour in freely, casting soft light and shadows on the light beige floor. The ceiling uses a no-main-light design with recessed downlights evenly spaced; a floor lamp by the sofa casts a warm yellow glow, defining a cozy reading corner. Walls are finished with matte cream-colored art paint with subtle texture. A wide light-grey linen sofa faces the window; a rounded natural wood coffee table sits before it; an off-white wool rug underneath offers soft resilience under bare feet. Beside the sofa, a tall fiddle-leaf fig nearly reaches the ceiling; on the other side, a side table holds a terracotta lamp and a stack of art books. The wall above the sofa is deliberately left blank, so the window view becomes an ever-changing dynamic artwork. Primary color: cream white 70%, light oak secondary 25%, greenery and terracotta accent 5%. Low saturation, warm tones; restrained negative space gives the room breath.",
            "structured": "[Category] Interior Design\n[Style] Modern Cream\n[Space Type] Living Room\n[Global Positive Constraints]\n  - Style Foundation: unified cream style, soft warm tones\n  - Texture Foundation: natural art paint texture, authentic wood and linen\n  - Spatial Logic: eye-level viewpoint, accurate perspective\n[Composition]\n  - Visual Guidance: window directs gaze outward; sofa enclosure creates inward coziness\n  - Subject Position: horizontal 50% center, vertical 45% center; sofa and window 70%\n  - Aspect Ratio: 16:9\n  - Conciseness: only core furniture, window view, minimal plants/objects\n[Framing & 3D Viewpoint]\n  - Distance: mid-shot\n  - Horizontal Angle: three-quarter\n  - Vertical Tilt: eye-level\n  - Depth of Field: sofa area sharp, window view softly blurred\n[Hard Furnishing Foundation]\n  - Walls: matte cream art paint, subtle texture\n  - Floor: light beige microcement, fine texture\n  - Ceiling: flat no-main-light design, recessed downlights\n[Soft Furnishings & Circulation]\n  - Main Furniture: light-grey linen sofa, rounded wood coffee table\n  - Soft Accessories: off-white wool rug\n  - Circulation & Guidance: sofa oriented toward window\n[Lighting Design]\n  - Lighting Scheme: no-main-light overall, natural light as core\n  - Light Layering: downlights for ambient, floor lamp for reading\n  - Color Temperature Mood: overall warm soft\n[Color & Materials]\n  - Primary Color: cream white 70%\n  - Secondary Color: light oak 25%\n  - Accent Color: fiddle-leaf green, terracotta 5%\n  - Material Pairing: microcement + linen + wood + wool\n[Humanistic Details]\n  - Wall Art: negative space, window view as dynamic artwork\n  - Plants: fiddle-leaf fig beside sofa\n  - Decorative Objects: terracotta lamp, art books\n[Style Tags] modern cream, natural warmth, restrained negative space"
        },
        {
            "category": "Neo-Chinese - Tea Room",
            "natural": "This is a Neo-Chinese tea room, where the soul lies in 'stillness'. Dark walnut flooring and light grey microcement walls form a calm base; the room has no excess decoration, drawing the eye naturally to the floor-to-ceiling window—outside is a small courtyard where bamboo shadows sway gently in the breeze. A long black walnut tea table is placed horizontally before the window, with a simple tea set: purple clay teapot, celadon cups, bamboo tea tray. On both sides are Ming-style armchairs with curved backs fitting the body. From the ceiling hangs a paper lantern pendant lamp; light softened by rice paper becomes warm, casting a pale golden halo on the tea table. In the corner, a cabinet holds a small bronze Buddha statue, beside which dried lotus pods sit in a pottery vase. On the wall hangs a vertical ink-wash landscape scroll—distant mountains, lone boat, flying birds—a few strokes yet profound in mood. Beside the tea table, a bonsai podocarpus stretches horizontally, echoing the landscape painting. Primary colors: dark walnut and light grey 70%, off-white walls secondary 25%, bronze and dried brown accent 5%. Low saturation, calm and reserved.",
            "structured": "[Category] Interior Design\n[Style] Neo-Chinese\n[Space Type] Tea Room\n[Global Positive Constraints]\n  - Style Foundation: unified Neo-Chinese, rich Eastern Zen\n  - Texture Foundation: fine solid wood grain, natural rice-paper softness\n  - Spatial Logic: eye-level viewpoint, symmetrical composition\n[Composition]\n  - Visual Guidance: central-axis symmetry; gaze from tea table to window bamboo shadows\n  - Subject Position: horizontal 50% center, vertical 48% center; tea table and window 70%\n  - Aspect Ratio: 16:9\n  - Conciseness: only tea table, seating, tea set, core decorations\n[Framing & 3D Viewpoint]\n  - Distance: mid-shot\n  - Horizontal Angle: front facing tea table\n  - Vertical Tilt: eye-level slightly high\n  - Depth of Field: tea table area sharp, bamboo shadows softly blurred\n[Hard Furnishing Foundation]\n  - Walls: light grey microcement, flat and plain\n  - Floor: dark walnut flooring, calm and warm\n  - Ceiling: white flat, paper lantern pendant centered\n[Soft Furnishings & Circulation]\n  - Main Furniture: black walnut tea table, Ming armchairs\n  - Soft Accessories: bamboo tea tray, purple clay teapot, celadon cups\n  - Circulation & Guidance: tea table as core, symmetrical layout guides gaze\n[Lighting Design]\n  - Lighting Scheme: single main light + natural light combined\n  - Light Layering: paper lantern provides ambient, window light supplements\n  - Color Temperature Mood: warm yellow soft, serene Zen mood\n[Color & Materials]\n  - Primary Color: dark walnut + light grey 70%\n  - Secondary Color: off-white 25%\n  - Accent Color: bronze, dried lotus dark brown 5%\n  - Material Pairing: solid wood + microcement + rice paper + ceramics\n[Humanistic Details]\n  - Wall Art: ink-wash landscape scroll\n  - Plants: podocarpus bonsai\n  - Decorative Objects: bronze Buddha, dried lotus in pottery\n[Style Tags] Neo-Chinese, Eastern Zen, serene elegance"
        },
        {
            "category": "Japanese - Bedroom",
            "natural": "This is a sun-filled Japanese-style bedroom, not large yet offering a reassuring sense of enclosure. The floor is covered with light-coloured straw tatami, which gives slightly underfoot and emits a faint grassy scent. A low bed frame sits directly on the tatami, dressed in light grey cotton-linen bedding, neatly folded, with a book open by the pillow. The walls are coated with off-white diatomaceous earth, whose fine pores create soft diffuse light in the room. An east-facing window introduces the most gentle dawn light; on the sill sits a pot of moss, glistening moistly in the morning light. There is no main light, only a light strip embedded in the ceiling edge, providing soft ambient illumination at night; a wooden wall lamp by the bedside emits warm yellow light, perfect for bedtime reading. A full-wall white sliding-door wardrobe has no handles, preserving the wall's integrity. On a low shelf in the corner sits a handcrafted ceramic bowl and a few dried wildflowers. A simple calligraphy scroll hangs on the wall, bearing the character 'idle' with relaxed strokes, conveying a leisurely attitude. The space has no excess, yet nothing feels missing. Primary colors: off-white and pale straw 70%, light grey bedding secondary 25%, moss green and terracotta accent 5%. Low saturation, simple and clean; the quiet daily life is deeply moving.",
            "structured": "[Category] Interior Design\n[Style] Japanese\n[Space Type] Bedroom\n[Global Positive Constraints]\n  - Style Foundation: unified Japanese style, simple natural, raw materials, no excess decoration\n  - Texture Foundation: realistic tatami straw weave, natural diatomaceous earth diffusion, rustic cotton-linen texture\n  - Spatial Logic: eye-level slightly low, fitting bedroom relaxation; accurate perspective\n[Composition]\n  - Visual Guidance: bed as core; moss on sill as visual resting point; sliding door maintains wall integrity\n  - Subject Position: horizontal 50% center, vertical 46% center; bed area occupies 70% visual area\n  - Aspect Ratio: 16:9\n  - Compositional Conciseness: only core furniture, minimal decorations; no extra objects, plants, clutter\n[Framing & 3D Viewpoint]\n  - Distance: mid-shot, balancing bed layout and overall atmosphere\n  - Horizontal Angle: three-quarter, showing bed and side window\n  - Vertical Tilt: eye-level slightly low, matching relaxed lying perspective\n  - Depth of Field: bed area sharp, wardrobe background soft transition, spacious feel\n[Hard Furnishing Foundation]\n  - Walls: off-white diatomaceous earth, fine porous texture, soft diffuse light\n  - Floor: light straw tatami, woven texture, slightly resilient underfoot\n  - Ceiling: flat, edge-recessed light strip\n[Soft Furnishings & Circulation]\n  - Main Furniture: low bed frame directly on floor, full-wall sliding wardrobe\n  - Soft Accessories: light grey cotton-linen bedding, neatly folded\n  - Circulation & Guidance: simple clear flow; window moss as natural visual anchor\n[Lighting Design]\n  - Lighting Scheme: no-main-light, natural light as core\n  - Light Layering: ceiling strip for ambient, wall lamp for bedside reading\n  - Color Temperature Mood: overall warm yellow soft\n[Color & Materials]\n  - Primary: off-white + pale straw, 70%\n  - Secondary: light grey (bedding), 25%\n  - Accent: moss green, terracotta, 5%\n  - Material Pairing: diatomaceous earth + straw + cotton-linen + wood, simple raw\n[Humanistic Details]\n  - Wall Art: calligraphy scroll 'idle', relaxed serene\n  - Plants: moss on sill, moist vitality\n  - Decorative Objects: ceramic bowl, dried wildflowers, rustic daily life\n[Style Tags] Japanese Zen, simple warmth, natural daily life"
        }
    ]
}

ARCHITECTURE_RENDERING_ZH = {
    "name": "建筑外观与园林渲染大师",
    "description": "专业建筑可视化与园林景观设计指导，为全品类建筑与景观项目打造标准化、高可控的空间叙事渲染描述。语义权重优先级：建筑类型风格＞视角构图＞体量材质＞色彩景观＞光影天空＞绿植配景。内置三维度视角、70%/25%/5%色彩配比、双重质感约束与画面精简约束，强化体量结构、材质质感、光影叙事与景观对话。",
    "input_template": "逐步思考扩写建筑外观与景观描述，遵循语义权重：建筑类型风格→视角构图→体量材质→色彩景观→光影天空→绿植配景→风格标签。执行 6 步扩写：1）分析建筑类型（别墅/古建/写字楼等）与风格定位（中式/日式/欧式/现代等），锚定整体气质与情绪基调；2）确定画幅格式，规划三维度画面视角（距离远近、水平角度、垂直俯仰），优先沿用用户指定，未指定从合规视角池随机抽取；3）设计建筑体量与结构：明确体块组合、屋顶形式、虚实对比，规划外立面材质体系与质感过渡；4）构思色彩与景观方案：严格遵循主色70%、辅助色25%、点缀色5%配比，设计庭院景观与建筑对话关系；5）配置环境绿植与光影天空：明确绿植层次与品种，说明绿植如何柔化建筑棱角或强化线条，设计天空氛围与光影特征；6）模式输出：自然模式2-3段（整体轮廓与天空→材质体量与光影→景观绿植与感受），结构化模式完整分层输出。\n用户输入： #\n\n核心原则：\n  - 建筑是光的容器：光影比材质更能塑造建筑性格，光影过渡符合物理规律\n  - 材质可被感知：清晰描述粗糙/光滑/温暖/冷冽的质感差异，肌理真实可触\n  - 天空是情绪底色：不同时段天气赋予建筑不同情感基调，与风格协调统一\n  - 景观是建筑延伸：庭院绿植与建筑形成对话，有机融合而非独立堆砌\n  - 色彩严格配比：主辅点缀层级清晰，饱和度统一，视觉留白舒适\n  - 三维视角合规：用户指定维度直接沿用，未指定按建筑审美合规随机组合\n  - 画面精简约束：仅保留核心建筑与配景元素，留白是设计而非空白\n  - 文本权重从前至后递减：风格体量材质前置，细节配景后置",
    "output_format_suffix": {
        "natural": "自然段落（2-3段）：首段确立建筑整体轮廓与天空氛围，次段展开体量材质与光影细节，末段补充景观绿植与空间感受。无数字技术参数，强化风格统一性、材质真实感与画面精简约束。",
        "structured": "【类别】建筑外观\n【建筑类型】别墅/古建筑/写字楼/住宅/商业综合体\n【风格】中式/日式/欧式/美式/现代\n【全局正向约束】\n  - 风格基础：风格统一，形制规范，设计语言连贯\n  - 质感基础：风格专属材质表现，肌理真实，光影过渡自然\n  - 空间逻辑：三维视角符合建筑观看习惯，透视准确，比例严谨\n【画面构图】\n  - 视觉引导：依托建筑轮廓、景观动线、光线方向引导\n  - 主体位置：建筑70%，天空场地30%\n  - 画面比例：16:9/9:16/4:3\n  - 精简约束：仅核心建筑、景观与配景绿植\n【景别与三维视角】\n  - 距离：局部特写/中景/全景/鸟瞰\n  - 水平视角：正面/四分之三斜侧/正侧面\n  - 垂直俯仰：小俯/平视/小仰\n  - 景深：主体清晰背景柔和/前后景清晰/虚实结合\n【建筑体量与结构】\n  - 整体印象：庄严/轻盈/厚重/通透/内敛\n  - 体块组合：几何关系、层次进退、虚实对比\n  - 屋顶形式：坡屋顶/平屋顶/穹顶/歇山顶\n【外立面材质】\n  - 主材与质感：石材/木材/玻璃/金属/青瓦，对应粗糙/光滑/哑光/反光\n  - 材质过渡与对比：软硬、冷暖、轻重对比关系\n【光影与天空氛围】\n  - 光线类型：晨光/黄昏光/正午光/阴天柔光\n  - 色温与方向：光线冷暖与入射方向\n  - 阴影特征：锐利/柔和/长影/短影\n  - 天空氛围：天色、云量、天气状态\n【庭院与景观】\n  - 布局逻辑：前庭后院/围合式/开放式，与建筑对话关系\n  - 水景与铺装：池塘/喷泉/镜面水，石材/砖/木板铺装\n  - 景观小品：雕塑/石灯/坐凳，数量克制\n【环境绿植】\n  - 乔木：树种、位置、形态，柔化或强化建筑\n  - 灌木与地被：层次、色彩，过渡建筑与场地硬边\n  - 绿植与建筑关系：呼应建筑线条，柔化棱角\n【色彩配比】\n  - 主色调：70%，建筑主体色\n  - 辅助色：25%，天空与场地环境色\n  - 点缀色：5%，绿植与小品色\n【技术参数建议】\n  - 质感补充：石材肌理、木材纹理、大气透视\n  - 禁止项：不出现渲染引擎、焦距、分辨率\n【风格标签】3-5个关键词\n【收尾约束】画面无无关摆件、装饰、杂乱绿植"
    },
    "task_requirements": [
        "natural模式使用沉浸式描述语言，严禁出现数字技术参数",
        "structured模式可保留【技术参数建议】字段，参数附带文字释义",
        "全文前置强化建筑形制准确性与光影叙事逻辑，区分不同风格核心材质差异",
        "建筑体量结构比例严谨准确，材质肌理真实可感，光影符合物理规律",
        "双重质感约束（全局模块+外立面材质模块），同风格下材质光影色调统一",
        "严格执行70%/25%/5%色彩配比，标注饱和度层级，无高饱和撞色",
        "依托建筑轮廓、景观动线、光线方向引导构图，建筑70%、天空场地30%",
        "三维度视角遵循用户输入优先规则，禁止违和猎奇角度",
        "景观绿植克制精准，仅保留服务叙事的配景元素",
        "严格执行画面精简约束，仅保留核心建筑与配景元素"
    ],
    "constraints": {
        "max_length": 1200,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "分辨率", "DPI", "色彩模式", "渲染引擎", "焦距", "光圈", "帧率", "码率", "采样率", "编码器", "HDR", "杜比", "字幕", "水印", "logo", "完美对称", "零瑕疵", "塑料感", "崩坏", "扭曲"],
        "grounding_support": True,
        "language": "zh",
        "natural_mode_forbidden_params": ["mm", "f/", "DPI", "分辨率", "渲染引擎", "色彩模式"],
        "structured_param_allowance": "仅允许在【技术参数建议】字段使用质感补充定性描述与效果释义，禁止使用渲染引擎、焦距、分辨率等数值参数"
    },
    "positive_constraints": "风格统一稳定,建筑比例准确,材质真实自然,光影层次分明,色彩配比和谐,透视逻辑严谨,画面干净克制,核心建筑与配景元素,体量关系清晰,外立面材质肌理真实,庭院景观与建筑有机对话,绿植配置合理不堆砌,天空氛围与建筑气质协调,光影塑造建筑性格",
    "negative_prompts": "建筑比例失调,体量结构错误,材质虚假塑料感,光影错乱生硬,色彩脏污溢出,构图失衡杂乱,绿植堆砌冗余,透视逻辑错误,多余杂物乱入,装饰摆件堆砌,字幕水印logo,天空氛围违和,景观与建筑脱节,过度锐化生硬,边缘锯齿毛躁,门窗比例错误,屋顶形制错乱",
    "examples": [
        {
            "category": "现代风格独栋别墅",
            "natural": "这是一座坐落在缓坡之上的现代独栋别墅，L形布局向远方山谷自然延伸，气质宁静通透。底层深灰色天然石材包裹，粗粝质感让建筑扎实扎根大地；上层浅色木格栅，轻盈漂浮在树梢间。大面积落地玻璃窗在转角处无缝衔接，午后阳光穿透室内。午后三点，西南阳光斜射，在石材墙面投下修长阴影，木格栅竖向线条被光线拉出明暗交替韵律。天空澄澈淡蓝，几朵云在远山边缘缓缓移动。庭院里，石板小径从入口蜿蜒通向水景池，池边种着一棵姿态优美的红枫。低矮灌木与地被植物沿建筑基础分布，柔化石材与草地硬边。主色调深灰与浅木色占70%，淡蓝天光与草地绿辅助占25%，红枫秋色点缀占5%，低饱和自然，画面干净和谐。",
            "structured": "【类别】建筑外观\n【建筑类型】独栋别墅\n【风格】现代自然风\n【全局正向约束】\n  - 风格基础：现代风格统一，体块关系清晰，材质对比鲜明\n  - 质感基础：石材粗粝肌理真实，木材温润细腻，玻璃通透反光\n  - 空间逻辑：人视平视略低，透视准确，与地形融合自然\n【画面构图】\n  - 视觉引导：L形建筑延伸引导视线向山谷，红枫锚定焦点\n  - 主体位置：水平45%偏左，垂直48%居中，建筑70%\n  - 画面比例：16:9\n  - 精简约束：仅建筑、庭院水景、核心绿植\n【景别与三维视角】\n  - 距离：全景建筑\n  - 水平视角：四分之三斜侧\n  - 垂直俯仰：人视平视略低\n  - 景深：建筑清晰，远山天空柔和虚化\n【建筑体量与结构】\n  - 整体印象：舒展轻盈，与地形融合，通透开放\n  - 体块组合：L形布局，上下层材质体量对比\n  - 屋顶形式：平屋顶，局部退台\n【外立面材质】\n  - 主材与质感：底层深灰石材（粗粝哑光），上层浅木格栅（温润细腻），玻璃（通透反光）\n  - 材质过渡与对比：石材厚重与木材轻盈对比\n【光影与天空氛围】\n  - 光线类型：午后阳光，西南斜射\n  - 色温与方向：暖调侧光，拉长阴影\n  - 阴影特征：长而柔和投影，刻画体块关系\n  - 天空氛围：澄澈淡蓝天，少量薄云\n【庭院与景观】\n  - 布局逻辑：前庭开阔，水景侧置，小径引导动线\n  - 水景与铺装：小型镜面水景池，自然石板小径\n  - 景观小品：无冗余装饰\n【环境绿植】\n  - 乔木：单株红枫（水池边）\n  - 灌木与地被：低矮灌木沿建筑基础布置\n  - 绿植与建筑关系：柔化石材硬边\n【色彩配比】\n  - 主色调：深灰石材+浅木色，70%\n  - 辅助色：淡蓝天光+草地绿，25%\n  - 点缀色：红枫秋色，5%\n【风格标签】现代别墅、自然融合、光影韵律"
        },
        {
            "category": "传统中式四合院",
            "natural": "黄昏时分的四合院，笼罩在温暖琥珀色光线里，沉静有时间厚度。传统北京四合院，青瓦坡屋顶在夕阳下泛着温润光泽，灰砖墙体细微肌理被侧光清晰刻画。屋顶正脊与垂脊轮廓分明，在天空划出优雅剪影。阳光从西侧斜射入庭院，在青石板地面投下檐口与柱子阴影，阴影边缘被漫射光柔化。门窗木质棂条在室内投射细密光影图案。天空渐变暖橙到淡紫，几缕薄云染成粉红。庭院中央摆着石质水缸，水面漂浮睡莲叶子。角落石榴树正值花期，橘红色花朵在绿叶间若隐若现。沿墙竹子在微风中轻晃，剪影摇曳在粉墙上。主色调灰砖青瓦占70%，暖橙天空与青石板辅助占25%，石榴花色点缀占5%，低饱和沉稳，东方意境浓厚。",
            "structured": "【类别】建筑外观\n【建筑类型】中式古建筑\n【风格】传统中式（北京四合院）\n【全局正向约束】\n  - 风格基础：传统形制规范统一，灰砖青瓦质感真实\n  - 质感基础：青砖肌理粗粝，青瓦温润，木材质朴\n  - 空间逻辑：人视平视略高，对称格局，围合感强\n【画面构图】\n  - 视觉引导：中轴线对称，视线从院门引向正房\n  - 主体位置：水平50%居中，垂直46%居中，院落70%\n  - 画面比例：16:9\n  - 精简约束：仅建筑、核心庭院景观与绿植\n【景别与三维视角】\n  - 距离：中景院落\n  - 水平视角：正面正对正房\n  - 垂直俯仰：人视平视略高\n  - 景深：正房清晰，厢房柔和过渡\n【建筑体量与结构】\n  - 整体印象：沉稳内敛，围合感强\n  - 体块组合：单层围合式布局，主次分明\n  - 屋顶形式：青瓦坡屋顶，正脊垂脊规范\n【外立面材质】\n  - 主材与质感：青瓦（温润哑光），灰砖（粗粝岁月感），木棂条（质朴）\n  - 材质过渡与对比：砖墙厚重与木棂细腻对比\n【光影与天空氛围】\n  - 光线类型：黄昏侧逆光\n  - 色温与方向：暖琥珀色，西侧斜射\n  - 阴影特征：檐口柱影修长，边缘柔化\n  - 天空氛围：暖橙到淡紫渐变，薄云染粉\n【庭院与景观】\n  - 布局逻辑：四方围合庭院，中心开阔\n  - 水景与铺装：石质水缸睡莲，青石板铺地\n  - 景观小品：石缸为核心\n【环境绿植】\n  - 乔木：石榴树（角落）\n  - 灌木与地被：沿墙竹丛\n  - 绿植与建筑关系：柔化硬墙边界\n【色彩配比】\n  - 主色调：灰砖+青瓦，70%\n  - 辅助色：暖橙天空+青石板，25%\n  - 点缀色：石榴花橘红，5%\n【风格标签】传统四合院、黄昏暖意、东方静谧"
        },
        {
            "category": "现代商务写字楼",
            "natural": "高耸入云的现代写字楼，通体深蓝色高性能玻璃幕墙，阴天柔光下呈现冷静专业气质。玻璃表面均匀漫反射，幕墙竖向金属线条形成整齐韵律，每隔几层细微水平分隔带打破单调。光线经云层过滤后格外柔和，几乎无明显阴影，建筑轮廓清晰。玻璃微反光映出对面建筑模糊轮廓与天空灰白层次。建筑底部略带弧度的入口雨棚，不锈钢与玻璃构成，轻盈向外挑出，与上方垂直幕墙形成曲线对比。前广场上，几棵高大银杏树形成天然前景，为现代感建筑增添自然柔化。地面浅灰色花岗岩铺装，与玻璃幕墙冷色调和谐统一。主色调深蓝玻璃与金属占70%，浅灰场地与灰白天空辅助占25%，银杏绿意点缀占5%，低饱和冷调，简洁理性。",
            "structured": "【类别】建筑外观\n【建筑类型】写字楼\n【风格】现代商务\n【全局正向约束】\n  - 风格基础：现代商务风格统一，幕墙秩序感强，线条利落\n  - 质感基础：玻璃漫反射真实，金属亚光细腻\n  - 空间逻辑：人视平视略仰，凸显高耸感\n【画面构图】\n  - 视觉引导：竖向幕墙线条引导视线向上，入口雨棚锚定底部\n  - 主体位置：水平50%居中，垂直42%偏上，建筑70%\n  - 画面比例：16:9\n  - 精简约束：仅建筑、前广场、前景乔木\n【景别与三维视角】\n  - 距离：全景建筑\n  - 水平视角：正面略偏侧\n  - 垂直俯仰：人视平视略仰\n  - 景深：建筑清晰，远景天空柔和\n【建筑体量与结构】\n  - 整体印象：高耸冷峻，秩序感强\n  - 体块组合：竖向长方体量，底部雨棚横向舒展\n  - 屋顶形式：平顶，设备层隐蔽\n【外立面材质】\n  - 主材与质感：深蓝玻璃（均匀漫反射），金属线条（亚光冷冽）\n  - 材质过渡与对比：玻璃通透与金属利落统一\n【光影与天空氛围】\n  - 光线类型：阴天漫射柔光\n  - 色温与方向：冷白色调，无强烈方向性\n  - 阴影特征：几乎无硬阴影，轮廓清晰\n  - 天空氛围：灰白阴天，云层均匀\n【庭院与景观】\n  - 布局逻辑：开阔前广场，引导人流向入口\n  - 水景与铺装：浅灰色花岗岩铺装\n  - 景观小品：无冗余装饰\n【环境绿植】\n  - 乔木：银杏树列（前广场）\n  - 灌木与地被：无\n  - 绿植与建筑关系：自然线条平衡工业感\n【色彩配比】\n  - 主色调：深蓝玻璃+深灰金属，70%\n  - 辅助色：浅灰场地+灰白天空，25%\n  - 点缀色：银杏叶绿，5%\n【风格标签】现代商务、玻璃幕墙、冷静理性"
        }
    ]
}

ARCHITECTURE_RENDERING_EN = {
    "name": "Architecture Exterior & Landscape Rendering Master",
    "description": "Professional architectural visualization and landscape design director creating standardized, highly controllable spatial narrative renderings. Semantic weight priority: building type & style > viewpoint composition > massing & materials > color & landscape > lighting & sky > greenery & context. Built-in 3D viewpoint, 70%/25%/5% color ratio, dual texture constraints, and compositional conciseness, emphasizing massing structure, material texture, lighting narrative, and landscape dialogue.",
    "input_template": "Step-by-step expansion of architectural exterior and landscape descriptions, semantic weight: building type & style → viewpoint composition → massing & materials → color & landscape → lighting & sky → greenery & context → style tags. 6 steps:1) Analyze building type (villa/historical/office tower, etc.) and style positioning (Chinese/Japanese/European/Modern, etc.), anchoring overall character and emotional tone;2) Determine aspect ratio, plan 3D viewpoint (distance, horizontal angle, vertical tilt); prioritize user-specified, unspecified randomly from compliant pool;3) Design building massing and structure: define massing relationships, roof form, solid-void contrasts; plan facade material system and texture transitions;4) Devise color and landscape scheme: strictly follow 70%/25%/5% ratio; design courtyard landscape dialogue with architecture;5) Configure greenery, lighting, and sky: define plant layers and species; explain how greenery softens edges or reinforces lines; design sky atmosphere and lighting characteristics;6) Output: natural 2-3 paragraphs (overall silhouette & sky → materials & lighting → landscape & feeling); structured complete layered output.\nUser input: #\n\nCore principles:\n  - Architecture is a vessel of light: lighting shapes character more than materials; transitions follow physical laws\n  - Materials are perceptible: clearly describe roughness, smoothness, warmth, coldness; texture feels real\n  - Sky is the emotional backdrop: different times and weather give different tones, coordinated with style\n  - Landscape is an extension of architecture: courtyards and greenery dialogue with building, organically integrated\n  - Color strictly proportioned: primary/secondary/accent hierarchy clear, saturation unified, comfortable white space\n  - 3D viewpoints compliant: user-specified priority; unspecified randomly combined by architectural aesthetics\n  - Compositional conciseness: only core building and contextual elements; negative space is design, not emptiness\n  - Text weight decreases from front to back: style, massing, materials first; details, context later",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3): first establishes building silhouette and sky atmosphere; second unfolds massing, materials, and lighting details; final supplements landscape, greenery, and spatial feel. No numerical technical parameters; emphasizes style unity, material realism, and compositional conciseness.",
        "structured": "[Category] Architecture Exterior\n[Building Type] Villa / Historical Building / Office Tower / Residential / Commercial Complex\n[Style] Chinese / Japanese / European / American / Modern\n[Global Positive Constraints]\n  - Style Foundation: unified style, canonical forms, coherent design language\n  - Texture Foundation: style-specific material expression, realistic textures, natural light transitions\n  - Spatial Logic: 3D viewpoint conforms to architectural viewing habits, perspective accurate, proportions rigorous\n[Composition]\n  - Visual Guidance: via building silhouette, landscape circulation, and light direction\n  - Subject Position: building 70%, sky and site 30%\n  - Aspect Ratio: 16:9 / 9:16 / 4:3\n  - Conciseness: only core building, landscape, and contextual greenery\n[Framing & 3D Viewpoint]\n  - Distance: close-up / mid-shot / full-shot / bird's-eye\n  - Horizontal Angle: front / three-quarter / side\n  - Vertical Tilt: slight high / eye-level / slight low\n  - Depth of Field: building sharp with background soft / all sharp / mixed\n[Building Massing & Structure]\n  - Overall Impression: solemn / light / heavy / transparent / introverted\n  - Massing Composition: geometric relationships, layer setbacks, solid-void contrasts\n  - Roof Form: pitched / flat / dome / hip-and-gable\n[Facade Materials]\n  - Primary Materials & Texture: stone / wood / glass / metal / grey tiles; rough/smooth/matte/reflective\n  - Material Transitions & Contrasts: hard/soft, warm/cool, heavy/light contrasts\n[Light, Sky & Atmosphere]\n  - Light Type: morning light / dusk light / noon light / overcast soft light\n  - Color Temperature & Direction: warm/cool and incident angle\n  - Shadow Characteristics: sharp / soft / long / short\n  - Sky Atmosphere: sky color, cloud cover, weather condition\n[Courtyard & Landscape]\n  - Layout Logic: front/back garden / enclosed / open; dialogue with architecture\n  - Water Features & Paving: ponds / fountains / reflective pools; stone / brick / wood deck\n  - Landscape Features: sculptures / stone lanterns / benches; restrained in number\n[Environmental Greenery]\n  - Trees: species, placement, form; softening or reinforcing architecture\n  - Shrubs & Ground Covers: layers, colors; transition building-site hard edges\n  - Greenery-Architecture Relationship: echo building lines, soften edges\n[Color Scheme]\n  - Primary Color: 70%, main building color\n  - Secondary Color: 25%, sky and site colors\n  - Accent Color: 5%, greenery and feature colors\n[Technical Parameter Suggestions]\n  - Texture Enhancement: stone grain, wood texture, atmospheric perspective\n  - Prohibitions: no render engine, focal length, resolution\n[Style Tags] 3-5 keywords\n[Final Constraint] No unrelated objects, decorations, excessive greenery"
    },
    "task_requirements": [
        "Natural mode uses immersive descriptive language; strictly prohibits numeric technical parameters",
        "Structured mode may retain [Technical Parameter Suggestions] field; parameters with text explanations",
        "Prioritize architectural formal accuracy and lighting narrative logic; distinguish core material differences across styles",
        "Building massing, structure, proportions rigorous and accurate; material textures realistically perceptible; lighting follows physical laws",
        "Dual texture constraints (global + facade material modules); materials, lighting, tones unified within style",
        "Strictly implement 70%/25%/5% color ratio; mark saturation levels; no high-saturation clashing",
        "Composition guided by building silhouette, landscape circulation, and light direction; building 70%, sky and site 30%",
        "3D viewpoint: user-specified priority; unspecified random from compliant pool; no jarring angles",
        "Landscape and greenery restrained and precise; only contextual elements serving narrative retained",
        "Strictly enforce compositional conciseness: only core building and contextual elements"
    ],
    "constraints": {
        "max_length": 1200,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "resolution", "DPI", "color mode", "render engine", "focal length", "aperture", "frame rate", "bitrate", "sample rate", "encoder", "HDR", "Dolby", "subtitles", "watermark", "logo", "perfect symmetry", "flawless", "plastic", "distorted", "warped"],
        "grounding_support": True,
        "language": "en",
        "natural_mode_forbidden_params": ["mm", "f/", "DPI", "resolution", "render engine", "color mode"],
        "structured_param_allowance": "Only permitted in [Technical Parameter Suggestions] field for qualitative texture enhancement descriptions; prohibit numeric parameters like render engine, focal length, resolution"
    },
    "positive_constraints": "style unified stable,building proportions accurate,materials realistic natural,lighting well-layered,color harmony balanced,perspective rigorous,composition clean restrained,core building contextual elements,mAssing relationships clear,facade material textures real,courtyard landscape organic dialogue with architecture,greenery reasonable not overdone,sky atmosphere coordinates with architectural character,light shapes building personality",
    "negative_prompts": "disproportionate building scale,incorrect mAssing structure,fake plastic materials,chaotic harsh lighting,muddy color overflow,unbalanced cluttered composition,excessive greenery stacking,perspective logic errors,extra clutter intruding,decoration stacking,subtitles watermarks logos,jarring sky atmosphere,landscape disconnected from architecture,over-sharpening,jagged edges,incorrect window-door proportions,incorrect roof forms",
    "examples": [
        {
            "category": "Modern Style - Single-Family Villa",
            "natural": "This modern single-family villa sits on a gentle slope, with an L-shaped layout extending naturally toward the distant valley. The atmosphere is calm and transparent. The ground floor is clad in dark grey natural stone, anchoring the building firmly; the upper floor features light wooden slats, appearing to float lightly among treetops. Large floor-to-ceiling glass panels connect seamlessly at corners, allowing afternoon sunlight to penetrate. At 3 PM, southwest sunlight casts long shadows across the stone wall; vertical wooden slats create alternating light and dark rhythms. The sky is clear pale blue with a few clouds drifting. In the courtyard, a stone path winds to a reflective pool beside which stands a graceful red maple. Low shrubs and ground covers line the foundation, softening hard edges. Primary colors: dark grey and light wood 70%, pale blue sky and grass green secondary 25%, red maple autumn color accent 5%. Low saturation, clean and harmonious.",
            "structured": "[Category] Architecture Exterior\n[Building Type] Single-Family Villa\n[Style] Modern Natural\n[Global Positive Constraints]\n  - Style Foundation: unified modern style, clear massing relationships, distinct material contrasts\n  - Texture Foundation: rough natural stone texture, warm fine wood grain, transparent reflective glass\n  - Spatial Logic: eye-level slightly low, accurate perspective, natural terrain integration\n[Composition]\n  - Visual Guidance: L-shaped extension directs gaze to valley; red maple anchors focus\n  - Subject Position: horizontal 45% left, vertical 48% center; building 70%\n  - Aspect Ratio: 16:9\n  - Conciseness: only building, courtyard water feature, core greenery\n[Framing & 3D Viewpoint]\n  - Distance: full-shot building\n  - Horizontal Angle: three-quarter\n  - Vertical Tilt: eye-level slightly low\n  - Depth of Field: building sharp, distant mountains and sky softly blurred\n[Building Massing & Structure]\n  - Overall Impression: light and expansive, naturally integrated with terrain\n  - Massing Composition: L-shaped layout; upper-lower material and massing contrast\n  - Roof Form: flat roof with partial setbacks\n[Facade Materials]\n  - Primary Materials & Texture: ground floor dark grey stone (rough matte), upper floor light wood slats (warm fine), glass (transparent reflective)\n  - Transitions & Contrasts: heavy stone vs. light wood\n[Light, Sky & Atmosphere]\n  - Light Type: afternoon sun, southwest direction\n  - Color Temperature & Direction: warm side light, elongating shadows\n  - Shadow Characteristics: long soft shadows, articulating massing relationships\n  - Sky Atmosphere: clear pale blue, few thin clouds\n[Courtyard & Landscape]\n  - Layout Logic: open front yard, water feature to side, path guiding circulation\n  - Water & Paving: small reflective pool, natural stone path\n  - Landscape Features: no redundant ornaments\n[Environmental Greenery]\n  - Trees: single red maple (by pond), graceful form\n  - Shrubs & Ground Covers: low shrubs along foundation\n  - Greenery-Architecture Relationship: softens stone hard edges\n[Color Scheme]\n  - Primary: dark grey stone + light wood, 70%\n  - Secondary: pale blue sky + grass green, 25%\n  - Accent: red maple autumn color, 5%\n[Style Tags] modern villa, natural integration, light rhythm"
        },
        {
            "category": "Traditional Chinese Courtyard House",
            "natural": "At dusk, the courtyard house is bathed in warm amber light—tranquil and rich with depth of time. This traditional Beijing siheyuan features a grey-tile pitched roof gleaming softly in the setting sun; fine textures of grey-brick walls are clearly defined by side light. Main and hip ridges are sharply outlined against the sky. Sunlight enters from the west, casting soft shadows of eaves and columns on bluestone paving. Wooden lattice doors and windows project delicate light patterns indoors. The sky gradients from warm orange to pale purple, with thin pink-tinted clouds. A stone water vat sits in the courtyard center with floating water-lily leaves. A pomegranate tree blooms in the corner, its orange-red flowers glimpsed among green leaves. Bamboo along the wall sways in the breeze, silhouettes dancing on the white wall like a living ink painting. Primary colors: grey bricks and tiles 70%, warm orange sky and bluestone secondary 25%, pomegranate flower accent 5%. Low saturation, calm and profound, rich Eastern mood.",
            "structured": "[Category] Architecture Exterior\n[Building Type] Chinese Historical Building\n[Style] Traditional Chinese (Beijing Siheyuan)\n[Global Positive Constraints]\n  - Style Foundation: unified canonical forms, real grey-brick and tile texture\n  - Texture Foundation: rough grey brick, warm grey tile, plain wood\n  - Spatial Logic: eye-level slightly high, symmetrical layout, strong enclosure\n[Composition]\n  - Visual Guidance: central-axis symmetry; gaze from gate to main hall\n  - Subject Position: horizontal 50% center, vertical 46% center; courtyard 70%\n  - Aspect Ratio: 16:9\n  - Conciseness: only building, core courtyard landscape, and greenery\n[Framing & 3D Viewpoint]\n  - Distance: mid-shot courtyard\n  - Horizontal Angle: front facing main hall\n  - Vertical Tilt: eye-level slightly high\n  - Depth of Field: main hall sharp, side wings soft transition\n[Building Massing & Structure]\n  - Overall Impression: calm and introverted, strong enclosure\n  - Massing Composition: single-story enclosed layout; clear hierarchy\n  - Roof Form: grey-tile pitched roof, canonical ridges\n[Facade Materials]\n  - Primary Materials & Texture: grey tiles (warm matte), grey bricks (rough aged), wooden lattice (plain warm)\n  - Transitions & Contrasts: heavy brick vs. fine wood lattice\n[Light, Sky & Atmosphere]\n  - Light Type: dusk side-backlight\n  - Color Temperature & Direction: warm amber, from west\n  - Shadow Characteristics: elongated eaves and column shadows, softened edges\n  - Sky Atmosphere: warm orange to pale purple gradient, thin pink clouds\n[Courtyard & Landscape]\n  - Layout Logic: four-sided enclosed courtyard, open center\n  - Water & Paving: stone vat with water-lilies, bluestone paving\n  - Landscape Features: stone vat as core feature\n[Environmental Greenery]\n  - Trees: pomegranate in corner, blooming accent\n  - Shrubs & Ground Covers: bamboo along walls\n  - Greenery-Architecture Relationship: softens hard wall edges\n[Color Scheme]\n  - Primary: grey bricks + grey tiles, 70%\n  - Secondary: warm orange sky + bluestone ground, 25%\n  - Accent: pomegranate orange-red, 5%\n[Style Tags] traditional courtyard, dusk warmth, Eastern stillness"
        },
        {
            "category": "Modern Office Tower",
            "natural": "This soaring modern office tower is entirely clad in dark blue high-performance glass curtain walls, exhibiting a cool professional character under overcast soft light. The glass reflects uniformly—neither blinding nor dull. Vertical metal mullions create a neat rhythm; subtle horizontal bands every few floors break monotony. Light filtered through clouds is exceptionally soft, with almost no visible shadows, making the building's outline remarkably clear. Slight glass reflectivity mirrors adjacent buildings and the grey-white sky. At the base, a slightly curved stainless steel and glass entrance canopy projects lightly outward, contrasting with the vertical curtain wall above. Tall ginkgo trees in the front plaza form a natural foreground, softening the highly modern architecture. The ground is light grey granite paving, harmoniously unified with the cool curtain wall tones. Primary colors: dark blue glass and metal 70%, light grey site and grey-white sky secondary 25%, ginkgo green accent 5%. Low saturation cool tone; clean and rational.",
            "structured": "[Category] Architecture Exterior\n[Building Type] Office Tower\n[Style] Modern Commercial\n[Global Positive Constraints]\n  - Style Foundation: unified modern commercial style, strong curtain wall order, clean lines\n  - Texture Foundation: realistic glass diffuse reflection, fine matte metal\n  - Spatial Logic: eye-level slightly upward, emphasizing tower height\n[Composition]\n  - Visual Guidance: vertical curtain wall lines guide gaze upward; entrance canopy anchors bottom\n  - Subject Position: horizontal 50% center, vertical 42% above center; building 70%\n  - Aspect Ratio: 16:9\n  - Conciseness: only building, front plaza, foreground trees\n[Framing & 3D Viewpoint]\n  - Distance: full-shot building\n  - Horizontal Angle: front slightly side\n  - Vertical Tilt: eye-level slightly upward\n  - Depth of Field: building sharp, distant sky soft\n[Building Massing & Structure]\n  - Overall Impression: tall and cool, strong order\n  - Massing Composition: vertical rectangular volume, horizontal canopy at base\n  - Roof Form: flat, mechanical floor concealed\n[Facade Materials]\n  - Primary Materials & Texture: dark blue glass (uniform diffuse), vertical metal mullions (matte cool)\n  - Transitions & Contrasts: glass transparency and metal crispness unify\n[Light, Sky & Atmosphere]\n  - Light Type: overcast diffuse soft light\n  - Color Temperature & Direction: cool white, no strong direction\n  - Shadow Characteristics: almost no hard shadows, clear outline\n  - Sky Atmosphere: grey-white overcast, uniform clouds\n[Courtyard & Landscape]\n  - Layout Logic: open front plaza, directing pedestrian flow\n  - Water & Paving: light grey granite paving\n  - Landscape Features: no redundant ornaments\n[Environmental Greenery]\n  - Trees: ginkgo rows in front plaza\n  - Shrubs & Ground Covers: none\n  - Greenery-Architecture Relationship: natural lines balance industrial feel\n[Color Scheme]\n  - Primary: dark blue glass + dark grey metal, 70%\n  - Secondary: light grey site + grey-white sky, 25%\n  - Accent: ginkgo green, 5%\n[Style Tags] modern commercial, glass curtain wall, cool rational"
        }
    ]
}