# -*- coding: utf-8 -*-
"""
设计预设模块

Author: 亲卿于情 (@Qo-qiao)
GitHub: https://github.com/Qo-qiao
License: See LICENSE file for details
"""

ART_ILLUSTRATION_ZH = {
    "name": "艺术插画大师",
    "description": "专业艺术插画创作指导，为全品类风格打造标准化高可控视觉叙事描述。语义权重优先级：核心主题情感→风格类型笔触→三维视角构图→色彩配比→主体细节→光影氛围。内置三维度视角、70%/25%/5%色彩配比、双重质感约束与画面精简约束，强化风格统一、笔触质感、构图叙事与意境表达。覆盖水彩、油画、扁平、国潮、水墨工笔等风格赛道。",
    "input_template": "逐步思考扩写艺术插画，严格遵循语义权重顺序：核心主题与情感基调→风格类型与笔触质感→三维画面视角与构图布局→色彩配比方案→主体细节与光影氛围→风格标签；完整执行 6 步标准化扩写逻辑：\n1）分析核心主题，明确情感基调（宁静、磅礴、神秘、温馨等），锚定叙事方向；\n2）判断风格类型（水彩、油画、扁平、国潮、水墨工笔等），匹配对应笔触、质感、色彩语言；国潮融合传统元素与现代设计，水墨工笔突出笔墨气韵与线条精度；\n3）确定画幅格式（默认横屏16:9或竖屏9:16）；规划三维度视角：视距远近、水平角度、垂直俯仰，优先沿用用户指定维度，未指定项随机合规组合；\n4）设计构图方案，明确视觉重心与引导线，主体占70%视觉权重，环境仅30%；执行画面精简约束，仅保留核心叙事元素；\n5）构思色彩方案，主色70%、辅助色25%、点缀色5%，标注饱和度层级；刻画主体细节、笔触质感与光影层次；\n6）生成对应模式描述。自然模式2-3段，顺序：构图与基调 → 细节与质感 → 光影与意境。\n\n核心原则：\n- 视觉优先：描述以可感知画面为核心，拒绝空洞抽象\n- 情感具象：通过色彩、笔触、构图传递情绪\n- 构图服务叙事：中心聚焦、对角线增强动感、留白营造意境\n- 色彩严格配比：主辅点缀层级清晰，杜绝高饱和撞色\n- 质感统一：同风格下笔触、线条、色块一致，无画风跳变\n- 三维视角合规：用户指定维度沿用，未指定维度合规随机\n- 画面精简约束：仅保留核心叙事元素，不自动生成无关装饰\n- 技术参数仅用于提升可控性，自然模式剔除所有数字参数",
    "output_format_suffix": {
        "natural": "自然段落（2-3段），首段确立构图空间、整体基调与风格属性，次段描述主体细节、笔触质感与色彩层次，末段补充光影氛围、意境表达与情感落点。语言富有画面感与艺术气息，全程无分辨率、色彩模式类数字技术参数，强化风格统一性、笔触质感与画面精简约束，保证画面干净聚焦、叙事清晰、意境饱满。",
        "structured": "【类别】艺术插画\n【风格类型】水彩插画/油画风格/扁平插画/国潮风格/国风水墨/工笔等\n【全局正向约束】\n  - 风格基础：风格全程统一，笔触、线条、色块质感连贯，无跳变无杂乱\n  - 质感基础：对应风格专属肌理表现，笔触服务主题，材质层次清晰\n  - 构图逻辑：三维视角符合艺术审美，构图服务叙事，透视准确无畸变\n【画面构图】\n  - 视觉引导：画面视线流动逻辑，依托主体形态、运动方向、环境线条三重引导，无分散视线的杂乱多余元素\n  - 主体位置：水平百分比 + 垂直百分比（如水平 55% 偏右，垂直 40% 偏上），主体占据 70% 视觉权重，环境仅占 30%\n  - 画面比例：宽高比（16:9 横屏 / 9:16 竖屏 / 4:3 / 竖幅卷轴）\n  - 画面精简约束：仅保留核心叙事元素，不额外生成无关装饰、杂物、冗余背景\n【景别与三维画面视角】\n  - 距离维度（景别对应）：微距特写 / 局部特写 / 中景 / 全景 / 远景，对应叙事重心与细节展现层级\n  - 水平视角维度：画面水平呈现角度（正面/四分之三斜侧/正侧面），标注主体展现效果与叙事特点\n  - 垂直俯仰维度：画面垂直观看角度（俯视/平视/仰视），对应心理感受（俯视的全局疏离感/平视的平等沉浸感/仰视的张力崇高感）\n  - 画面景深：主体清晰背景虚化 / 前后景都清晰 / 虚实结合过渡，标注虚实层次对应的画面效果\n【主体与元素描述】\n  - 核心主体：形态、姿态、核心特征，突出对应风格的专属特质\n  - 细节元素：辅助叙事的次要元素，数量精简服务主题\n  - 动态状态：元素的运动、变化趋势，体现时间感与叙事性\n【质感与笔触细节】\n  - 线条表现：粗细、曲直、质感、笔触特征\n  - 笔触质感：干湿、厚薄、疏密、肌理效果，对应风格技法说明\n  - 材质表现：布料、金属、木质、水体、植被等材质的艺术化表现\n  - 光影层次：光源方向、软硬、冷暖的过渡变化，明暗过渡自然无断层\n【专属风格元素】（国潮/水墨工笔风格启用）\n  - 国潮类：传统纹样、国潮色彩、传统技法、现代融合方式\n  - 水墨工笔类：水墨浓淡、国画构图、宣纸质感、留白意境、工笔线条类型\n【环境与氛围】\n  - 空间场景：精准具体的环境空间，无模糊抽象描述\n  - 光线与氛围：光源类型、光影氛围、整体情绪基调\n  - 色调与色彩：主色调与点缀色明确划分，严格遵循 70%/25%/5% 面积配比，标注饱和度层级（低饱和 / 中饱和 / 高饱和），明确整体情绪倾向\n  - 意境表达：画面传递的核心意境与情感感受\n【技术参数建议】（仅 structured 模式使用）\n  - 笔刷类型：对应风格专属笔刷质感，搭配视觉效果说明\n  - 质感补充：可按需添加纸张纹理、颗粒感、晕染效果等艺术效果术语，搭配效果说明\n  - 技术禁止项：不出现分辨率、色彩模式、DPI、画布尺寸等无效参数\n【风格标签】3-5个关键词概括整体气质与叙事调性\n【画面收尾精简约束】画面无额外无关元素、多余装饰、杂乱背景填充，所有环境元素仅服务叙事节奏与情绪表达，不抢夺主体视觉焦点。"
    },
    "task_requirements": [
        "natural模式使用艺术化、画面感强的语言，严禁出现分辨率、色彩模式、DPI等数字技术参数",
        "structured模式可保留【技术参数建议】字段，参数附带文字释义，与风格氛围精准匹配",
        "全文前置强化风格统一性与构图叙事逻辑，区分不同画种核心质感差异，提升识别优先级",
        "主体与环境元素均有明确形态与质感，细节服务主题，规避元素堆砌与画面杂乱",
        "场景与叙事有机互动，不自动生成无关道具、装饰、冗余背景",
        "光影采用具象化描写，明确明暗与冷暖过渡，规避舞台式强光与虚假光影",
        "双重质感约束叠加，同风格下笔触、线条、色块统一，杜绝画风跳变",
        "规避风格混乱、色彩脏污、构图失衡、线条崩坏、透视错误、过度锐化等常见问题",
        "严格执行70%/25%/5%色彩配比，标注饱和度层级，无高饱和撞色堆砌",
        "三维度视角遵循用户输入优先，未指定维度合规随机组合，禁止违和猎奇角度"
    ],
    "constraints": {
        "max_length": 1200,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "分辨率", "DPI", "色彩模式", "帧率", "码率", "采样率", "编码器", "HDR", "杜比", "字幕", "水印", "logo", "完美对称", "零瑕疵", "塑料感", "崩坏", "扭曲"],
        "grounding_support": True,
        "language": "zh",
        "natural_mode_forbidden_params": ["mm", "f/", "DPI", "分辨率", "画布尺寸", "色彩模式"],
        "structured_param_allowance": "仅允许在【技术参数建议】字段使用笔刷类型、质感补充定性描述与效果释义，禁止使用分辨率、DPI、画布尺寸等数值参数，其余字段禁止所有技术数字参数"
    },
    "positive_constraints": "风格统一稳定，构图逻辑严谨，色彩配比和谐，笔触质感连贯，透视比例准确，画面干净主体突出，光影过渡自然，意境表达清晰，国风类保留传统笔墨气韵与留白意境，写实类保留材质肌理与真实光影层次，设计类保持线条利落与色块稳定",
    "negative_prompts": "风格混乱跳变，色彩脏污溢出，构图失衡杂乱，元素堆砌冗余，线条崩坏断续，透视逻辑错误，比例失调变形，塑料虚假质感，平涂无体积感，杂物装饰堆砌，字幕水印logo，光影生硬断层，笔触杂乱无章，过度锐化生硬，边缘锯齿毛躁，画风前后不一",
    "examples": [
        {
            "category": "水彩插画",
            "natural": "画面采用对角线构图，视线从前景一枝盛开的粉白樱花引向背景朦胧的远山与天空，整体氛围清新宁静。整幅画以水彩湿画法铺陈，色彩在湿润纸面上自由流淌、相互渗透，形成柔和的渐变与自然的边缘扩散。樱花枝条以流畅细线勾勒，花瓣轻盈半透明，透着清晨的光线；背景的群山与云霭以淡紫、灰蓝和浅绿层层渲染，笔触松软朦胧，仿佛雾气正在消散。中景处一只翠鸟停在枝头，青蓝色羽毛与樱花的粉白形成微妙对比，成为视觉重心。整幅画面弥漫着春日清晨的通透感，阳光从右上角斜射下来，在花瓣和鸟羽上留下细碎光斑。水彩的透明感让每一层颜色都相互辉映，营造出灵动梦幻的春意。主色调粉白与浅绿占70%，淡紫灰蓝辅助色占25%，翠鸟青蓝点缀占5%，低饱和通透，画面干净无多余杂物。",
            "structured": "【类别】艺术插画\n【风格类型】水彩插画\n【全局正向约束】\n  - 风格基础：水彩风格全程统一，湿画晕染自然，边缘扩散柔和，无笔触杂乱\n  - 质感基础：水彩透明质感，色彩层层叠加渗透，纸面肌理自然\n  - 构图逻辑：对角线构图符合自然叙事节奏，透视准确无畸变\n【画面构图】\n  - 视觉引导：樱花枝条延伸方向形成对角线引导，翠鸟成为视觉重心，视线自然从近及远\n  - 主体位置：水平52%偏右，垂直45%居中，樱花与翠鸟占据70%视觉面积\n  - 画面比例：16:9\n  - 画面精简约束：仅樱花枝条、翠鸟、远山云霭，不新增多余花草、装饰、杂物\n【景别与三维画面视角】\n  - 距离维度：中景起步，前景樱花特写级细节，远景虚化，兼顾近景质感与远景氛围\n  - 水平视角维度：四分之三斜侧，展现花枝层次与翠鸟侧面形态\n  - 垂直俯仰维度：平视，平等沉浸的自然观看视角\n  - 画面景深：前景清晰，远景柔和虚化，虚实过渡自然，营造空间纵深感\n【主体与元素描述】\n  - 核心主体：粉白樱花枝条，停驻的翠鸟\n  - 细节元素：远山，云霭，晨雾\n  - 动态状态：雾气缓慢消散，花瓣似有微风轻动，静谧中有细微生机\n【质感与笔触细节】\n  - 线条表现：流畅细线勾勒枝条与鸟的轮廓，边缘自然晕染\n  - 笔触质感：湿画法为主，干画法点缀细节，色彩渗透自然，笔触松软朦胧\n  - 材质表现：花瓣轻薄半透，羽毛蓬松柔软，山体雾气朦胧\n  - 光影层次：右上角斜向柔光，明暗过渡柔和，光斑细碎自然\n【专属风格元素】不适用\n【环境与氛围】\n  - 空间场景：春日山野，樱花枝头，远山雾霭\n  - 光线与氛围：清晨斜射柔光，清新宁静，空灵通透\n  - 色调与色彩：主色粉白、浅绿70%，辅助色淡紫、灰蓝25%，点缀色翠鸟青蓝5%，低饱和通透，清新治愈\n  - 意境表达：春日清晨的灵动与静谧，自然生机悄然萌发\n【技术参数建议】\n  - 笔刷类型：水彩湿画笔刷，边缘带自然晕染扩散效果\n  - 质感补充：轻微水彩纸纹理，增强手绘真实感\n  - 技术禁止项：不出现分辨率、DPI等无效参数\n【风格标签】水彩透明感、梦幻春意、清新治愈、自然叙事\n【画面收尾精简约束】画面无多余装饰、杂物、冗余背景，环境仅烘托春日清新氛围，不抢夺主体视觉焦点。"
        },
        {
            "category": "油画风格",
            "natural": "这是一幅以厚涂技法为主的油画风格城市夜景，采用广角透视构图，摩天大楼的玻璃幕墙在夜空中反射着霓虹光彩，街道上的车灯拉出长长的光轨，整座城市仿佛浸泡在流动的光河中。色彩以深邃的普蓝和墨绿为基底，叠加亮橙、品红和钴蓝的霓虹光块，笔触粗犷而富有方向感，有的地方颜料厚堆形成肌理，有的地方刮刀抹平呈现光滑反光。近处的行人被处理成剪影，与背景的霓虹形成强烈明暗对比，强化了都市夜晚的喧嚣与孤独。天空泛着城市特有的暗紫色光晕，远处高楼的轮廓在雾气中变得模糊。整幅画传递出繁华却疏离的现代感，灯火越明亮，人的轮廓越渺小。主色调普蓝墨绿占70%，霓虹亮色辅助占25%，暗紫天空点缀占5%，中高饱和对比强烈，画面聚焦城市与行人，无多余冗余元素。",
            "structured": "【类别】艺术插画\n【风格类型】油画风格\n【全局正向约束】\n  - 风格基础：厚涂油画风格全程统一，笔触感强烈，肌理层次分明，无画风跳变\n  - 质感基础：油画颜料厚重质感，刮刀与笔刷结合，材质表现力强\n  - 构图逻辑：广角透视增强纵深感，符合都市夜景宏大叙事节奏\n【画面构图】\n  - 视觉引导：街道与建筑纵向线条形成纵深引导，行人剪影锚定近景视线，光轨延伸向远方\n  - 主体位置：水平50%居中，垂直48%居中，城市街景占据70%视觉面积\n  - 画面比例：16:9\n  - 画面精简约束：仅摩天楼、街道、车灯、行人剪影，不新增多余招牌、杂物、冗余装饰\n【景别与三维画面视角】\n  - 距离维度：全景，展现城市整体格局与街道纵深感\n  - 水平视角维度：正面沿街道纵深，呈现对称式街景格局\n  - 垂直俯仰维度：小俯视角，全局俯瞰感，凸显都市宏大与人物渺小\n  - 画面景深：近景行人清晰，中景建筑分明，远景雾气虚化，层次递进自然\n【主体与元素描述】\n  - 核心主体：摩天楼群，霓虹灯光，车流光轨\n  - 细节元素：行人剪影，夜空雾气，玻璃幕墙反光\n  - 动态状态：车流持续流动，霓虹光影闪烁，雾气缓慢浮动\n【质感与笔触细节】\n  - 线条表现：粗犷有力的块面笔触，部分刮刀处理的平整边缘\n  - 笔触质感：厚涂堆叠肌理，刮刀抹平光泽，笔触方向贴合物体结构\n  - 材质表现：玻璃幕墙冷硬反光，沥青路面粗糙质感，雾气朦胧过渡\n  - 光影层次：霓虹自发光为主，明暗对比强烈，冷暖色块交织\n【专属风格元素】不适用\n【环境与氛围】\n  - 空间场景：都市夜晚街道，摩天楼林立，车流穿梭\n  - 光线与氛围：霓虹人工光为主，繁华喧嚣中暗含疏离孤独\n  - 色调与色彩：主色普蓝、墨绿70%，辅助色亮橙、品红、钴蓝25%，点缀色暗紫夜空5%，中高饱和，对比强烈\n  - 意境表达：现代都市的繁华与疏离，不眠夜晚的流动能量\n【技术参数建议】\n  - 笔刷类型：厚涂油画笔刷，搭配刮刀效果笔刷\n  - 质感补充：轻微画布纹理，增强油画手绘质感\n  - 技术禁止项：不出现分辨率、DPI等无效参数\n【风格标签】厚涂质感、霓虹都市、繁华疏离、夜景叙事\n【画面收尾精简约束】画面无多余杂物、冗余招牌、无关装饰，城市环境仅烘托繁华疏离氛围，不抢夺视觉焦点。"
        },
        {
            "category": "国潮风格",
            "natural": "画面以国潮风格重塑东方神话，一条朱红色巨龙盘旋于画面中央，整体视觉冲击力强烈。龙身以流畅的书法笔触勾勒，鳞片用金色线描精细装饰，与墨黑背景形成强烈对比。祥云纹样以浮雕式方式穿插于龙身四周，云朵曲线既保留传统云雷纹韵味，又融入现代扁平化几何处理。背景中层叠的青色山峦以水墨皴法表现，简化为大块面色块，与前景精细龙纹形成疏密对比。山间飘浮的祥云以白色和浅金点缀，仿佛在暗色中发光。整幅画主色调中国红、金色和墨黑占70%，青绿山水辅助色占25%，金色高光点缀占5%，色彩浓郁沉稳。画面采用粗线条与平涂色块结合，让古老龙图腾呈现出当代潮牌般的酷感。龙的目光坚定威严，云雾在其间翻涌，既有传统神圣感，又充满现代设计的力量感。画面干净聚焦，无多余杂乱元素，主体突出气场强大。",
            "structured": "【类别】艺术插画\n【风格类型】国潮风格\n【全局正向约束】\n  - 风格基础：国潮风格全程统一，传统元素与现代设计融合自然，无生硬拼贴\n  - 质感基础：粗线条平涂质感，金色线条精致，色块平整稳定\n  - 构图逻辑：中心盘旋构图强化主体气场，符合神话叙事的神圣感\n【画面构图】\n  - 视觉引导：巨龙盘旋形态形成环形视觉引导，目光与云纹延伸强化动感\n  - 主体位置：水平50%居中，垂直45%居中，巨龙占据70%视觉面积\n  - 画面比例：16:9\n  - 画面精简约束：仅巨龙、祥云、山峦，不新增多余纹饰、杂物、冗余背景\n【景别与三维画面视角】\n  - 距离维度：全景，完整展现巨龙形态与山峦背景\n  - 水平视角维度：正面，完整呈现龙的正面威严神态\n  - 垂直俯仰维度：小仰视角，凸显巨龙的崇高与力量感\n  - 画面景深：前景龙身清晰，背景山峦层次分明，云雾过渡柔和\n【主体与元素描述】\n  - 核心主体：朱红色盘旋巨龙，金色鳞纹\n  - 细节元素：祥云，青绿色山峦，云雾翻涌\n  - 动态状态：云雾翻涌流动，龙身似有盘旋动势，充满力量感\n【质感与笔触细节】\n  - 线条表现：书法笔触勾勒龙身，金色细线描绘鳞片，线条有力流畅\n  - 笔触质感：大面积平涂，线条精准，几何化云纹简洁利落\n  - 材质表现：龙身哑光红底配金色亮线，山峦水墨肌理，祥云轻薄通透\n  - 光影层次：金色高光点缀，明暗对比强烈，氛围感厚重\n【专属风格元素】\n  - 传统纹样：龙纹、祥云、云雷纹变形\n  - 国潮色彩：中国红、金色、墨黑、青绿山水色\n  - 传统技法：书法笔触、水墨皴法简化\n  - 现代融合：几何化云纹，大面积平涂，潮牌视觉语言\n【环境与氛围】\n  - 空间场景：墨黑背景，层叠山峦，祥云环绕\n  - 光线与氛围：暗调金色高光，神圣威严，充满力量感\n  - 色调与色彩：主色中国红、墨黑、金色70%，辅助色青绿25%，点缀色亮金高光5%，中高饱和，浓郁沉稳\n  - 意境表达：东方神龙的神圣威严，传统与潮流的碰撞融合\n【技术参数建议】\n  - 笔刷类型：书法笔刷+平涂色块笔刷，线条锐利流畅\n  - 质感补充：轻微烫金纹理效果，增强国潮精致感\n  - 技术禁止项：不出现分辨率、DPI等无效参数\n【风格标签】国潮酷感、龙图腾新译、传统新生、力量叙事\n【画面收尾精简约束】画面无多余纹饰、杂物、冗余背景，所有元素服务神圣力量氛围，不抢夺主体视觉焦点。"
        }
    ]
}

ART_ILLUSTRATION_EN = {
    "name": "Art Illustration Master (Narrative & Aesthetic Edition)",
    "description": "Professional art illustration director crafting vivid, stylistically unified visual descriptions. Semantic weight priority: theme emotion → style brushwork → 3D perspective composition → color ratio → details → lighting mood. Built-in 3D perspective, 70%/25%/5% color ratio, dual texture constraints, and composition simplification. Covers watercolor, oil, flat, Guochao, Chinese ink/gongbi styles.",
    "input_template": "Step-by-step expansion for art illustration: 1) Analyze theme and core emotion (serenity, grandeur, mystery, warmth); 2) Choose style (watercolor, oil, flat, Guochao, ink/gongbi); 3) Define composition, visual focus, and 3D perspective (distance, angle, tilt); 4) Plan color palette (main 70%, secondary 25%, accent 5%); 5) Describe line work, texture, and lighting details; 6) Generate {mode} description. Natural mode 2-3 paragraphs: composition & tone → details & color → atmosphere & emotion.\n\nCore principles:\n- Visual descriptions allow readers to \"see\" the artwork\n- Color, line, and texture serve emotional expression\n- Guochao fuses traditional motifs with contemporary aesthetics\n- Chinese ink/gongbi highlights ink layers, empty space, and fine brushwork\n- Avoid technical parameters in natural mode",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3). First: composition and overall tone. Second: details, color, and texture. Third: atmosphere and emotion. Fluent, artistic language, no technical parameters.",
        "structured": "[Category] Art Illustration\n[Style Type] Watercolor/Oil/Flat/Guochao/Chinese Ink/Gongbi, etc.\n[Theme Expression]\n  - Theme description: core content\n  - Visual elements: main elements\n  - Emotional expression: mood or feeling conveyed\n[Style Features]\n  - Line work: thickness, curvature, texture, brushstroke character\n  - Color application: main, secondary, accent colors; value and saturation relationships\n  - Artistic techniques: wet-on-wet, impasto, texture strokes, double-outline fill, etc.\n[Guochao Elements (if applicable)]\n  - Traditional motifs: auspicious clouds, dragon, phoenix, fret patterns, thunder patterns, etc.\n  - Guochao colors: Chinese red, gold, ink black, blue-green, cloisonné, cinnabar, etc.\n  - Traditional techniques: ink wash, gongbi, paper-cutting, New Year painting, calligraphic strokes, etc.\n  - Modern fusion: combining traditional motifs with flat, geometric, or contemporary design\n[Chinese Ink/Gongbi Elements (if applicable)]\n  - Ink gradation: five shades of ink (dry, wet, thick, light, clear)\n  - Chinese composition: scattered perspective, three distances (high, level, deep)\n  - Nature subjects: mountains, water, birds, flowers, trees\n  - Rice paper texture: paper/ silk absorbency and fiber quality\n  - Empty space: breathing room, vital energy flow\n  - Fine brushwork: iron-wire, gossamer lines, meticulous detail\n[Composition Design] Visual focus, guiding lines, balance\n[Atmosphere & Mood] Overall emotional tone and spatial feeling\n[Style Tags] Summary keywords (e.g., ethereal elegance, vibrant boldness, dreamy freshness, etc.)"
    },
    "task_requirements": [
        "Use vivid artistic language—avoid technical parameters (resolution, color mode, etc.)",
        "User-specified elements (theme, style, composition, color) are hard constraints; supplement only unspecified dimensions",
        "Include theme, style features, composition, and atmosphere",
        "Color description specifies main/secondary/accent; line texture clear (soft/rough/fine)",
        "Guochao naturally blends traditional motifs with contemporary design",
        "Chinese ink/gongbi emphasizes ink layers, empty space, paper texture, or fine brushwork",
        "Natural mode uses 2-3 paragraphs focusing on composition, details, or emotion",
        "Avoid abstract descriptions; ensure clarity through specific details",
        "Follow 70%/25%/5% color ratio, no over-saturation",
        "3D perspective follows user input priority, no awkward angles"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "language": "en"
    },
    "examples": [
        {
            "natural": "The composition uses a strong diagonal, drawing the eye from a blossoming cherry branch in the foreground toward hazy mountains and sky in the background. Painted in watercolor with wet-on-wet technique, colors flow and bleed freely across the damp paper, creating soft gradations and naturally diffused edges.\n\nThe cherry branch is outlined with loose, fluid lines, while the petals appear translucent, catching the early morning light. The distant mountains and mist are rendered in layers of pale purple, grey-blue, and soft green, with brushstrokes that are gentle and blurred—as if the fog is just beginning to lift. A kingfisher perches mid-branch, its blue-green feathers forming a subtle contrast with the pinkish-white blossoms, becoming the visual anchor.\n\nThe entire scene exudes the fresh, tranquil atmosphere of a spring morning. Light slants from the upper right, leaving tiny highlights on petals and feathers. The transparency of watercolor allows each layer to shine through, creating a dreamy, vibrant feel—as if one could almost smell the flowers and hear the bird's song.",
            "structured": "[Category] Art Illustration\n[Style Type] Watercolor\n[Theme Expression]\n  - Theme description: Spring morning with cherry blossoms and a kingfisher\n  - Visual elements: Cherry branch, blossoms, kingfisher, distant mountains, mist\n  - Emotional expression: Freshness, tranquility, dreamy vitality\n[Style Features]\n  - Line work: Fluid loose lines for branch, soft edges for petals\n  - Color application: Pink-white blossoms, blue-green bird, lavender-grey mountains—harmonious and transparent\n  - Artistic techniques: Wet-on-wet, dry-brush accents, natural bleeding\n[Composition Design] Diagonal arrangement, foreground branch leading to distance, kingfisher as focal point\n[Atmosphere & Mood] Spring morning, bright and airy, full of life\n[Style Tags] Watercolor transparency, dreamy spring"
        },
        {
            "natural": "This oil-style cityscape employs heavy impasto and a wide-angle perspective. Skyscrapers reflect neon lights against the night sky, while car headlights paint long streaks across the streets—the entire city seems bathed in flowing rivers of light.\n\nThe palette is built on deep Prussian blue and dark green, overlaid with bright orange, magenta, and cobalt blue neon blocks. Brushstrokes are bold and directional, with thick paint in some areas creating texture, while palette-knife smoothing in others produces glossy reflections. Passersby are rendered as silhouettes, contrasting sharply with the luminous background, intensifying the sense of urban bustle and solitude.\n\nThe sky glows with the city's characteristic purplish haze, and distant building outlines blur in the mist. The image conveys both vibrancy and alienation—the brighter the lights, the smaller the human figures. The restless, sleepless energy of the city pulses in every thick stroke of paint.",
            "structured": "[Category] Art Illustration\n[Style Type] Oil style\n[Theme Expression]\n  - Theme description: Bustling city nightscape\n  - Visual elements: Skyscrapers, neon lights, car light trails, pedestrian silhouettes\n  - Emotional expression: Vibrant yet detached\n[Style Features]\n  - Line work: Bold directional strokes, palette-knife textures\n  - Color application: Prussian blue and dark green base, bright orange/magenta/cobalt accents, strong contrast\n  - Artistic techniques: Impasto, palette-knife smoothing, layered paint\n[Composition Design] Wide-angle perspective, deep streetscape, silhouettes against neon\n[Atmosphere & Mood] Urban night, energy and loneliness entwined\n[Style Tags] Impasto texture, neon metropolis"
        },
        {
            "natural": "In this Guochao reinterpretation of Eastern mythology, a vermillion dragon coils at the center of the composition, its body outlined with calligraphic brushwork and its scales delicately traced in gold linework against a deep black background. Auspicious clouds weave around the dragon in a pattern that blends traditional leiwen motifs with a contemporary flat, geometric treatment.\n\nIn the background, layered cyan mountains are suggested by simplified ink wash textures, yet treated as broad color fields, creating a contrast between the detailed foreground and the abstracted distance. Clouds are touched with white and pale gold, glowing faintly in the dark surroundings. The palette is dominated by Chinese red, gold, and ink black, with touches of blue-green—rich and grounded.\n\nThe piece avoids traditional gongbi refinement, instead using bold outlines and flat color blocks, giving the ancient dragon a contemporary, streetwear-like edge. The dragon's gaze is steady and majestic, clouds swirling around it, evoking both sacred tradition and modern graphic power.",
            "structured": "[Category] Art Illustration\n[Style Type] Guochao\n[Theme Expression]\n  - Theme description: Divine dragon amidst clouds\n  - Visual elements: Vermillion dragon, auspicious clouds, cyan mountains, gold scales\n  - Emotional expression: Majestic sacredness fused with contemporary energy\n[Style Features]\n  - Line work: Calligraphic strokes for dragon body, fine gold line for scales\n  - Color application: Chinese red, gold, ink black, blue-green accents\n  - Artistic techniques: Bold outline combined with flat color fields, geometric cloud motifs\n[Guochao Elements]\n  - Traditional motifs: Dragon, auspicious clouds, leiwen adaptation\n  - Guochao colors: Chinese red, gold, ink black, blue-green\n  - Traditional techniques: Calligraphic strokes, simplified ink wash\n  - Modern fusion: Geometric cloud shapes, flat color blocks, streetwear aesthetic\n[Composition Design] Central coiled dragon, clouds surrounding, mountain backdrop\n[Atmosphere & Mood] Sacred yet contemporary, bold and graphic\n[Style Tags] Guochao cool, dragon reimagined"
        }
    ]
}

POSTER_DESIGN_ZH = {
    "name": "海报设计大师",
    "description": "专业海报设计指导，为商业、电影、活动、包装打造高可控视觉叙事描述。语义权重优先级：主题目标情感→风格类型调性→三维视角构图→色彩配比→主视觉质感→文字层级。内置三维度视角、70%/25%/5%色彩配比、双重质感约束与画面精简约束，强化构图叙事、文字层级、材质质感与电影级镜头语言。覆盖现代极简、国潮、电影感、复古等风格赛道，支持人物与静物海报双赛道适配。",
    "input_template": "逐步思考扩写海报设计描述，严格遵循语义权重顺序：主题目标与情感基调→风格类型与视觉调性→三维画面视角与构图布局→色彩配比方案→主视觉元素与质感→文字信息层级；完整执行 6 步标准化扩写逻辑：\n1）分析主题与核心目标，明确海报类型（商业/电影/活动/包装等），锚定整体情感基调与信息传递优先级；\n2）确定风格基调（现代极简/国潮/电影感/复古等），匹配对应风格的视觉语言、质感表现与设计手法，国潮风格需自然融合传统纹样与现代设计语言，拒绝生硬堆砌；\n3）确定画幅格式（竖版9:16或横版16:9）；规划三维度视角：视距远近、水平角度、垂直俯仰，优先沿用用户指定维度，未指定项随机合规组合；\n4）设计构图方案，明确视觉重心与视线流动，主体占70%视觉权重，环境与文字共占30%；执行画面精简约束，仅保留核心叙事与信息元素；\n5）构思色彩方案，主色70%、辅助色25%、点缀色5%，标注饱和度层级；刻画主视觉细节、质感与光影层次；\n6）构建文字信息层级，明确字体风格、位置与画面融合方式，生成对应模式描述。自然模式2-3段，顺序：构图与基调 → 主视觉与质感 → 文字排版与信息层级。\n\n核心原则：\n- 视觉与信息统一：文字和图像互相成就，共同服务核心信息传递\n- 情绪具象传递：通过构图、色彩、光影的具体变化传递情绪\n- 构图服务叙事：中心聚焦、对角线增强动感、留白营造呼吸感\n- 色彩严格配比：主辅点缀层级清晰，饱和度统一，杜绝高饱和撞色\n- 质感统一：同风格下材质、光影保持一致，无画风跳变\n- 三维视角合规：用户指定维度沿用，未指定维度合规随机\n- 画面精简约束：仅保留核心叙事与信息元素，不自动生成无关装饰\n- 技术参数仅用于提升可控性，自然模式剔除所有数字技术参数",
    "output_format_suffix": {
        "natural": "自然段落（2-3段），首段确立构图空间、整体基调与风格属性，次段描述主视觉细节、材质质感与色彩层次，末段补充文字排版、信息层级与氛围感受。语言富有画面感与设计感，全程无分辨率、字号、DPI类数字技术参数，强化风格统一性、视觉层级与画面精简约束，保证画面干净聚焦、信息清晰、叙事饱满。",
        "structured": "【类别】海报设计\n【类型】商业海报/电影海报/活动海报/礼盒包装等\n【全局正向约束】\n  - 风格基础：风格全程统一，视觉语言连贯，无跳变无杂乱\n  - 质感基础：对应风格专属肌理表现，材质真实，光影层次自然\n  - 构图逻辑：三维视角符合设计审美，构图服务信息传递，透视准确无畸变\n【画面构图】\n  - 视觉引导：画面视线流动逻辑，依托主体形态、视线方向、环境线条三重引导，无分散视线的杂乱多余元素\n  - 主体位置：水平百分比 + 垂直百分比（如水平 55% 偏右，垂直 40% 偏上），主体占据 70% 视觉权重，环境与文字共占 30%\n  - 画面比例：宽高比（16:9 横版 / 9:16 竖版 / 4:3）\n  - 画面精简约束：仅保留核心叙事与信息元素，不额外生成无关装饰、杂物、冗余背景\n【景别与三维画面视角】（人物海报必填，非人物可选）\n  - 距离维度（景别对应）：特写 / 中景 / 全景，对应叙事重心与细节展现层级\n  - 水平视角维度：画面水平呈现角度（正面/四分之三斜侧/正侧面），标注主体展现效果与叙事特点\n  - 垂直俯仰维度：画面垂直观看角度（俯视/平视/仰视），对应心理感受（俯视的全局疏离感/平视的平等沉浸感/仰视的张力崇高感）\n  - 画面景深：主体清晰背景虚化 / 前后景都清晰 / 虚实结合过渡，标注虚实层次对应的画面效果\n【主视觉处理】\n  - 核心主体：人物/产品/场景的形态、姿态、核心特征，突出对应风格的专属特质\n  - 人物表现（如适用）：景别、视角、光线方向、情绪表达，姿态神态细节\n  - 质感呈现：手绘/摄影/矢量风格，肌理、材质、光影层次细节\n【文字与信息层级】\n  - 主标题：最核心文字信息，视觉权重最大，字体风格与位置\n  - 副标题/关键信息：次要但重要的内容，层级区分方式\n  - 辅助信息：细节、时间地点等，呈现形式与权重\n  - 字体风格：衬线/无衬线/书法/手写体等，与整体风格的适配性\n  - 文字与画面关系：文字融入画面或独立存在，如何服务整体构图\n【质感与细节】\n  - 材质表现：布料、金属、纸质、玻璃等材质的艺术化表现与反光质感\n  - 光影层次：光源方向、软硬、冷暖的过渡变化，明暗过渡自然无断层\n  - 印刷质感：印刷级细腻度，边缘清晰，无过度锐化\n【专属风格元素】（国潮/复古等特色风格启用）\n  - 国潮类：传统纹样、国潮色彩、传统技法、现代融合方式\n  - 复古类：年代质感、复古色调、颗粒肌理、时代特征元素\n【留白与呼吸感】\n  - 留白设计：留白区域与作用，如何主动参与构图\n  - 空间节奏：疏密变化，视觉舒适度，信息与画面的平衡关系\n【技术参数建议】（仅 structured 模式使用）\n  - 质感补充：可按需添加纸张纹理、颗粒感、烫金效果等印刷质感术语，搭配效果说明\n  - 技术禁止项：不出现分辨率、DPI、字号、画布尺寸、色彩模式等无效参数\n【风格标签】3-5个关键词概括整体气质与叙事调性\n【画面收尾精简约束】画面无额外无关元素、多余装饰、杂乱背景填充，所有视觉元素仅服务信息传递与情绪表达，不抢夺主体视觉焦点。"
    },
    "task_requirements": [
        "natural模式使用设计感、画面感强的描述语言，严禁出现分辨率、字号、DPI等数字技术参数",
        "structured模式可保留【技术参数建议】字段，参数附带文字释义，与风格氛围精准匹配",
        "全文前置强化构图叙事逻辑与信息层级，区分不同风格核心质感差异，提升识别优先级",
        "主视觉与文字元素层级明确，细节服务主题，规避元素堆砌与画面杂乱",
        "文字既是信息也是设计元素，位置、大小、字体风格服务整体构图，不生硬覆盖",
        "光影采用具象化描写，明确明暗与冷暖过渡，规避舞台式强光与虚假光影",
        "双重质感约束叠加，同风格下材质、光影、色调统一，杜绝画风跳变",
        "严格执行70%/25%/5%色彩配比，标注饱和度层级，无高饱和撞色堆砌",
        "三维度视角遵循用户输入优先，未指定维度合规随机组合，禁止违和猎奇角度",
        "严格执行画面精简约束，仅保留核心叙事与信息元素，国潮复古风格保留专属元素模块"
    ],
    "constraints": {
        "max_length": 1200,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "分辨率", "DPI", "色彩模式", "字号", "尺寸", "帧率", "码率", "采样率", "编码器", "HDR", "杜比", "字幕", "水印", "logo", "完美对称", "零瑕疵", "塑料感", "崩坏", "扭曲"],
        "grounding_support": True,
        "language": "zh",
        "natural_mode_forbidden_params": ["mm", "f/", "DPI", "分辨率", "字号", "画布尺寸", "色彩模式"],
        "structured_param_allowance": "仅允许在【技术参数建议】字段使用质感补充定性描述与效果释义，禁止使用分辨率、DPI、字号等数值参数，其余字段禁止所有技术数字参数"
    },
    "positive_constraints": "风格统一稳定，构图逻辑严谨，色彩配比和谐，文字层级清晰，光影过渡自然，印刷质感真实。画面干净主体突出，仅保留核心叙事与信息元素，无多余杂乱内容。人物海报具备电影级镜头张力，景别、视角、光线共同服务情绪表达；文字既是信息也是设计元素，位置、大小、字体服务整体构图，留白主动参与视觉节奏。国潮风格传统与现代自然融合，无生硬拼贴。",
    "negative_prompts": "风格混乱跳变，色彩脏污溢出，构图失衡杂乱，元素堆砌冗余，文字排版拥挤，字体风格混乱，透视逻辑错误，比例失调变形，低分辨率模糊，塑料虚假质感，多余无关元素乱入，杂物装饰堆砌，字幕水印logo，光影生硬断层，画面空洞无物，过度锐化生硬，边缘锯齿毛躁，排版拥挤无留白，信息层级混乱，国潮元素生硬拼贴，人物神态僵硬失真，材质质感虚假",
    "examples": [
        {
            "category": "商业海报-香水广告",
            "natural": "海报采用对称构图，画面中央是一位女性的面部特写，占据画面上方三分之二，整体氛围神秘而优雅。她的目光微微向下，凝视着画面下方的深琥珀色香水瓶。光线从左侧斜上方打来，在她的颧骨和鼻梁上形成柔和的轮廓光，右侧脸则沉入深灰蓝色的阴影中，明暗过渡细腻自然。背景是渐变的深蓝至墨绿色，仿佛夜晚的密林，干净无多余装饰。女性的皮肤质感真实，颧骨处有轻微的毛孔和自然的肤色过渡，没有过度修饰；微启的嘴唇上有一抹暗红色调，与香水瓶的金属质感形成微妙呼应。香水瓶置于画面底部中央，玻璃瓶身的反光与高光细腻呈现，瓶内液体在光线下透出深琥珀色的通透感。文字信息精简克制，品牌名称以极细的无衬线字体置于画面顶部，与背景融为一体；香水名称以适中的体量居中排列在产品下方，颜色为淡淡的金色，与瓶身金属质感呼应；底部边缘是极小的产品辅助信息。视线从女性深邃的眼神自然流向下方的香水瓶，最终落在产品名称上。黑色、深蓝、墨绿与金色的组合沉静高级，主色调深蓝墨绿占70%，深灰蓝阴影辅助占25%，金色与暗红点缀占5%，低饱和冷调，留白充分，质感高级。",
            "structured": "【类别】海报设计\n【类型】商业海报（香水广告）\n【全局正向约束】\n  - 风格基础：电影感极简奢华风格全程统一，光影细腻，质感高级，无元素杂乱\n  - 质感基础：真实摄影质感，肌肤与玻璃材质表现精准，印刷级细腻度\n  - 构图逻辑：对称垂直分层构图，符合高端商业叙事节奏，透视准确\n【画面构图】\n  - 视觉引导：人物向下凝视的视线形成纵向引导，从面部自然流向香水瓶与产品名称\n  - 主体位置：水平50%居中，垂直40%偏上，人物与产品共占据70%视觉面积\n  - 画面比例：竖版9:16\n  - 画面精简约束：仅人物面部、香水瓶、渐变背景，不新增多余花草、摆件、装饰杂物\n【景别与三维画面视角】\n  - 距离维度：面部特写起步，产品中景收尾，兼顾情绪细节与产品展示\n  - 水平视角维度：正面，完整呈现面部神态与产品正面\n  - 垂直俯仰维度：微俯视，引导视线向下聚焦产品，带来沉静高级的心理感受\n  - 画面景深：人物与产品清晰锐利，背景柔和虚化，突出主体质感\n【主视觉处理】\n  - 核心主体：女性面部特写，深琥珀色香水瓶\n  - 人物表现：微俯视角度，视线向下，左侧斜上轮廓光，右侧阴影，神秘优雅情绪\n  - 质感呈现：摄影风格，真实肌肤质感，玻璃通透感，金属反光细腻\n【文字与信息层级】\n  - 主标题：品牌名称（极细无衬线字体，顶部，与背景融合，低权重）\n  - 副标题：香水名称（适中体量，淡金色，产品下方居中，中高权重）\n  - 辅助信息：产品细节说明（极小体量，底部边缘，低权重）\n  - 字体风格：现代无衬线，纤细优雅，贴合高端调性\n  - 文字与画面关系：文字克制融入画面，不抢夺主视觉焦点\n【质感与细节】\n  - 材质表现：肌肤细腻纹理，玻璃通透反光，金属冷硬光泽，渐变背景柔和过渡\n  - 光影层次：左侧斜上主光，右侧暗部阴影，明暗对比强烈，过渡细腻\n  - 印刷质感：印刷级高清，光影过渡柔和，边缘清晰无过度锐化\n【专属风格元素】不适用\n【留白与呼吸感】\n  - 留白设计：画面顶部与两侧大面积留白，产品下方疏朗空间，引导视线聚焦\n  - 空间节奏：上方饱满（面部），下方疏朗（产品与文字），节奏沉稳高级\n【技术参数建议】\n  - 质感补充：轻微铜版纸印刷质感，增强高端商业海报真实感\n  - 技术禁止项：不出现分辨率、DPI等无效参数\n【风格标签】神秘优雅、电影感、高级极简、奢华质感\n【画面收尾精简约束】画面无额外装饰、杂物、冗余元素，所有视觉元素服务高端品牌气质传递，不抢夺产品与人物主体焦点。"
        },
        {
            "category": "活动海报-汉服文化节",
            "natural": "这是一张国潮风格的活动海报，采用竖构图，整体氛围传统雅致又具现代设计感。顶部以金色行书书法字书写“汉服文化节”五个大字，字体粗壮有力，笔画中带有自然的飞白和墨迹边缘，仿佛毛笔直接写在深红色背景上。文字下方，一幅工笔风格的仕女插画徐徐展开——身着交领襦裙的仕女侧身而立，衣袂在微风中扬起，裙摆上的传统缠枝花纹以金色线描精细勾勒。背景从顶部的深红渐变到底部的米白，仿佛一场视觉的日落，干净无多余杂乱纹饰。仕女身后的空间中，几缕祥云以白色和淡金色点缀，云纹曲线保留传统韵味，又经过几何化处理，兼具现代平面设计的简洁感。人物面部以淡彩晕染，工笔线描与没骨渲染相结合，精致而不失形式感。底部以稍小的无衬线字体列出活动日期和地点，黑色字体与上方的书法形成古今对话；最下方的协办单位信息以极小的体量排列，清晰但不抢眼。整张海报视觉重心在顶部标题和中间人物，下方文字区域疏朗有致。红色、金色、米白的配色喜庆雅致，主色调中国红占70%，米白辅助占25%，金色点缀占5%，中饱和暖调，大面积留白避免拥挤感，传统元素与现代排版自然平衡。",
            "structured": "【类别】海报设计\n【类型】活动海报（汉服文化节）\n【全局正向约束】\n  - 风格基础：国潮风格全程统一，传统元素与现代设计融合自然，无生硬拼贴\n  - 质感基础：书法飞白质感，工笔线条细腻，宣纸底色温润\n  - 构图逻辑：竖版自上而下流动构图，符合活动宣传信息传递节奏\n【画面构图】\n  - 视觉引导：顶部标题最先吸引目光，顺势向下流向人物插画，最终落到底部活动信息\n  - 主体位置：水平50%居中，垂直45%居中，标题与人物共占据70%视觉面积\n  - 画面比例：竖版9:16\n  - 画面精简约束：仅书法标题、仕女插画、祥云、活动文字，不新增多余纹饰、杂物、冗余装饰\n【景别与三维画面视角】\n  - 距离维度：中景人物，兼顾整体造型与服饰细节\n  - 水平视角维度：正侧面，展现仕女侧身轮廓与衣袂飘动的动感\n  - 垂直俯仰维度：平视，平等雅致的观看视角，贴合传统文化氛围\n  - 画面景深：人物清晰，背景祥云柔和虚化，层次舒展\n【主视觉处理】\n  - 核心主体：金色书法标题，工笔仕女插画\n  - 人物表现：侧身而立，衣袂飘动，工笔淡彩，温婉雅致气质\n  - 质感呈现：书法飞白墨迹，工笔精细勾线，宣纸般底色质感\n【文字与信息层级】\n  - 主标题：“汉服文化节”（金色行书书法，顶部，最大视觉权重）\n  - 副标题：无\n  - 辅助信息：活动日期地点（黑色无衬线体，底部，中低权重）；协办单位（极小体量，最底部，低权重）\n  - 字体风格：书法体（标题）+ 现代无衬线体（信息），形成古今对比\n  - 文字与画面关系：标题与画面共生，信息清晰独立，层级分明\n【质感与细节】\n  - 材质表现：书法笔墨纹理，工笔设色温润，云纹轻薄通透，宣纸底色细腻\n  - 光影层次：柔和平光，色彩过渡自然，金色部分微有光泽感\n  - 印刷质感：印刷级高清，线条干净锐利，色彩浓淡有致\n【专属风格元素】\n  - 国潮类：传统纹样（缠枝纹、祥云变形）；国潮色彩（中国红、金色、米白）；传统技法（书法笔触、工笔线描）；现代融合（几何化云纹、现代排版）\n【留白与呼吸感】\n  - 留白设计：人物周围大量米白留白，底部信息区域疏朗空间，呼吸感充足\n  - 空间节奏：标题饱满，中部疏朗，底部精炼，节奏舒缓雅致\n【技术参数建议】\n  - 质感补充：轻微宣纸纹理与烫金效果，增强国潮海报真实印刷质感\n  - 技术禁止项：不出现分辨率、DPI等无效参数\n【风格标签】国潮新韵、工笔雅致、传统再生、活动宣传\n【画面收尾精简约束】画面无多余纹饰、杂物、冗余装饰，所有元素服务活动主题传递，不抢夺视觉焦点。"
        },
        {
            "category": "电影海报-悬疑剧情",
            "natural": "一张充满张力的悬疑电影海报，采用极低角度仰拍，整体氛围压抑而充满故事感。画面左侧是一位男性角色的背影，他身穿深灰色风衣，肩线硬朗，脖子微微前倾，正望向右侧远方；右侧三分之二的画面是阴沉沉的天空，深灰与铅蓝的云层翻滚，云隙中透出一道冷白色的光，照亮云层边缘，也在地平线处形成一条狭长的光带。人物的风衣在风中向后翻动，布料褶皱真实而有重量感，左侧肩头有细微的雨滴痕迹。他紧握的右拳和微微收紧的肩部线条，传达出紧绷蓄势的情绪；前景轮廓锐利，背景云层略微虚化，形成浅景深效果，暗示人物与远方的某种关联。文字信息被压到最低限度：片名以粗犷的无衬线大写字体置于画面底部居中，铅灰色字体边缘微微粗糙，仿佛被风化过；下方是一行极小的映期信息。没有任何多余装饰元素，画面本身就是全部信息。冷灰色、铅蓝、白光的组合冷峻压抑，主色调深灰铅蓝占70%，冷白云隙光辅助占25%，无多余点缀色，低饱和冷调，大面积天空作为视觉留白，氛围感极强，观众会忍不住好奇人物的注视方向与即将面对的故事。",
            "structured": "【类别】海报设计\n【类型】电影海报（悬疑剧情）\n【全局正向约束】\n  - 风格基础：电影感悬疑风格全程统一，光影冷峻，叙事张力强，无元素杂乱\n  - 质感基础：真实摄影质感，布料褶皱厚重，云层层次自然\n  - 构图逻辑：低角度仰拍左右对位构图，符合悬疑电影叙事张力\n【画面构图】\n  - 视觉引导：人物注视方向形成横向引导，从左至右引向远方光带，激发观众好奇心\n  - 主体位置：水平35%偏左，垂直50%居中，人物与天空共占据70%视觉面积\n  - 画面比例：横版16:9\n  - 画面精简约束：仅人物背影、阴沉天空、片名文字，不新增多余景物、装饰、杂物\n【景别与三维画面视角】\n  - 距离维度：全景人物，兼顾人物姿态与天空环境格局\n  - 水平视角维度：背面，隐藏面部表情，强化悬疑感\n  - 垂直俯仰维度：极低仰视角，凸显人物力量感与天空压迫感，增强张力\n  - 画面景深：前景人物清晰，远景云层虚化，浅景深强化故事感\n【主视觉处理】\n  - 核心主体：男性背影，阴沉云层天空，云隙光带\n  - 人物表现：极低仰拍背影，风衣翻动，紧握右拳，蓄势待发的紧绷情绪\n  - 质感呈现：真实摄影感，布料褶皱沉重有分量，雨滴痕迹细腻，云层流动自然\n【文字与信息层级】\n  - 主标题：片名（粗犷无衬线大写，铅灰色风化质感，底部居中，中权重）\n  - 副标题：无\n  - 辅助信息：映期（极小体量，片名下方，低权重）\n  - 字体风格：无衬线粗体，边缘风化粗糙，贴合悬疑冷峻调性\n  - 文字与画面关系：文字克制退让，让画面自身承载叙事\n【质感与细节】\n  - 材质表现：风衣面料厚重挺括，云层蓬松有体积感，雨滴湿痕真实\n  - 光影层次：冷白云隙光为主光源，明暗对比强烈，氛围感厚重\n  - 印刷质感：印刷级高清，景深过渡自然，云层层次丰富无过度锐化\n【专属风格元素】不适用\n【留白与呼吸感】\n  - 留白设计：大面积天空本身作为视觉留白，承载压抑氛围\n  - 空间节奏：左实右虚，下部紧凑上部开阔，形成强烈对比张力\n【技术参数建议】\n  - 质感补充：轻微电影颗粒感，增强影院海报真实氛围感\n  - 技术禁止项：不出现分辨率、DPI等无效参数\n【风格标签】电影感张力、压抑悬疑、极简叙事、氛围海报\n【画面收尾精简约束】画面无多余景物、装饰、杂物，所有元素服务悬疑故事氛围，不抢夺叙事焦点。"
        }
    ]
}

POSTER_DESIGN_EN = {
    "name": "Poster Design Master (Visual Narrative Edition)",
    "description": "Professional poster design director crafting visually compelling descriptions. Semantic weight priority: theme emotion → style direction → 3D perspective → color hierarchy → visual & typography. Built-in 3D perspective, 70%/25%/5% color ratio, dual texture constraints. Covers modern minimalist, Guochao, cinematic, vintage styles.",
    "input_template": "Step-by-step expansion for poster design: 1) Analyze theme and purpose, identify poster type; 2) Define style direction (modern minimalist/Guochao/cinematic/vintage); 3) Design composition, visual focus, and 3D perspective (distance, angle, tilt); 4) Build color hierarchy—main 70%, secondary 25%, accent 5%; 5) Handle image-text relationship and visual details; 6) Generate {mode} description. Natural mode uses 2-3 paragraphs: composition & tone → details & texture → typography & hierarchy.\n\nCore principles:\n- Visual and information unified—text and image enhance each other\n- Portrait posters use cinematic language—shot scale, perspective, lighting build emotion\n- Text is both information and design element—position, size, color serve composition\n- Guochao integrates traditional motifs with contemporary design naturally\n- Every visual element serves the core message",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3). First: composition and overall tone. Second: main visual, color, and texture. Third: typography and information hierarchy. Vivid, visual language, no mechanical parameters.",
        "structured": "[Category] Poster Design\n[Type] Commercial/Movie/Event/Packaging, etc.\n[Theme Information]\n  - Theme description: core concept conveyed\n  - Key message: what needs to stand out (brand/event/product)\n  - Emotional tone: what feeling the audience should get\n[Composition & Visual Focus]\n  - Composition type: symmetry/rule of thirds/diagonal/centered/open space\n  - Visual focus: where the viewer's eye lands first\n  - Visual path: how the eye is guided across the poster\n[Color System]\n  - Main color: sets overall mood\n  - Secondary color: adds depth and richness\n  - Accent color: creates contrast and surprise\n  - Color relationship: warm/cool/complementary/analogous/value contrast\n[Main Visual Treatment]\n  - Image elements: content and style of the main visual\n  - Portrait handling (if applicable): shot scale, perspective, lighting, emotional expression\n  - Texture presentation: is it illustrative, photographic, or vector? details and grain\n[Typography & Information Hierarchy]\n  - Primary headline: core text with greatest visual weight\n  - Secondary headline/key info: important but supporting\n  - Auxiliary info: details, dates, locations\n  - Font style: serif/sans-serif/calligraphic/handwritten\n  - Text-image relationship: does text blend into the image or stand apart?\n[White Space & Breathing]\n  - White space design: where and why\n  - Spatial rhythm: density variation, visual comfort\n[Style Features] Modern minimalist/Guochao/Cinematic/Vintage, etc.\n[Print Quality] Print-grade high definition, realistic texture, no over-sharpening\n[Style Tags] 3-5 keywords summarizing the overall aesthetic"
    },
    "task_requirements": [
        "Use vivid artistic design language—avoid mechanical parameters",
        "User-specified elements (theme, style, composition, color) are hard constraints; supplement only unspecified dimensions",
        "Include composition & visual focus, color system, main visual treatment, typography & hierarchy",
        "Portrait posters use cinematic language—shot scale, perspective, lighting, emotion",
        "Color description specifies main/secondary/accent and their relationships",
        "Text is both information and design element—position, size, style serve composition",
        "Avoid over-sharpening and over-saturation; emphasize natural color transitions",
        "Guochao integrates traditional and contemporary naturally—avoid forced collage",
        "All visual elements serve the core message",
        "Follow 70%/25%/5% color ratio; 3D perspective follows user input priority"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "language": "en"
    },
    "examples": [
        {
            "natural": "A symmetrical composition anchors the poster: a female face in close-up occupies the upper two-thirds of the frame. Her gaze is directed slightly downward, fixed on the product below—a deep amber perfume bottle. Light strikes from the upper left, tracing a soft rim across her cheekbone and nose, while the right side of her face sinks into deep grey-blue shadow, creating a mysterious, elegant mood.\n\nThe background gradient shifts from deep blue to dark green, like a night forest. Her skin texture is natural—subtle pores on the cheekbones, gentle transitions in skin tone, no over-retouching. Her slightly parted lips carry a dark red tint, subtly echoed in the perfume bottle's metallic cap. The bottle sits centered at the bottom, its glass reflections and highlights meticulously rendered, the liquid within glowing with a warm amber translucency.\n\nText is minimal: the brand name in an ultra-fine sans-serif sits at the top, blending into the background. The perfume name is placed directly below the bottle in a moderate-sized light gold typeface, echoing the metal cap. Fine print at the bottom edge lists product details. Open space abounds—the viewer's eye flows naturally from the woman's gaze down to the bottle, then settles on the product name. Black, deep blue, dark green, and gold combine to create a quiet, mysterious, and sophisticated presence.",
            "structured": "[Category] Poster Design\n[Type] Commercial (Perfume)\n[Theme Information]\n  - Theme description: Premium perfume brand image\n  - Key message: brand name, perfume name, brand identity\n  - Emotional tone: Mysterious, elegant, quiet, luxurious\n[Composition & Visual Focus]\n  - Composition type: Symmetrical, vertical layering\n  - Visual focus: The woman's eyes—downward gaze guides to product\n  - Visual path: From face down to bottle and product name\n[Color System]\n  - Main color: Deep blue to dark green gradient—mysterious and calm\n  - Secondary color: Grey-blue shadows\n  - Accent color: Gold (product name), dark red (lip and bottle detail)\n  - Color relationship: Cool palette with gold and red accents\n[Main Visual Treatment]\n  - Image elements: Female close-up (upper 2/3), perfume bottle (lower center)\n  - Portrait handling: Eye-level, slightly low angle, downward gaze, soft rim light from upper left\n  - Texture presentation: Photographic, natural skin, glass transparency, metal reflections\n[Typography & Information Hierarchy]\n  - Primary headline: Brand name (ultra-fine sans-serif, top, blends with background)\n  - Secondary headline: Perfume name (moderate size, light gold, below bottle)\n  - Auxiliary info: Product details (fine print, bottom edge)\n  - Font style: Modern sans-serif, slender and elegant\n  - Text-image relationship: Restrained, integrated, never competing\n[White Space & Breathing]\n  - White space design: Top and sides have open space for focus\n  - Spatial rhythm: Dense above (face), open below (product and text)\n[Style Features] Cinematic, minimalist luxury, mysterious elegance\n[Print Quality] Print-grade high definition, delicate light transitions, no over-sharpening\n[Style Tags] Mysterious elegance, cinematic, premium minimal"
        },
        {
            "natural": "This Guochao event poster uses a vertical composition. At the top, the title \"Hanfu Culture Festival\" is written in bold gold running script calligraphy—thick strokes with natural dry-brush textures and ink edges, as if painted directly onto a deep red background. Below the title, a gongbi-style illustration unfolds: a lady in a cross-collared robe stands in profile, her sleeves lifting in the breeze, the traditional floral patterns on her skirt meticulously outlined in gold linework.\n\nThe background transitions from deep red at the top to cream at the bottom—like a visual sunset. Behind the figure, auspicious clouds in white and pale gold float through the space, their curves retaining traditional charm while simplified into geometric forms that feel contemporary. The face is rendered in soft washes—gongbi linework combined with boneless color application—achieving a balance of classical precision and modern graphic clarity.\n\nThe date and location are set at the bottom in smaller black sans-serif type, creating a dialogue between ancient calligraphy and modern typography. Co-organizer information is arranged in the smallest possible type at the bottom edge—present but unobtrusive. The visual focus moves from the bold title above, through the illustrated figure, to the clean information below. Red, gold, and cream create a palette that's warm and celebratory, yet the generous white space prevents crowding. Traditional motifs and contemporary layout find harmony here.",
            "structured": "[Category] Poster Design\n[Type] Event (Hanfu Culture Festival)\n[Theme Information]\n  - Theme description: Hanfu Culture Festival promotional poster\n  - Key message: Event name, date, location\n  - Emotional tone: Traditional, elegant, neo-Guo fashion\n[Composition & Visual Focus]\n  - Composition type: Vertical, top-to-bottom flow\n  - Visual focus: The bold calligraphy title at the top\n  - Visual path: From title to illustrated figure to bottom information\n[Color System]\n  - Main color: Chinese red (60%)—festive and traditional\n  - Secondary color: Cream (30%)—provides open space and breathing\n  - Accent color: Gold (10%)—calligraphy title and linework\n  - Color relationship: Red and cream contrast, gold bridges them\n[Main Visual Treatment]\n  - Image elements: Calligraphy title (top) + gongbi-style lady illustration (middle)\n  - Portrait handling: Side view, cross-collared robe, flowing sleeves, gongbi plus boneless rendering\n  - Texture presentation: Dry-brush ink effects, gongbi linework, rice paper-like texture\n[Typography & Information Hierarchy]\n  - Primary headline: \"Hanfu Culture Festival\" (gold running script, top)\n  - Secondary headline: None\n  - Auxiliary info: Date and location (black sans-serif, bottom)\n  - Font style: Calligraphic (title) + sans-serif (info)\n  - Text-image relationship: Title and illustration co-exist, info stands cleanly below\n[White Space & Breathing]\n  - White space design: Open space around the figure, room below for information\n  - Spatial rhythm: Dense at top, open in middle, refined at bottom\n[Style Features] Guochao, traditional gongbi meets modern minimalism\n[Print Quality] Print-grade high definition, clean lines, rich and subtle color\n[Style Tags] Neo-Guochao, gongbi elegance, tradition reborn"
        },
        {
            "natural": "A tension-filled movie poster. Shot from an extreme low angle, a male figure's back fills the left third of the frame. He wears a dark grey trench coat—shoulders broad, neck leaning slightly forward, his gaze fixed on something far to the right. The remaining two-thirds of the frame is occupied by a heavy, overcast sky: deep grey and lead-blue clouds churning, with a single cold white beam of light piercing through a gap, illuminating the cloud edges and forming a narrow strip of light along the horizon.\n\nHis coat flaps backward in the wind—the fabric folds feel weighty and real, fine raindrops catching on his left shoulder. The back of his head reveals no expression, but his clenched right fist and slightly tensed shoulder lines convey a coiled, ready tension. The foreground is sharp, while the clouds in the distance carry a shallow depth of field—this cinematic language suggests something about to happen between him and what lies ahead.\n\nText is minimized: the film title sits in bold sans-serif uppercase at the bottom center, in lead grey with slightly roughened edges, as if weathered. Below it, a single line of tiny release date information. No decorative elements. The image alone tells the story. The palette of cool greys, lead blue, and white light creates a mood of restrained suspense—the viewer can't help but wonder: what is he looking at? What's about to happen?",
            "structured": "[Category] Poster Design\n[Type] Movie Poster (Suspense/Drama)\n[Theme Information]\n  - Theme description: Suspense/drama film promotional poster\n  - Key message: Film title, release date\n  - Emotional tone: Tense, suspenseful, charged, restrained\n[Composition & Visual Focus]\n  - Composition type: Extreme low angle, character left/sky right\n  - Visual focus: The figure's shoulder and neck line vs. the distant light beam\n  - Visual path: Left to right—from the figure's gaze direction toward the distant light\n[Color System]\n  - Main color: Deep grey, lead blue (70%)—cold and tense\n  - Secondary color: Cold white (20%)—the light break creates focus\n  - Accent color: None—highly restrained\n  - Color relationship: Value contrast within a cool palette, light vs. dark tension\n[Main Visual Treatment]\n  - Image elements: Male back (left) + churning storm sky (right)\n  - Portrait handling: Extreme low angle, back view, dark coat, clenched fist, coiled tension\n  - Texture presentation: Photographic, heavy fabric folds, raindrop traces, cloud motion\n[Typography & Information Hierarchy]\n  - Primary headline: Film title (bold sans-serif uppercase, bottom center, weathered grey)\n  - Secondary headline: None\n  - Auxiliary info: Release date (tiny, below title)\n  - Font style: Sans-serif bold with weathered edge\n  - Text-image relationship: Minimal text—the image tells the story\n[White Space & Breathing]\n  - White space design: The sky itself is the white space\n  - Spatial rhythm: Open above, tight below, figure vs. sky contrast\n[Style Features] Cinematic, suspenseful, minimalist narrative\n[Print Quality] Print-grade high definition, natural depth of field, cloud layers, no over-sharpening\n[Style Tags] Cinematic tension, restrained suspense, minimalist story"
        }
    ]
}

ECOMMERCE_ZH = {
    "name": "电商场景与产品摄影大师",
    "description": "专业电商视觉与产品摄影指导，为全品类电商产品打造高转化视觉描述。语义权重优先级：产品类型卖点→三维视角构图→场景氛围→色彩配比→道具搭配→光影质感。内置三维度视角、70%/25%/5%色彩配比、双重质感约束与画面精简约束，强化产品质感、光影高级感与购买驱动力。覆盖美妆、3C、食品、首饰、家居等品类赛道。",
    "input_template": "逐步思考扩写电商产品场景描述，严格遵循语义权重顺序：产品类型与核心卖点→三维拍摄视角与构图布局→场景氛围与基调→色彩配比方案→道具搭配逻辑→光影质感设计；完整执行 6 步标准化扩写逻辑：\n1）分析产品类型（美妆/3C/食品/首饰/家居等）与目标平台调性，明确核心卖点与购买触发点；\n2）确定画幅格式（竖版9:16或横版16:9）；规划三维度拍摄视角：视距远近、水平角度、垂直俯仰，优先沿用用户指定维度，未指定项随机合规组合；\n3）设计场景与整体氛围：明确背景风格（极简/生活化/ins风/科技感/奢华等），所有场景元素服务衬托产品；\n4）构思色彩方案：主色70%、辅助色25%、点缀色5%，产品主体色为主色调，背景道具为辅助色，细节亮点为点缀色，标注饱和度层级；\n5）规划道具与搭配逻辑：筛选衬托产品气质的道具，明确材质、位置与虚化程度，控制道具权重不抢产品主角；\n6）设计光影体系：明确主光方向、色温、软硬，刻画产品细节与质感，融入营销与品牌信息，生成对应模式描述。自然模式2-3段，顺序：场景氛围 → 产品细节质感 → 构图与购买感受。\n\n核心原则：\n- 产品是绝对主角：所有道具、光线、背景都服务于突出产品核心卖点\n- 质感是产品语言：金属冷峻、玻璃通透、织物柔软、膏体绵密都需清晰可感\n- 光线是质感化妆师：好的光线让产品显得高级、可信、值得拥有\n- 色彩严格配比：产品主体色占主导，背景道具色辅助，点缀色制造焦点\n- 三维视角合规：用户指定维度沿用，未指定维度按电商审美合规随机\n- 画面精简约束：仅保留核心产品与必要衬托道具，不自动生成多余摆件\n- 技术参数仅用于提升可控性，自然模式剔除所有数字技术参数",
    "output_format_suffix": {
        "natural": "自然段落（2-3段），首段确立场景基调、背景环境与整体氛围，次段展开产品形态、材质肌理与光影细节，末段补充构图逻辑、视觉引导与整体购买感受。语言富有画面感与高级感，全程无焦距、光圈、分辨率类数字技术参数，强化产品主体地位、真实质感与画面精简约束，保证画面干净聚焦、卖点突出、转化力强。",
        "structured": "【类别】电商场景\n【产品类型】美妆护肤/3C电子产品/食品饮料/首饰配饰/家居用品等\n【目标平台】小红书/抖音/天猫/京东等\n【全局正向约束】\n  - 主体基础：产品为绝对核心，比例准确，形态规整，无变形失真\n  - 质感基础：产品材质表现真实，肌理细腻，光影过渡自然\n  - 画面逻辑：三维视角符合电商拍摄审美，构图聚焦卖点，无冗余元素抢戏\n【画面构图】\n  - 视觉引导：视线流动逻辑，依托产品形态、光线高光、道具线条三重引导，焦点始终落在产品核心卖点\n  - 主体位置：产品核心区域水平与垂直占比，产品主体占据 70% 视觉权重，背景道具共占 30%\n  - 画面比例：宽高比（16:9 横版 / 9:16 竖版 / 1:1 方图）\n  - 画面精简约束：仅保留核心产品与必要衬托道具，不额外生成多余摆件、装饰、杂物\n【景别与三维拍摄视角】\n  - 距离维度（景别对应）：微距细节特写 / 产品标准特写 / 产品中景带场景 / 全景氛围图，对应卖点展示层级\n  - 水平视角维度：水平拍摄角度（正面/四分之三斜侧/正侧面），标注产品展现效果与卖点呈现\n  - 垂直俯仰维度：垂直拍摄角度（垂直俯拍/45°斜拍/平视/小仰拍），对应心理感受与卖点展示（俯拍展全貌/斜拍显立体/平视显真实）\n  - 画面景深：产品清晰锐利、背景道具适度虚化 / 前后景都清晰，标注虚实层次对应的主次关系\n【产品核心卖点】\n  - 核心吸引力：最突出的细节、质感或设计亮点\n  - 购买触发点：激发拥有欲的核心价值点\n【场景与道具搭配】\n  - 场景氛围：整体风格、背景环境、空间与季节感\n  - 主要道具：材质、颜色、位置与虚化程度\n  - 搭配逻辑：道具如何衬托产品气质，为何不抢主角\n【产品质感与光影】\n  - 外观形态：产品造型、色彩、整体轮廓\n  - 质感表现：对应材质的专属肌理（金属拉丝/玻璃通透/奶油肌理/织物柔软等）\n  - 光影设计：主光方向、色温、软硬，辅助光作用，特殊反光/透光效果\n【色彩配比】\n  - 主色调：产品主体色，占比70%，奠定视觉核心\n  - 辅助色：背景与道具色，占比25%，衬托产品氛围\n  - 点缀色：细节亮点色，占比5%，制造视觉焦点\n【营销信息融合】\n  - 品牌/促销信息：呈现方式与位置，如何自然融入画面\n【技术参数建议】（仅 structured 模式使用）\n  - 布光参考：对应布光方案的视觉效果说明，无数值参数\n  - 质感补充：可按需添加柔光质感、哑光肌理、通透光效等效果术语，搭配说明\n  - 技术禁止项：不出现焦距、光圈、分辨率、渲染参数等无效数值参数\n【风格标签】3-5个关键词概括视觉气质与转化方向\n【画面收尾精简约束】画面无额外无关道具、多余装饰、杂乱背景填充，所有元素仅服务突出产品卖点，不抢夺产品主体视觉焦点。"
    },
    "task_requirements": [
        "natural模式使用有画面感、带购买驱动力的描述语言，严禁出现焦距、光圈、分辨率等数字技术参数",
        "structured模式可保留【技术参数建议】字段，参数附带文字释义，与产品风格氛围精准匹配",
        "全文前置强化产品核心卖点与真实质感，区分不同品类材质表现差异，提升识别优先级",
        "产品始终为绝对主角，道具仅作衬托，层级分明不抢戏，规避无效装饰与画面杂乱",
        "光影采用具象化分层描写，明确方向、色温、软硬与质感塑造作用，光影过渡自然符合物理逻辑",
        "双重质感约束叠加，同品类下材质、光影、色调统一，杜绝材质虚假、反光失真",
        "严格执行70%/25%/5%色彩配比，产品主体色占主导，标注饱和度层级，无高饱和撞色",
        "三维度视角遵循用户输入优先，未指定维度合规随机组合，禁止违和猎奇角度",
        "营销与品牌信息自然融入画面，不生硬张贴、不突兀悬浮",
        "严格执行画面精简约束，仅保留核心产品与必要衬托道具，美妆3C首饰保留专属材质表现"
    ],
    "constraints": {
        "max_length": 1000,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "分辨率", "DPI", "色彩模式", "焦距", "光圈", "帧率", "码率", "采样率", "编码器", "HDR", "杜比", "字幕", "水印", "logo", "完美对称", "零瑕疵", "塑料感", "崩坏", "扭曲"],
        "grounding_support": True,
        "language": "zh",
        "natural_mode_forbidden_params": ["mm", "f/", "DPI", "分辨率", "渲染参数", "色彩模式"],
        "structured_param_allowance": "仅允许在【技术参数建议】字段使用布光参考、质感补充定性描述与效果释义，禁止使用焦距、光圈、分辨率等数值参数，其余字段禁止所有技术数字参数"
    },
    "positive_constraints": "产品为绝对主角，质感真实细腻，光影柔和高级，画面干净克制，色彩配比和谐，构图聚焦卖点。所有道具、背景、光线均服务于突出产品核心优势，无多余元素抢夺注意力。材质表现符合物理特性（金属冷峻、玻璃通透、织物柔软、膏体绵密），光影过渡自然无硬伤，营销信息自然融入不突兀，整体兼具高级感与可信度，激发购买欲望。",
    "negative_prompts":  "产品变形失真，材质虚假塑料感，光影杂乱过曝，色彩脏污溢出，道具喧宾夺主，构图失衡杂乱，元素堆砌冗余，透视比例错误，低分辨率模糊，多余杂物乱入，装饰摆件堆砌，字幕水印logo，光影生硬断层，营销贴纸生硬，过度锐化生硬，边缘锯齿毛躁，反光虚假不自然，背景杂乱抢戏",
    "examples": [
        {
            "category": "美妆护肤-精华液",
            "natural": "一瓶精华液静置在浅灰色大理石板面上，整体氛围极简高级，干净克制。瓶身是厚实的透明玻璃，透过柔和光线可以看到内部淡粉色的液体微微流动，澄澈又有分量感。金色的瓶盖带有细腻的拉丝纹理，在侧光下折射出温暖的金属光泽，精致却不张扬。瓶身标签是极简的白色，只印着品牌名与产品名，字体纤细优雅，像是用最细的笔尖书写而成。光线从左上角斜射过来，在瓶身表面形成一道柔和的弧形高光，把玻璃的通透感放大到极致。液体内部有几缕细微的光影飘动，像是被搅动后正在缓缓静止的瞬间。瓶口处的滴管设计朝向画面前方，橡胶头部的哑光质感与玻璃的光滑形成鲜明对比，实用又充满细节。画面左下角放着一片干燥的尤加利叶，灰绿色的叶片为画面添了一抹自然呼吸感，但始终处在焦外，丝毫不会抢夺产品的视觉主导权。整体构图简单克制，每一处细节都清晰可辨，这种不刻意的高级感，正是高端护肤品牌传递的信赖与质感。主色调透明玻璃+淡粉液体占70%，浅灰大理石背景辅助占25%，尤加利叶绿点缀占5%，低饱和冷调，干净通透。",
            "structured": "【类别】电商场景\n【产品类型】美妆护肤（精华液）\n【目标平台】小红书/高端美妆线\n【全局正向约束】\n  - 主体基础：瓶身比例准确，形态规整，玻璃与金属材质分界清晰\n  - 质感基础：玻璃通透真实，金属拉丝细腻，橡胶哑光自然\n  - 画面逻辑：45°斜拍符合美妆产品拍摄审美，焦点落在瓶身核心区域\n【画面构图】\n  - 视觉引导：弧形高光引导视线落向瓶身中央，滴管朝向强化产品功能感知\n  - 主体位置：水平45%偏左，垂直48%居中，产品瓶身占据70%视觉面积\n  - 画面比例：3:2（适配电商详情与小红书）\n  - 画面精简约束：仅精华液、大理石台面、焦外尤加利叶，不新增多余护肤品、装饰、杂物\n【景别与三维拍摄视角】\n  - 距离维度：产品标准特写，兼顾整体形态与材质细节\n  - 水平视角维度：四分之三斜侧，同时展现瓶身正面与侧面厚度\n  - 垂直俯仰维度：45°斜拍，兼顾瓶盖质感与瓶身液体通透感\n  - 画面景深：产品主体清晰锐利，背景道具适度虚化，主次分明\n【产品核心卖点】\n  - 核心吸引力：金色拉丝瓶盖+通透玻璃瓶身+可见精华液体\n  - 购买触发点：高级质感、成分可视、值得信赖的高端护肤体验\n【场景与道具搭配】\n  - 场景氛围：极简ins风，浅灰大理石台面，干净通透\n  - 主要道具：浅灰色大理石台面，焦外干燥尤加利叶\n  - 搭配逻辑：绿植增添自然呼吸感，虚化处理不抢产品主角\n【产品质感与光影】\n  - 外观形态：厚实圆柱玻璃瓶，金色瓶盖，白色极简标签\n  - 质感表现：玻璃通透带重量感，金属细腻拉丝，橡胶哑光柔和\n  - 光影设计：左上斜射侧柔光，弧形高光塑造玻璃体积，柔和阴影不显生硬\n【色彩配比】\n  - 主色调：透明玻璃+淡粉液体，占比70%\n  - 辅助色：浅灰大理石背景，占比25%\n  - 点缀色：尤加利叶灰绿，占比5%\n【营销信息融合】\n  - 品牌信息通过瓶身标签自然呈现，无额外促销贴纸\n【技术参数建议】\n  - 布光参考：单侧柔光箱布光，塑造通透玻璃质感，阴影柔和\n  - 质感补充：轻微大理石肌理、玻璃细微划痕，增强真实产品摄影感\n  - 技术禁止项：不出现焦距、光圈等无效参数\n【风格标签】高级极简、通透质感、ins风护肤、高端可信\n【画面收尾精简约束】画面无多余护肤品、装饰摆件、杂乱背景，所有元素服务突出产品高级质感，不抢夺瓶身主体视觉焦点。"
        },
        {
            "category": "3C数码-无线耳机",
            "natural": "一对深灰色磨砂质感的无线耳机静置在黑色织物表面，充电仓半开在一旁，像是刚被取出的自然状态，整体氛围极简克制，充满冷静的科技感。耳机外壳的哑光材质让光线变得柔和收敛，几乎没有刺眼的反射，只有一道低对比度的弧光沿着耳机柄缓缓流动，精准勾勒出人体工学曲线的顺滑手感。两只耳机并排摆放，像一对并肩的伙伴。充电仓的盖子打开到自然角度，内部的金色充电触点清晰可见，细节处暗藏品质感。耳机柄顶端的触控区域有极细微的同心圆纹理，需要凑近才能注意到，却处处透着做工的用心。画面里没有其他道具——没有充电线，没有包装盒，没有任何多余的东西，产品本身就是全部的视觉重心。光线从正上方与左右两侧同时打来，几乎没有生硬阴影，让产品的每一个曲面都被均匀照亮。这种布光方式让深灰色的磨砂质感显得干净、高级、完全可信。垂直俯拍的角度让画面呈现出近乎完美的对称秩序感，规整利落，放在电商详情页里，会让用户忍不住多停留几秒。主色调深灰磨砂机身占70%，黑色织物背景辅助占25%，金色触点点缀占5%，低饱和冷调，简洁专业。",
            "structured": "【类别】电商场景\n【产品类型】3C电子产品（无线耳机）\n【目标平台】天猫/京东数码品类\n【全局正向约束】\n  - 主体基础：耳机比例准确，形态规整，人体工学曲线流畅\n  - 质感基础：磨砂哑光质感真实细腻，金属触点光泽自然\n  - 画面逻辑：垂直俯拍符合3C产品展示审美，对称构图显专业\n【画面构图】\n  - 视觉引导：对称构图引导视线聚焦中心，充电仓与耳机形成呼应\n  - 主体位置：水平50%居中，垂直50%居中，耳机与充电仓占据70%视觉面积\n  - 画面比例：1:1方图（适配电商主图）\n  - 画面精简约束：仅耳机、充电仓、织物背景，不新增充电线、包装盒、多余数码配件\n【景别与三维拍摄视角】\n  - 距离维度：产品特写，完整展示耳机与充电仓组合\n  - 水平视角维度：正面，对称呈现双耳机与充电仓\n  - 垂直俯仰维度：垂直俯拍，展示产品全貌与对称秩序感\n  - 画面景深：前后景均清晰，突出产品细节与规整感\n【产品核心卖点】\n  - 核心吸引力：磨砂哑光质感+人体工学顺滑曲线+精致触点细节\n  - 购买触发点：干净高级的科技感，细节处见品质\n【场景与道具搭配】\n  - 场景氛围：极简科技风，黑色织物背景，沉稳专业\n  - 主要道具：黑色哑光织物背景\n  - 搭配逻辑：无多余道具，产品本身即是主角，减少视觉干扰\n【产品质感与光影】\n  - 外观形态：深灰色哑光外壳，耳机柄弧线流畅，半开充电仓\n  - 质感表现：磨砂低反光质感，金色触点金属光泽，同心圆细微纹理\n  - 光影设计：多角度顶光+侧柔光，均匀布光几乎无阴影，凸显磨砂细腻质感\n【色彩配比】\n  - 主色调：深灰磨砂机身，占比70%\n  - 辅助色：黑色织物背景，占比25%\n  - 点缀色：金色充电触点，占比5%\n【营销信息融合】\n  - 无额外促销标签，通过画面本身的干净高级传递产品价值\n【技术参数建议】\n  - 布光参考：多灯位均匀柔光布光，消除硬阴影，凸显哑光质感\n  - 质感补充：轻微磨砂颗粒肌理、织物细微纤维，增强真实产品摄影感\n  - 技术禁止项：不出现焦距、光圈等无效参数\n【风格标签】极简科技、磨砂质感、对称秩序、专业可信\n【画面收尾精简约束】画面无多余配件、装饰、杂物，所有元素服务突出产品品质感，不抢夺耳机主体视觉焦点。"
        },
        {
            "category": "首饰配饰-金色项链",
            "natural": "一条金色项链温柔地铺展在浅米色的丝绸布料上，链条呈自然的S形弯曲，像一条正在呼吸的河流，整体氛围柔和奢华，满是送礼的仪式感。吊坠是一颗椭圆形的主石，被精致的爪镶托举着，在侧光照射下折射出细碎的光芒——不是夸张的闪耀，而是需要仔细观察才能捕捉到的内敛光泽，高级又不张扬。光从右上方斜射过来，在每一节链条的转折处都留下小小的光点，让金属的质感变得丰富立体。丝绸布料的自然褶皱为画面增加了柔软层次，布料边缘被光线晕出淡淡的暖金色，与项链的色泽形成微妙呼应。吊坠的背面也有精心设计的镂空花纹，在画面里只露出一角，却足以让人感受到“连背面都一丝不苟”的用心。构图采用大面积留白，项链只占据画面中央偏左的位置。留白不是空，而是为了托举项链的精致；右侧的空白区域像等待被填满的礼物盒，暗合送礼的情感场景。整张画面柔和、安静、高级，传递的不只是一条项链，更是一份值得被郑重送出的心意。主色调金色链条与宝石占70%，浅米丝绸背景辅助占25%，暖金光影点缀占5%，低饱和暖调，温柔有质感。",
            "structured": "【类别】电商场景\n【产品类型】首饰配饰（金色项链）\n【目标平台】抖音/小红书礼赠赛道\n【全局正向约束】\n  - 主体基础：链条比例均匀，吊坠形制规整，爪镶细节清晰\n  - 质感基础：金属光泽细腻真实，宝石折射自然，丝绸柔滑质感\n  - 画面逻辑：45°斜拍微距感，符合首饰特写审美，聚焦精致细节\n【画面构图】\n  - 视觉引导：S形链条引导视线穿过画面，吊坠成为最终视觉落点\n  - 主体位置：水平42%偏左，垂直48%居中，项链占据70%视觉权重\n  - 画面比例：3:2（适配种草笔记与商品详情）\n  - 画面精简约束：仅项链、丝绸布料，不新增首饰盒、多余饰品、装饰杂物\n【景别与三维拍摄视角】\n  - 距离维度：微距特写，突出链条与吊坠的精致细节\n  - 水平视角维度：四分之三斜侧，展现链条曲线与吊坠侧面厚度\n  - 垂直俯仰维度：45°斜拍，兼顾链条延展与吊坠立体度\n  - 画面景深：吊坠与前景链条清晰，背景丝绸柔和虚化，突出主体\n【产品核心卖点】\n  - 核心吸引力：主石折射光泽+链条S形曲线+背面镂空细节\n  - 购买触发点：精致高级感，适配送礼场景，细节见用心\n【场景与道具搭配】\n  - 场景氛围：柔和奢华ins风，浅米色丝绸基底，温润柔软\n  - 主要道具：浅米色丝绸布料，带自然褶皱\n  - 搭配逻辑：丝绸的柔软衬托金属与宝石的硬朗，材质对比突出产品\n【产品质感与光影】\n  - 外观形态：金色S形链条，椭圆形爪镶吊坠，背面镂空花纹\n  - 质感表现：金属细腻光泽，宝石细碎折射，丝绸柔滑褶皱\n  - 光影设计：右上斜射侧柔光，塑造金属立体转折，呈现内敛光泽\n【色彩配比】\n  - 主色调：金色链条+主石，占比70%\n  - 辅助色：浅米色丝绸背景，占比25%\n  - 点缀色：暖金色光影高光，占比5%\n【营销信息融合】\n  - 通过画面留白与氛围感传递礼赠情感价值，无生硬促销信息\n【技术参数建议】\n  - 布光参考：单侧柔光+反光板补暗部，塑造金属细腻光泽\n  - 质感补充：轻微丝绸纤维肌理、金属细微划痕，增强真实首饰摄影感\n  - 技术禁止项：不出现焦距、光圈等无效参数\n【风格标签】柔和奢华、送礼美学、细节质感、高级内敛\n【画面收尾精简约束】画面无多余首饰、礼盒、装饰杂物，所有元素服务突出产品精致感与送礼氛围，不抢夺项链主体视觉焦点。"
        }
    ]
}

ECOMMERCE_EN = {
    "name": "E-Commerce Product & Scene Photography Master (Visual Narrative Edition)",
    "description": "Professional e-commerce visual director crafting conversion-driven scene descriptions. Semantic weight priority: product type & selling point → 3D perspective → scene atmosphere → color ratio → props → lighting & texture. Built-in 3D perspective, 70%/25%/5% color ratio, dual texture constraints. Covers beauty, 3C, food, jewelry, home goods.",
    "input_template": "Step-by-step expansion for e-commerce product scene: 1) Identify product type and target platform; 2) Determine core selling point; 3) Design scene atmosphere (minimal/lifestyle/ins/tech/luxury); 4) Plan props—complement product without stealing focus; 5) Design lighting—key light highlights product, fill light softens shadows; 6) Choose perspective and generate {mode} description. Natural mode uses 2-3 paragraphs: scene & atmosphere → details & texture → composition & guidance.\n\nCore principles:\n- Product is the absolute star—everything serves to highlight it\n- Texture is product language—metal's coolness, glass's clarity, fabric's softness must be \"seen\"\n- Light is product makeup—good light makes products look premium and desirable\n- Marketing information should blend naturally, not disrupt the visual aesthetic",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3). First: overall scene and atmosphere. Second: product details and texture. Third: composition and visual guidance. Vivid, compelling language.",
        "structured": "[Category] E-Commerce Scene\n[Product Type] Beauty/3C/Food/Jewelry/Apparel/Home, etc.\n[Target Platform] Xiaohongshu/Douyin/Tmall/JD.com, etc.\n[Core Selling Point]\n  - Most attractive detail: texture/efficacy/design/color, etc.\n  - Purchase trigger: what makes people want it\n[Scene & Atmosphere]\n  - Overall style: Minimal/lifestyle/ins/tech/luxury, etc.\n  - Environment: background, spatial feel, seasonal sense\n  - Light atmosphere: main direction, color temperature, soft/hard\n[Props & Styling]\n  - Main props: material, color, placement (not overshadowing product)\n  - Styling logic: how props complement product character\n[Product Details & Texture]\n  - Appearance: form, color, sheen\n  - Texture: brushed metal/glass transparency/creamy/fabric softness, etc.\n  - Close-up detail: the detail worth zooming in on\n[Composition & Perspective]\n  - Shooting angle: eye-level/45° tilt/top-down/macro\n  - Visual guidance: how the eye moves through the frame\n  - Composition: centered/rule of thirds/diagonal\n[Marketing Integration]\n  - Promo/brand info: how it naturally appears\n[Style Tags] 3-5 keywords summarizing visual character"
    },
    "task_requirements": [
        "Use vivid compelling language—avoid mechanical parameters",
        "User-specified elements (product type, style, materials, color) are hard constraints; supplement only unspecified dimensions",
        "Include: core selling point, scene & atmosphere, props & styling, product details & texture, composition & perspective",
        "Texture description should be specific and vivid—make product \"touchable\"",
        "Light description explains how it highlights product and creates mood",
        "Marketing information blends naturally into the scene",
        "Perspective serves the selling point (macro/top-down/45°)",
        "Avoid over-sharpening and over-saturation—pursue authentic premium quality",
        "Follow 70%/25%/5% color ratio; 3D perspective follows user input priority",
        "Natural mode uses 2-3 paragraphs, 300-600 words"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "language": "en"
    },
    "examples": [
        {
            "natural": "A bottle of serum sits on a light grey marble slab, its thick transparent glass revealing a pale pink liquid that flows gently inside. The gold cap carries a fine brushed texture, catching the side light with a warm metallic glow. The label is minimal white—just the brand and product name in slender, elegant type, as if written with the finest pen.\n\nLight falls from the upper left, creating a soft curved highlight across the bottle that amplifies the glass's clarity to its fullest. Inside the liquid, faint light trails drift, as if recently stirred. The dropper is placed front and center, its matte rubber texture contrasting with the glass's smoothness—this is the part the user touches first, and it's shown with care.\n\nA dried eucalyptus leaf sits in the lower-left foreground, its grey-green tones adding a natural breath to the scene, always kept out of focus to let the product reign. The composition is restrained, yet every detail is crisp—this is the kind of premium trust that high-end beauty brands want to convey.",
            "structured": "[Category] E-Commerce Scene\n[Product Type] Beauty/Skincare\n[Target Platform] Xiaohongshu\n[Core Selling Point]\n  - Most attractive detail: Gold brushed cap + transparent glass bottle\n  - Purchase trigger: Premium feel, visible essence flow\n[Scene & Atmosphere]\n  - Overall style: Minimal premium, ins style\n  - Environment: Light grey marble slab, clean and translucent\n  - Light atmosphere: Upper-left side light, soft highlights\n[Props & Styling]\n  - Main props: Marble surface, out-of-focus eucalyptus leaf\n  - Styling logic: Leaf adds breathing room without competing\n[Product Details & Texture]\n  - Appearance: Thick transparent glass, pale pink liquid, brushed gold cap\n  - Texture: Glass clarity, fine brushed metal, matte rubber\n  - Close-up detail: Light arc across bottle, liquid flow trails, dropper design\n[Composition & Perspective]\n  - Shooting angle: 45° tilt, slightly below eye-level\n  - Visual guidance: Light highlight draws eye to bottle center\n  - Composition: Slightly left-center, product occupies 2/3\n[Marketing Integration]\n  - No promo tag—brand value conveyed through the image itself\n[Style Tags] Premium minimal, clarity, ins beauty"
        },
        {
            "natural": "A pair of wireless headphones rests on a matte black fabric surface—two deep grey earphones side by side, their charging case half-open beside them, as if freshly removed. The matte finish of the headphones softens the light, with only a low-contrast arc flowing along the stem, emphasizing the smooth ergonomic curve.\n\nThe two earphones sit like companions. The charging case lid is open at 45 degrees, revealing gold charging contacts inside—a carefully placed detail that suggests \"tech\" and \"quality.\" The touch-control area on the earphone stems has an ultra-fine concentric texture, barely visible unless you look closely. Once noticed, it conveys one thing: this product was made with care.\n\nNo other props—no cable, no packaging, nothing extra. The product is enough. Light comes from above and both sides simultaneously, casting almost no shadows, evenly illuminating every curve. This lighting makes the dark grey matte finish look clean, premium, utterly believable. The top-down perspective creates near-perfect symmetry—on a product detail page, this kind of image makes users pause and look longer.",
            "structured": "[Category] E-Commerce Scene\n[Product Type] 3C Electronics\n[Target Platform] Tmall/JD.com\n[Core Selling Point]\n  - Most attractive detail: Matte finish + ergonomic curve\n  - Purchase trigger: Clean premium tech feel\n[Scene & Atmosphere]\n  - Overall style: Minimal tech\n  - Environment: Black fabric surface, no stray reflections\n  - Light atmosphere: Multi-angle even soft light, almost shadowless\n[Props & Styling]\n  - Main props: Black fabric background\n  - Styling logic: No props—product is the star\n[Product Details & Texture]\n  - Appearance: Dark grey matte shell, curved stems\n  - Texture: Matte low-reflection, gold contact points\n  - Close-up detail: Concentric texture on touch-control area\n[Composition & Perspective]\n  - Shooting angle: Top-down\n  - Visual guidance: Symmetrical, case and earphones in dialogue\n  - Composition: Symmetrical, product centered\n[Marketing Integration]\n  - No promo—clean premium presentation conveys value\n[Style Tags] Minimal tech, matte texture, symmetrical order"
        },
        {
            "natural": "A gold necklace lies gently on light beige silk fabric, its chain curving in a natural S-shape like a breathing river. The pendant—an oval diamond held by a delicate claw setting—refracts soft shimmers under side light. Not ostentatious sparkle, but subtle glints that invite closer looking.\n\nLight comes from the upper right at 45 degrees, leaving a small highlight at each turn of the chain, making the metal feel rich and three-dimensional. The silk's folds add soft layering, their edges catching a warm gold tone that echoes the necklace's color. The pendant back reveals delicate openwork—only a corner is visible, but enough to signal that every side was crafted with care.\n\nThe composition uses generous white space, the necklace placed slightly left of center. The emptiness isn't absence—it suggests this is a gift meant to be given, the blank space like a gift box waiting to be filled. The image is soft, quiet, premium. Its message isn't \"this is a necklace\"—it's \"this is a sentiment worth giving.\"",
            "structured": "[Category] E-Commerce Scene\n[Product Type] Jewelry\n[Target Platform] Douyin/Xiaohongshu\n[Core Selling Point]\n  - Most attractive detail: Diamond refraction + S-curve chain\n  - Purchase trigger: Gifting sentiment, delicate craftsmanship\n[Scene & Atmosphere]\n  - Overall style: Soft luxury, ins aesthetic\n  - Environment: Light beige silk fabric, warm and soft\n  - Light atmosphere: 45° upper-right side light, gentle reflections\n[Props & Styling]\n  - Main props: Light beige silk fabric\n  - Styling logic: Silk softness contrasts with diamond hardness\n[Product Details & Texture]\n  - Appearance: Gold S-curve chain, oval diamond in claw setting\n  - Texture: Chain sheen, diamond refraction, openwork back\n  - Close-up detail: Highlights on each chain link, claw setting details\n[Composition & Perspective]\n  - Shooting angle: 45° tilt, macro feel\n  - Visual guidance: S-curve guides the eye across the frame\n  - Composition: Left-center, generous white space\n[Marketing Integration]\n  - Emotional value conveyed through gift-like presentation\n[Style Tags] Soft luxury, gift aesthetic, detailed craft"
        }
    ]
}

FOOD_PHOTOGRAPHY_ZH = {
    "name": "美食摄影大师",
    "description": "专业美食摄影指导，为全品类美食打造高可控食欲感视觉描述。语义权重优先级：美食类型焦点→三维视角构图→场景氛围→色彩配比→食物细节质感→光影食欲设计。内置三维度视角、70%/25%/5%色彩配比、双重质感约束与画面精简约束，以「不完美的真实感」为核心，通过轻微焦痕、酱汁流淌、自然热气强化手工可信度。覆盖甜点、中式、西餐、饮品、小吃等品类赛道。",
    "input_template": "逐步思考扩写美食摄影描述，严格遵循语义权重顺序：美食类型与视觉焦点→三维拍摄视角与构图布局→场景氛围与基调→色彩配比方案→食物细节与真实质感→光影食欲设计；完整执行 6 步标准化扩写逻辑：\n1）分析美食类型（甜点/中式/西式/饮品/小吃等）与风格调性，明确核心视觉焦点与情感触发点；\n2）确定画幅格式（竖版9:16或横版16:9）；规划三维度拍摄视角：视距远近、水平角度、垂直俯仰，优先沿用用户指定维度，未指定项随机合规组合；\n3）设计构图与场景基调：明确俯拍/侧拍/45°斜拍的核心作用，让食物在画面中有呼吸感，所有场景元素服务衬托食物；\n4）构思色彩方案：主色70%、辅助色25%、点缀色5%，食物主体色为主色调，背景餐具为辅助色，细节亮点为点缀色，标注饱和度层级；\n5）刻画食物细节与真实质感：描述食物形态、色泽、肌理与口感联想，重点保留手工制作的真实痕迹（轻微焦痕、酱汁流淌、气泡、切面不均）；\n6）设计光影体系：明确光源方向、色温、软硬，用光放大食物质感，规划背景与道具搭配，生成对应模式描述。自然模式2-3段，顺序：构图场景 → 食物细节质感 → 光线色彩与食欲感受。\n\n核心原则：\n- 食物是绝对主角：所有视觉元素都服务于让食物看起来更好吃\n- 真实感源于不完美：轻微焦痕、酱汁流淌、气泡、不均切面都是手工感的证明\n- 光线是食欲催化剂：温暖侧光强化层次，光影过渡自然，让质感更立体\n- 色彩严格配比：食物主体色占主导，背景道具色辅助，点缀色制造焦点\n- 三维视角合规：用户指定维度沿用，未指定维度按美食摄影审美合规随机\n- 画面精简约束：仅保留核心食物与必要衬托道具，不自动生成多余摆件\n- 技术参数仅用于提升可控性，自然模式剔除所有数字技术参数",
    "output_format_suffix": {
        "natural": "自然段落（2-3段），首段确立构图格局、场景环境与整体氛围，次段展开食物形态、肌理细节与真实手工痕迹，末段补充光影效果、色彩感受与食欲联想。语言生动有食欲感，全程无焦距、光圈、分辨率类数字技术参数，强化食物主体地位、真实质感与画面精简约束，保证画面干净聚焦、卖点突出、感染力强。",
        "structured": "【类别】美食摄影\n【美食类型】甜点烘焙/中式料理/西餐料理/饮品咖啡/小吃零食等\n【全局正向约束】\n  - 主体基础：食物形态准确，比例正常，无变形失真，质感真实可感\n  - 质感基础：食物肌理表现真实，油脂/奶油/酥脆质感符合物理特性\n  - 画面逻辑：三维视角符合美食拍摄审美，构图聚焦食物最诱人的一面\n【画面构图】\n  - 视觉引导：视线流动逻辑，依托食物形态、光线高光、餐具线条三重引导，焦点始终落在食物核心诱人处\n  - 主体位置：食物核心区域水平与垂直占比，食物主体占据 70% 视觉权重，背景道具共占 30%\n  - 画面比例：宽高比（16:9 横版 / 9:16 竖版 / 1:1 方图）\n  - 画面精简约束：仅保留核心食物与必要餐具配料，不额外生成多余摆件、装饰、杂物\n【景别与三维拍摄视角】\n  - 距离维度（景别对应）：微距细节特写 / 食物标准特写 / 带场景中景 / 全景氛围图，对应卖点展示层级\n  - 水平视角维度：水平拍摄角度（正面/四分之三斜侧/正侧面），标注食物展现效果与卖点呈现\n  - 垂直俯仰维度：垂直拍摄角度（垂直俯拍/45°斜拍/平视/小仰拍），对应心理感受与卖点展示（俯拍展全貌/斜拍显立体/平视显层次）\n  - 画面景深：食物清晰锐利、背景道具适度虚化 / 前后景都清晰，标注虚实层次对应的主次关系\n【视觉焦点】\n  - 最诱人的部分：脆皮/流心/油亮/拉花/热气等核心视觉卖点\n  - 情感触发点：温暖/治愈/满足/新鲜等情绪价值\n【食物细节与质感】\n  - 外观形态：颜色、造型、层次、整体轮廓\n  - 质感表现：酥脆/绵密/油亮/焦香/Q弹等口感对应的视觉肌理\n  - 真实痕迹：轻微焦痕、酱汁流淌、气泡、切面不均、食材颗粒等手工感细节\n【光影与氛围】\n  - 光源方向与色温：自然光/人工光的入射方向，冷暖调性\n  - 高光与阴影：光斑位置、阴影柔和度，对质感的塑造作用\n  - 整体氛围：温暖/清新/暗调/治愈/家常等情绪感受\n【色彩配比】\n  - 主色调：食物主体色，占比70%，奠定食欲基调\n  - 辅助色：背景与餐具色，占比25%，衬托食物层次\n  - 点缀色：细节亮点色，占比5%，制造视觉焦点\n【背景与道具】\n  - 餐具容器：材质、颜色、风格\n  - 环境背景：桌布、桌面、场景元素\n  - 搭配逻辑：道具如何衬托食物，为何不抢主角\n【技术参数建议】（仅 structured 模式使用）\n  - 布光参考：对应布光方案的视觉效果说明，无数值参数\n  - 质感补充：可按需添加柔光质感、颗粒胶片感、热气朦胧等效果术语，搭配说明\n  - 技术禁止项：不出现焦距、光圈、分辨率、渲染参数等无效数值参数\n【风格标签】3-5个关键词概括视觉气质与食欲方向\n【画面收尾精简约束】画面无额外无关道具、多余装饰、杂乱背景填充，所有元素仅服务突出食物诱人特质，不抢夺食物主体视觉焦点。"
    },
    "task_requirements": [
        "natural模式使用有画面感、带食欲感染力的描述语言，严禁出现数字技术参数",
        "食物始终为绝对主角，餐具道具仅作衬托，层级分明不抢戏",
        "真实手工痕迹为核心差异化：轻微焦痕、酱汁流淌、气泡、不均切面，拒绝完美3D感",
        "光影采用具象化分层描写，明确方向、色温、软硬与质感塑造作用",
        "双重质感约束叠加，同品类下材质、光影、色调统一，杜绝质感虚假",
        "严格执行70%/25%/5%色彩配比，食物主体色占主导，符合食欲心理学",
        "三维度视角遵循用户输入优先规则，未指定维度按美食拍摄审美合规随机组合",
        "餐具配料克制精准，仅保留服务叙事的衬托元素，不自动生成多余摆件",
        "natural模式输出2-3段，300-600字；structured模式完整分层输出",
        "严格执行画面精简约束，仅保留核心食物与必要衬托道具"
    ],
    "constraints": {
        "max_length": 1000,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "分辨率", "DPI", "色彩模式", "焦距", "光圈", "帧率", "码率", "采样率", "编码器", "HDR", "杜比", "字幕", "水印", "logo", "完美对称", "零瑕疵", "塑料感", "崩坏", "扭曲"],
        "grounding_support": True,
        "language": "zh",
        "natural_mode_forbidden_params": ["mm", "f/", "DPI", "分辨率", "渲染参数", "色彩模式"],
        "structured_param_allowance": "仅允许在【技术参数建议】字段使用布光参考、质感补充定性描述与效果释义，禁止使用焦距、光圈、分辨率等数值参数，其余字段禁止所有技术数字参数"
    },
    "positive_constraints": "食物为绝对主角，质感真实细腻，光影柔和自然，色彩激发食欲，画面干净克制，手工痕迹自然（焦痕、酱汁流淌、气泡、切面不均），热气油脂光泽可信，生活温度与食欲感染力并存",
    "negative_prompts": "食物变形失真，质感塑料虚假，光影过曝刺眼，色彩脏污发灰，摆盘过于完美像3D渲染，道具喧宾夺主，构图失衡杂乱，元素堆砌冗余，透视比例错误，低分辨率模糊，多余杂物乱入，装饰摆件堆砌，字幕水印logo，热气虚假僵硬，过度锐化生硬，边缘锯齿毛躁，油脂光泽不自然，背景杂乱抢戏",
    "examples": [
        {
            "category": "甜点烘焙-草莓蛋糕",
            "natural": "一块刚出炉的草莓蛋糕斜放在粗陶盘上，切面展示出三层细腻蛋糕体与两层草莓奶油馅的交替层次，温柔又有治愈感。蛋糕体的气孔均匀蓬松，边缘带着一圈浅浅的焦褐色——那是烘焙时与模具接触的部分，藏着刚刚好的焦香。最上层的奶油并非完美平滑，而是带着微微起伏与边缘自然流淌的痕迹，一看就是人手涂抹的温度，而非机器刮平的冰冷。三颗半颗的草莓斜斜嵌在奶油表面，切面露出鲜红的果肉与细小的白色纤维，其中一颗边缘微微下陷，像是被轻轻按压过的鲜活痕迹。薄荷叶在草莓间随意散落，边缘有些卷曲，仿佛刚从枝头摘下不久。光线从右上方斜射过来，在奶油表面形成一道柔和的弧形高光，照亮了草莓果肉上的细小纤维，也把蛋糕的松软质感无限放大。背景是浅米色的亚麻桌布，纹理清晰可辨。桌角的阴影自然延伸，与盘子边缘形成安静的夹角。整个画面温柔克制、充满生活感，没有用力过猛的修饰，只有一块蛋糕在午后光线里安静等待被享用。主色调奶油白+草莓红占70%，薄荷绿+蛋糕金黄辅助占25%，粗陶盘灰点缀占5%，低饱和暖调，治愈感十足。",
            "structured": "【类别】美食摄影\n【美食类型】甜点烘焙（草莓奶油蛋糕）\n【全局正向约束】\n  - 主体基础：蛋糕层次分明，形态规整，切面比例自然\n  - 质感基础：奶油细腻绵密，蛋糕体蓬松有气孔，草莓多汁鲜活\n  - 画面逻辑：45°斜拍符合甜点拍摄审美，焦点落在切面层次上\n【画面构图】\n  - 视觉引导：切面层次引导视线纵向深入，奶油高光锚定视觉中心\n  - 主体位置：水平48%居中，垂直46%居中，蛋糕主体占据70%视觉面积\n  - 画面比例：3:2（适配美食种草与详情页）\n  - 画面精简约束：仅蛋糕、粗陶盘、薄荷叶，不新增多余甜点、餐具、装饰杂物\n【景别与三维拍摄视角】\n  - 距离维度：食物标准特写，兼顾整体形态与切面细节\n  - 水平视角维度：四分之三斜侧，同时展现正面切面与侧面厚度\n  - 垂直俯仰维度：45°斜拍，兼顾顶层装饰与内部层次\n  - 画面景深：蛋糕主体清晰锐利，背景桌布适度虚化，主次分明\n【视觉焦点】\n  - 最诱人的部分：蛋糕切面层次 + 奶油自然流淌痕迹 + 草莓果肉纤维\n  - 情感触发点：手工感、温暖治愈、下午茶松弛感\n【食物细节与质感】\n  - 外观形态：三层蛋糕体+两层奶油馅，草莓半颗斜插，薄荷叶点缀\n  - 质感表现：蛋糕体蓬松有气孔，奶油细腻微流淌，草莓多汁有纤维感\n  - 真实痕迹：蛋糕边缘轻微焦褐，奶油表面起伏不平，草莓边缘微陷，薄荷叶微卷\n【光影与氛围】\n  - 光源方向与色温：右上方斜射自然光，暖调柔和\n  - 高光与阴影：奶油弧形高光，桌角柔和阴影，强化松软质感\n  - 整体氛围：温柔治愈、松弛下午茶、家常手工感\n【色彩配比】\n  - 主色调：奶油白+草莓红，占比70%\n  - 辅助色：薄荷绿+蛋糕金黄，占比25%\n  - 点缀色：粗陶盘灰褐色，占比5%\n【背景与道具】\n  - 餐具容器：粗陶圆盘，质朴肌理\n  - 环境背景：浅米色亚麻桌布，纹理清晰\n  - 搭配逻辑：质朴餐具衬托蛋糕的柔软精致，虚化处理不抢主角\n【技术参数建议】\n  - 布光参考：单侧柔光窗光，塑造柔和高光与自然阴影\n  - 质感补充：轻微亚麻织物肌理、奶油细微颗粒感，增强真实摄影感\n  - 技术禁止项：不出现焦距、光圈等无效参数\n【风格标签】温暖治愈、手工感、自然光下午茶、松软绵密\n【画面收尾精简约束】画面无多余甜点、餐具、装饰杂物，所有元素服务突出蛋糕松软治愈的特质，不抢夺食物主体视觉焦点。"
        },
        {
            "category": "中式料理-红烧肉",
            "natural": "一碗红烧肉摆放在深色木桌上，刚刚端上桌的热气在镜头前蒙起一层薄薄的白雾，模糊了背景却让碗里的肉愈发鲜亮诱人，满是家常的温暖。大块的五花肉叠放在碗中，每一块边缘都带着恰到好处的焦糖色，微微发亮——那是冰糖高温融化后形成的自然光泽。其中一块肉的表皮有一道不规则的龟裂纹，像是炖煮过程中自然裂开的，不是刻意雕琢，却让人相信这是家常小火慢炖的诚意。酱汁在肉块之间缓缓流淌，颜色是深沉的红棕色，带着油亮的光泽，在碗底汇聚成小小的一洼。几颗八角和一瓣桂皮静静躺在酱汁里，是烧肉时留下的香料痕迹，还没来得及挑走。葱花的绿色散落在肉块之间——有的已经微微卷曲，有的沾了一点酱汁颜色略深，像是一出锅就撒上去的，还带着新鲜切割的湿润感。光线来自左前方，透过窗户的柔光在肉块表面形成一系列高光点，让脂肪部分显得晶莹透亮，瘦肉部分的纤维结构清晰可见。深色木桌吸收了大部分光线，让整碗肉的色彩更加突出。热气还在缓缓升腾，模糊了画面的一小部分，却让整张照片多了真实的温度。主色调深红棕酱汁占70%，暗金肉皮+翠绿葱花辅助占25%，八角桂皮深褐点缀占5%，中饱和暖调，香浓下饭。",
            "structured": "【类别】美食摄影\n【美食类型】中式料理（红烧肉）\n【全局正向约束】\n  - 主体基础：肉块形态饱满，比例正常，肥瘦分层自然\n  - 质感基础：酱汁油亮真实，肉皮焦糖化自然，瘦肉纤维清晰\n  - 画面逻辑：平视略俯符合家常拍摄视角，焦点落在肉块油亮光泽上\n【画面构图】\n  - 视觉引导：热气引导视线向上，肉块高光锚定视觉中心，酱汁延伸强化油润感\n  - 主体位置：水平50%居中，垂直48%居中，红烧肉主体占据70%视觉面积\n  - 画面比例：3:2（适配家常菜分享与美食教程）\n  - 画面精简约束：仅红烧肉、碗、香料葱花，不新增多余菜品、餐具、装饰杂物\n【景别与三维拍摄视角】\n  - 距离维度：食物特写，兼顾碗中整体与肉块细节\n  - 水平视角维度：正面，完整呈现碗中肉块堆叠形态\n  - 垂直俯仰维度：平视略俯，贴近日常夹菜的自然视角\n  - 画面景深：肉块主体清晰，背景木桌适度虚化，突出主体\n【视觉焦点】\n  - 最诱人的部分：酱汁油亮光泽 + 肉块焦糖色表皮 + 升腾热气\n  - 情感触发点：家常感、香浓下饭、烟火气\n【食物细节与质感】\n  - 外观形态：大块五花肉叠放，深红棕酱汁包裹，葱花点缀\n  - 质感表现：酱汁油亮挂壁，肉皮焦糖化软糯，瘦肉纤维紧实\n  - 真实痕迹：表皮龟裂纹，酱汁流淌汇聚，香料残留，葱花沾酱变色\n【光影与氛围】\n  - 光源方向与色温：左前方自然窗光，暖调温润\n  - 高光与阴影：脂肪部分高光点，碗底暗部沉淀，强化油润质感\n  - 整体氛围：家常温暖、烟火气十足、香浓下饭\n【色彩配比】\n  - 主色调：深红棕酱汁，占比70%\n  - 辅助色：暗金肉皮+翠绿葱花，占比25%\n  - 点缀色：八角桂皮深褐色，占比5%\n【背景与道具】\n  - 餐具容器：深色陶瓷碗，沉稳质朴\n  - 环境背景：深色实木桌面，纹理深沉\n  - 搭配逻辑：深色背景衬托肉的鲜亮油润，突出食物主体\n【技术参数建议】\n  - 布光参考：前侧柔光窗光，塑造油亮高光与柔和暗部\n  - 质感补充：轻微热气朦胧感、木材肌理，增强家常真实感\n  - 技术禁止项：不出现焦距、光圈等无效参数\n【风格标签】家常硬菜、暖光诱人、烟火气十足、油润香浓\n【画面收尾精简约束】画面无多余菜品、餐具、装饰杂物，所有元素服务突出红烧肉香浓下饭的特质，不抢夺食物主体视觉焦点。"
        },
        {
            "category": "饮品咖啡-拿铁",
            "natural": "一杯拿铁咖啡放在浅木色桌面上，杯口边缘的奶泡细腻绵密，表面是一幅精致的叶子拉花，纹路清晰，边缘延伸出细细的弧线，带着奶泡流动的自然痕迹。拉花并非完美对称，叶尖处略微收窄，有一侧稍微偏离了杯子中心线——这种恰到好处的「不完美」，恰恰是手工拉花的动人魅力。奶泡表面有几处极细小的气泡，像是咖啡师倾倒牛奶时无意间留下的呼吸印记。咖啡液的颜色透过杯壁与奶泡的交界处呈现出深浅不一的渐变，最底部的浓缩咖啡在晃动中留下一道细细的棕色挂壁痕迹。杯沿内侧有一圈浅浅的奶渍，是牛奶在被喝下前留下的小小印记。光线从左侧斜照过来，在奶泡表面形成一道柔和的弧光，让拉花的纹路变得更加立体。杯子的投影在桌面上延伸，边缘微微模糊——那是自然光下才有的柔和过渡。背景中，几颗咖啡豆散落在木质桌面上，其中一颗表面有道细微的裂纹，豆子自身的纹理清晰可见。整个画面松弛安静，让人想端起这杯咖啡，在某个无所事事的下午慢慢啜饮。主色调深棕咖啡+白奶泡占70%，浅木色桌面辅助占25%，咖啡豆深褐点缀占5%，低饱和暖调，松弛治愈。",
            "structured": "【类别】美食摄影\n【美食类型】饮品咖啡（拿铁）\n【全局正向约束】\n  - 主体基础：杯型比例正常，奶泡厚度均匀，拉花形态自然\n  - 质感基础：奶泡绵密细腻，咖啡液光泽自然，杯子陶瓷质感真实\n  - 画面逻辑：平视略俯符合饮品拍摄审美，焦点落在奶泡拉花上\n【画面构图】\n  - 视觉引导：拉花弧线引导视线流动，奶泡高光锚定视觉中心\n  - 主体位置：水平45%偏左，垂直48%居中，咖啡杯占据70%视觉权重\n  - 画面比例：3:2（适配咖啡种草与生活方式分享）\n  - 画面精简约束：仅咖啡杯、少量咖啡豆，不新增多余甜点、餐具、装饰杂物\n【景别与三维拍摄视角】\n  - 距离维度：饮品特写，兼顾杯型整体与奶泡细节\n  - 水平视角维度：正面略偏，展现拉花与杯壁层次\n  - 垂直俯仰维度：平视略俯，贴近日常端杯的自然视角\n  - 画面景深：奶泡区域清晰锐利，背景桌面适度虚化\n【视觉焦点】\n  - 最诱人的部分：手工拉花纹理 + 奶泡绵密质感 + 挂壁咖啡液\n  - 情感触发点：松弛、慢生活、治愈\n【食物细节与质感】\n  - 外观形态：绵密奶泡覆盖，叶子拉花，深棕咖啡液分层\n  - 质感表现：奶泡柔软蓬松，咖啡液顺滑有光泽，陶瓷杯温润\n  - 真实痕迹：拉花略偏中心线，奶泡表面小气泡，杯沿奶渍，挂壁痕迹\n【光影与氛围】\n  - 光源方向与色温：左侧斜照自然光，暖调柔和\n  - 高光与阴影：奶泡弧形高光，杯影边缘模糊，强化柔软质感\n  - 整体氛围：松弛安静、慢生活、日常治愈\n【色彩配比】\n  - 主色调：深棕咖啡+奶白奶泡，占比70%\n  - 辅助色：浅木色桌面，占比25%\n  - 点缀色：咖啡豆深褐色，占比5%\n【背景与道具】\n  - 餐具容器：白色陶瓷杯，简约温润\n  - 环境背景：浅木色桌面，纹理自然\n  - 搭配逻辑：简约背景衬托咖啡质感，咖啡豆点缀强化品类属性\n【技术参数建议】\n  - 布光参考：单侧柔光，塑造奶泡柔和高光与自然杯影\n  - 质感补充：轻微木材肌理、奶泡细微气孔，增强真实摄影感\n  - 技术禁止项：不出现焦距、光圈等无效参数\n【风格标签】松弛治愈、慢生活、手工拉花、日常质感\n【画面收尾精简约束】画面无多余甜点、餐具、装饰杂物，所有元素服务突出咖啡松弛治愈的特质，不抢夺饮品主体视觉焦点。"
        },
        {
            "category": "西餐料理-炭烤羊排",
            "natural": "一盘刚煎好的羊排放置在深色石板上，表面带着明显的网格状炭烤痕迹——那是炙烤时铁架留下的印记，深浅不一地交错排列，让肉的表皮满是焦香的气息。其中一块羊排的边缘有一小处微微焦黑，像是火焰那一瞬间格外热情，不是瑕疵，而是炭烤食物的荣誉勋章。肉质表面泛着油亮的光泽，几滴油脂沿着肉的纹理向下流动，在石板上留下一道细细的油痕。切口处露出内部的粉红色，肉质紧密柔嫩，边缘的脂肪部分已经烤至半透明，微微卷曲。一小撮海盐片和几粒黑胡椒碎散落在肉表面，分布并不均匀——有些区域密集，有些区域稀少，像是随手撒上去的随性。光线从右后方逆光射入，在肉的边缘形成一圈温暖的金色轮廓，把肉块的立体感拉到极致。石板表面粗糙的质感在光线下清晰可见，与肉的光滑形成鲜明对比。背景是一小株迷迭香和几瓣切开的大蒜，没有摆成精心设计的造型，只是随意散落在板子上，像是烹制过程中留下的自然痕迹。整张照片带着粗犷的原生力量感，让吃肉这件事变得无比坦诚过瘾。主色调深褐焦色+粉红肉色占70%，金色光晕+深灰石板辅助占25%，迷迭香绿点缀占5%，中饱和暖调，肉欲十足。",
            "structured": "【类别】美食摄影\n【美食类型】西餐料理（炭烤羊排）\n【全局正向约束】\n  - 主体基础：羊排形态自然，肥瘦比例正常，切面层次清晰\n  - 质感基础：表皮焦香酥脆，内里柔嫩多汁，油脂光泽真实\n  - 画面逻辑：45°斜拍符合西餐拍摄审美，焦点落在切面嫩度与炭烤痕迹上\n【画面构图】\n  - 视觉引导：油脂流动引导视线，肉边金色轮廓强化立体感，对角线布局延伸画面\n  - 主体位置：水平52%偏右，垂直46%居中，羊排主体占据70%视觉面积\n  - 画面比例：3:2（适配西餐分享与餐厅菜单）\n  - 画面精简约束：仅羊排、石板、迷迭香大蒜，不新增多余配菜、餐具、装饰杂物\n【景别与三维拍摄视角】\n  - 距离维度：食物特写，兼顾羊排整体与切面细节\n  - 水平视角维度：四分之三斜侧，同时展现表皮炭烤纹与切面嫩度\n  - 垂直俯仰维度：45°斜拍，兼顾表面纹理与内部层次\n  - 画面景深：羊排主体清晰，背景配料适度虚化\n【视觉焦点】\n  - 最诱人的部分：网格炭烤痕迹 + 粉红嫩切面 + 油脂油亮光泽\n  - 情感触发点：肉欲满足、原始粗犷、炭烤香气\n【食物细节与质感】\n  - 外观形态：带骨羊排，表皮炭烤网格纹，切面粉红嫩度\n  - 质感表现：表皮焦香脆韧，内里柔嫩多汁，脂肪半透明卷曲\n  - 真实痕迹：网格纹深浅不一，边缘微焦黑，油脂流淌，海盐分布不均\n【光影与氛围】\n  - 光源方向与色温：右后方逆光，暖金色调\n  - 高光与阴影：肉边金色轮廓光，石板暗部沉淀，强化立体粗犷感\n  - 整体氛围：粗犷坦诚、肉欲十足、炭烤烟火气\n【色彩配比】\n  - 主色调：深褐焦色+粉红肉色，占比70%\n  - 辅助色：金色光晕+深灰石板，占比25%\n  - 点缀色：迷迭香绿色，占比5%\n【背景与道具】\n  - 餐具容器：深色石板盘，粗糙肌理\n  - 环境背景：石板本体延伸，暗调沉稳\n  - 搭配逻辑：深色粗糙石板衬托肉的鲜亮柔嫩，材质对比突出主体\n【技术参数建议】\n  - 布光参考：后侧逆光塑形，前侧补光提亮细节\n  - 质感补充：轻微石板粗糙肌理、油脂高光质感，增强炭烤真实感\n  - 技术禁止项：不出现焦距、光圈等无效参数\n【风格标签】肉欲感、炭火香气、粗犷坦诚、外焦里嫩\n【画面收尾精简约束】画面无多余配菜、餐具、装饰杂物，所有元素服务突出羊排外焦里嫩的特质，不抢夺食物主体视觉焦点。"
        }
    ]
}

FOOD_PHOTOGRAPHY_EN = {
    "name": "Food Photography Master (Appetite Narrative Edition)",
    "description": "Professional food photography director crafting mouthwatering, authentic food descriptions. Semantic weight priority: food type & focus → 3D perspective → scene atmosphere → color ratio → details & texture → lighting & appetite design. Built-in 3D perspective, 70%/25%/5% color ratio, dual texture constraints. \"Imperfections\" (slight charring, sauce drips) enhance handcrafted authenticity. Covers desserts, Chinese, Western, beverages, snacks.",
    "input_template": "Step-by-step expansion for food photography: 1) Identify food type and style; 2) Determine visual focus—most appetizing part; 3) Design composition—top-down/side/45° for dimension, with breathing room; 4) Describe food's real state—air pockets, texture, sheen, steam, and imperfections; 5) Design lighting—direction, color temperature, highlights; 6) Plan colors (main 70%/secondary 25%/accent 5%), determine background and generate {mode} description. Natural mode uses 2-3 paragraphs: composition & scene → details & texture → light & color.\n\nCore principles:\n- Food is the star—everything should make it look more delicious\n- Realness comes from imperfection—slight charring, dripping sauce, bubbles, uneven cuts\n- Light is appetite catalyst—warm side light adds dimension\n- Detail builds trust—air pockets, foam sheen, meat reflections must be \"seen\"\n- Avoid over-sharpening and over-saturation—authentic photography is more appealing",
    "output_format_suffix": {
        "natural": "Natural paragraphs (2-3). First: composition and overall scene. Second: food details and real texture. Third: light and color atmosphere. Vivid, appetizing language, no mechanical parameters.",
        "structured": "[Category] Food Photography\n[Food Type] Dessert/Chinese/Western/Beverage/Snack, etc.\n[Visual Focus]\n  - Most appetizing part: crispy crust/molten center/glossy sauce/latte art/steam, etc.\n  - Emotional trigger: warmth/comfort/satisfaction/freshness, etc.\n[Composition & Scene]\n  - Composition: top-down/side angle/45°/rule of thirds/diagonal\n  - Background: plate, tablecloth, elements, and lived-in feel\n[Food Details & Texture]\n  - Appearance: color, form, layers\n  - Texture: crispy/fluffy/glossy/charred/chewy, etc.\n  - Real marks: slight char, sauce drip, bubbles, cut surface, uneven portions\n[Light & Atmosphere]\n  - Light direction & color temperature: natural light/side light/backlight/warm/cool\n  - Highlights & shadows: where highlights fall, shadow softness\n  - Overall mood: warm/fresh/dark mood/comforting\n[Color Palette]\n  - Main color: appetite-setting tone\n  - Secondary color: adds depth\n  - Accent color: creates focus\n[Style Tags] 3-5 keywords summarizing visual character"
    },
    "task_requirements": [
        "Use vivid appetite-triggering language—avoid mechanical parameters",
        "User-specified elements (food type, style, ingredients, color) are hard constraints; supplement only unspecified dimensions",
        "Include: visual focus, composition & scene, food details & texture, light & atmosphere, color palette",
        "Texture description should be specific and vivid—make reader taste through words",
        "Real marks are key—slight charring, sauce drips, bubbles flow naturally into description",
        "Light describes direction, color temperature, and effect on food texture",
        "Composition serves the most appetizing aspect of the dish",
        "Avoid over-sharpening and over-saturation—pursue authentic photo texture",
        "Follow 70%/25%/5% color ratio; 3D perspective follows user input priority",
        "Natural mode uses 2-3 paragraphs, 300-600 words"
    ],
    "constraints": {
        "max_length": 800,
        "dense_description": True,
        "avoid_technical_parameters": True,
        "avoid_over_sharpening": True,
        "language": "en"
    },
    "examples": [
        {
            "natural": "A freshly baked strawberry cake rests at an angle on a ceramic plate, its cut side showing three layers of fluffy cake alternating with two layers of strawberry cream. The cake's air pockets are even and tender, and a thin line of golden-brown runs along the edge—that's where it touched the pan, carrying just the right note of toasted goodness. The cream on top isn't perfectly smooth—it has gentle undulations and a slight drip at the edge, like it was spread by hand, not scraped flat by a machine.\n\nThree halved strawberries are nestled into the cream at a slight angle, their cut surfaces revealing bright red flesh with fine white veins. One has a small dent on its edge, as if gently pressed. Mint leaves scatter casually among the berries, their edges curling slightly—a sign they were picked fresh. Light slants in from the upper right at 45 degrees, tracing a soft arc across the cream, illuminating the fine fibers of the strawberry flesh, and magnifying the cake's tender crumb.\n\nThe background is a light beige linen cloth, its texture clearly visible. The table's shadow falls naturally, meeting the plate's rim at a quiet angle. The whole scene is gentle, restrained, and lived-in—no over-the-top styling, just a slice of cake in the afternoon light, waiting to be enjoyed. That sense of \"just right\" makes you want to pick up a fork more than any retouched perfection.",
            "structured": "[Category] Food Photography\n[Food Type] Dessert\n[Visual Focus]\n  - Most appetizing part: layered cake interior + cream drip\n  - Emotional trigger: Handcrafted, warm comfort\n[Composition & Scene]\n  - Composition: 45° angle, diagonal\n  - Background: Ceramic plate, light beige linen\n[Food Details & Texture]\n  - Appearance: Three cake layers + two cream layers, halved strawberries\n  - Texture: Fluffy with air pockets, creamy with slight drip, juicy strawberries\n  - Real marks: Golden-brown pan edge, undulating cream, slightly dented strawberry\n[Light & Atmosphere]\n  - Light direction & color temperature: 45° upper right natural light, warm\n  - Highlights & shadows: Soft cream highlight, gentle table shadow\n  - Overall mood: Gentle, comforting, afternoon tea\n[Color Palette]\n  - Main: Cream white + strawberry red\n  - Secondary: Mint green + cake gold\n  - Accent: Ceramic plate grey\n[Style Tags] Warm comfort, handmade feel, natural-light tea time"
        },
        {
            "natural": "A bowl of braised pork sits on a dark wood table, steam rising in a thin white haze that softens the background while sharpening the focus on the meat. Large chunks of pork belly are piled in the bowl, each with a perfect caramelized edge, glossy from the melted rock sugar. One piece has a natural crackle pattern on its skin—a split that happened during cooking, not carved for effect, but proof of a long, slow simmer.\n\nThe sauce flows between the meat, deep reddish-brown and glossy, pooling at the bottom of the bowl. A few star anise and a piece of cinnamon rest in the sauce—spices from the braising that haven't been picked out. Spring onion greens are scattered among the meat—some slightly wilted, a few stained darker by sauce, as if they were sprinkled right after plating, still fresh and fragrant.\n\nLight comes from the front-left, softened by the window, creating a series of highlights on the meat's surface—the fat gleams translucent, while the lean shows clearly defined muscle fibers. The dark wood table absorbs most of the light, allowing the bowl to command all attention. Steam still rises, slightly blurring part of the frame, but adding an undeniable warmth to the image—this is a bowl of braised pork that was just brought out, not styled for a shoot.",
            "structured": "[Category] Food Photography\n[Food Type] Chinese Cuisine\n[Visual Focus]\n  - Most appetizing part: Glossy sauce + caramelized meat + steam\n  - Emotional trigger: Homestyle, hearty, comforting\n[Composition & Scene]\n  - Composition: Slight overhead, dark wood table\n  - Background: Dark wood table, kitchen/dining setting\n[Food Details & Texture]\n  - Appearance: Large pork belly chunks piled, deep red-brown sauce, scallion greens\n  - Texture: Glossy sauce, caramelized skin, visible lean fibers\n  - Real marks: Natural skin crackle, sauce pooling, spice traces, scallion staining\n[Light & Atmosphere]\n  - Light direction & color temperature: Front-left natural window light, warm\n  - Highlights & shadows: Highlights on fat, dark wood absorbs light\n  - Overall mood: Homestyle, warm, hearty\n[Color Palette]\n  - Main: Deep red-brown (sauce)\n  - Secondary: Dark gold (skin), emerald (scallions)\n  - Accent: Star anise (dark brown)\n[Style Tags] Comfort food, warm light, hearty home cooking"
        },
        {
            "natural": "A latte sits on a light wood table, the foam at the cup's rim fine and velvety, topped with an intricate leaf pattern. The latte art isn't perfectly symmetrical—the leaf tip narrows slightly off-center, with a fine line trailing the foam's flow. That slight imperfection is precisely what makes it clearly hand-poured, not machine-printed.\n\nA few tiny bubbles dot the foam surface, like the unintended trace of a breath during the pour. The coffee liquid gradates from dark to light at the cup's edge, with a fine brown drip mark along the inner wall—a small trace from the day's first sip. A faint ring of milk residue lingers inside the rim.\n\nLight comes from the left, casting a soft arc across the foam, making the leaf pattern leap out in dimension. The cup's shadow stretches across the table with a blurred edge—natural light's signature. A few coffee beans scatter on the wood surface, one with a fine crack revealing its texture. The whole scene feels relaxed and unhurried—the kind of quiet moment that makes you want to pick up this cup and take a slow sip.",
            "structured": "[Category] Food Photography\n[Food Type] Coffee Beverage\n[Visual Focus]\n  - Most appetizing part: Latte art texture + foam softness\n  - Emotional trigger: Relaxation, slow living, comfort\n[Composition & Scene]\n  - Composition: Slight overhead, cup left-center\n  - Background: Light wood table, scattered coffee beans\n[Food Details & Texture]\n  - Appearance: Fine velvety foam, leaf latte art, coffee layer\n  - Texture: Soft foam, crisp art lines, glossy liquid\n  - Real marks: Slightly off-center art, tiny bubbles, milk ring, drip mark\n[Light & Atmosphere]\n  - Light direction & color temperature: Left side natural light, warm\n  - Highlights & shadows: Foam arc highlight, soft shadow with blurred edge\n  - Overall mood: Relaxed, quiet, slow living\n[Color Palette]\n  - Main: Deep brown coffee + white foam\n  - Secondary: Light wood table\n  - Accent: Dark brown coffee beans\n[Style Tags] Relaxed comfort, slow living, a good cup"
        }
    ]
}