# -*- coding: utf-8 -*-
"""
欧美人像预设提示词库

Author: 亲卿于情 (@Qo-qiao)
GitHub: https://github.com/Qo-qiao
License: See LICENSE file for details
"""

WESTERN_FEMALE_ZH = {
    "name": "真实感欧美女性人像摄影大师",
    "description": "专业欧美女性人像摄影指导，打造真实自然、富有情绪与故事感的人像描述。语义权重优先级：面部肤质五官＞人物姿态服饰＞光影色彩＞场景环境＞构图景别＞摄影参数。支持三维度视角受控组合，用户指定优先沿用。",
    "input_template": "逐步思考扩写欧美女性人像，遵循语义权重：面部肤质雀斑强制约束→人种风格服饰人物动态→场景光影色彩→构图景别视角→色彩方案→模式输出。执行 6 步扩写：1）人种风格判断（欧美女性/通用类）；匹配欧美女性五官、肤质、毛发核心特征（深邃双眼皮、深眼窝、高鼻梁、立体轮廓、蓝/绿/棕瞳色、自然雀斑），拒绝模板化失真；同步判断服饰风格类别（职场/通勤、运动/健身、婚纱/礼服、街头/潮牌、泳装、通用类），未匹配则自主创建并沿用相同字段结构；2）场景与光影：选择与服饰风格匹配的生活化真实空间，用具象词汇描述自然光源（窗光、午后斜阳、阴天柔光、室内暖灯）、场景材质与氛围，删除纯文学化抽象抒情，约束画面仅保留指定场景物件；3）姿态与表情：完整描述动态过程而非静态造型，强调自然抓拍瞬间，展现松弛、慵懒、自信、温柔的生活化状态，搭配肢体、手部、发丝联动动态，捕捉真实细微情绪，杜绝空洞假笑、无神凝视；4）三维度视角与景别：以人物为中心原点，按距离远近、水平环绕、垂直俯仰三维度生成视角；优先沿用用户指定的景别、方位与俯仰，未指定从合规视角池随机抽取；景别限微距特写/标准特写/肩特写/七分/九分/全景人像，水平方位限正面/四分之三斜侧/正侧面/四分之三背面，垂直俯仰限小俯/平视/小仰视角；5）色彩方案：严格遵循主色70%、辅助色25%、点缀色5%面积配比，标注饱和度层级，保证整体色调和谐统一；6）模式输出：自然模式采用2-3段（环境与实体光线→主体动态姿态微表情→肤质肌理色彩细节），剔除全部数字光学参数；结构化模式光学参数搭配中文释义。\n用户输入： #\n\n核心原则：\n  - 姿态必须完整描述动态过程，还原生活抓拍瞬间，展现松弛慵懒的生活化状态，禁止静态摆拍表述\n  - 表情捕捉具象细微真实情绪，使用眼神低垂、眼帘微阖、唇角轻扬等细节描写，杜绝假笑或空洞凝视\n  - 场景与人物有机融合，环境服务于人物叙事而非单纯背景板，全程规避自动新增无关道具、装饰、行人\n  - 光线采用生活化实体光源描述，删除空泛抽象光影修辞，规避过度打光造成的舞台感\n  - 色彩严格执行70%/25%/5%面积配比，统一标注饱和度高低，色调统一不杂乱，视觉留有舒适留白\n  - 全文优先强化欧美女性特征：深邃双眼皮、深眼窝、高鼻梁、立体面部轮廓、蓝/绿/棕色瞳孔、自然雀斑肌理\n  - 拒绝AI虚假人脸：双重肤质约束强化真实肌理，保留雀斑、毛孔、淡细纹、肤色不均、淡痣等生活痕迹\n  - 视角生成遵循用户输入优先原则，指定维度直接沿用，未指定维度按纪实风格审美合规随机，组合符合真实生活拍摄逻辑",
    "output_format_suffix": {
        "natural": "自然段落（2-3 段）：首段描述实体场景环境与明确光源光线氛围，次段刻画人物完整动态姿态与细微表情神态，末段补充肤色肌理、雀斑质感、面料色彩细节。语言平实有画面感，全程无数字技术参数，强化面部不对称、原生肌肤、自然雀斑与发丝细节，自带画面精简约束。",
        "structured": "【类别】风格类别\n【全局肤质正向约束】\n  - 面部基础：欧美年轻女性原生五官，天然面部非对称，深眼窝、高鼻梁、立体轮廓\n  - 皮肤肌理：自然原生肤质，鼻翼可见细微毛孔，眼尾浅细纹，轻微肤色不均，面部带有自然分布雀斑、淡痣\n  - 毛发细节：发丝层次自然，存在碎发、毛躁发梢、额前胎发，无工业级顺滑质感\n【画面构图】\n  - 视觉引导：依托人物目光、肢体朝向、环境线条三重引导\n  - 主体位置：水平百分比 + 垂直百分比，人物占据 70% 视觉权重，环境仅占 30%\n  - 画面比例：3:2 / 4:3 / 16:9 / 1:1\n  - 画面精简约束：仅保留指定场景、道具\n【景别】\n  - 类型：微距特写 / 标准特写 / 肩特写 / 七分人像 / 九分人像 / 全景人像\n  - 取景范围与裁切位置：明确拍到哪些部位、画面裁切边界\n【视角与景深感知】\n  - 距离维度：对应景别类型\n  - 水平方位维度：正面/四分之三斜侧/正侧面/四分之三背面\n  - 垂直俯仰维度：小俯/平视/小仰视角\n  - 景深氛围：主体清晰背景虚化 / 前后景都清晰 / 局部保留环境细节\n【人物描述】\n  - 外貌特征：面部轮廓、眼型（深邃双眼皮）、瞳色、肤色、发型、发色\n  - 姿态动作：完整身体动态与手部联动细节，姿态松弛自然\n  - 表情神态：眼神落点、细微面部变化，标注清晰真实情绪\n  - 服装造型：款式、颜色、面料材质、版型，标注主色/辅助色/点缀色占比\n【肌肤与细节】\n  - 肤质状态：原生肤色纹理，轻微自然光泽、淡纹路、细小绒毛，保留毛孔、自然雀斑、淡痣、肤色不均\n  - 毛发质感：发丝层次分明，存在碎发或毛躁感，逆光发丝半透明\n  - 面部特征：强化双眼、眉毛、唇形不对称细节，凸显深眼窝、高鼻梁、立体面部轮廓\n【环境与氛围】\n  - 空间场景：精准具体地点及环境特征\n  - 光线来源与方向：自然光/混合光，光线软硬与具体光位，标注冷暖色温\n  - 色调与色彩：主色调与点缀色明确划分，严格遵循70%/25%/5%面积配比\n  - 细节元素：少量服务叙事的质感物件\n【技术参数建议】\n  - 建议焦距：根据景别适配（微距特写100mm-150mm，标准特写85mm，肩特写50mm，七分35mm，九分28mm，全景24mm）\n  - 建议光圈：根据景深气氛需求（强烈虚化f/1.4-f/2.8，适度虚化f/2.8-f/4，环境清晰f/5.6-f/8）\n  - 镜头类型：标准定焦/长焦/广角/微距/移轴等\n  - 技术禁止项：不出现快门速度、ISO数值、测光模式、对焦模式\n【风格标签】整体气质关键词\n【画面收尾精简约束】画面无额外人物、无关花草、多余摆件、杂乱背景装饰"
    },
    "task_requirements": [
        "natural模式使用生活化描述语言，严禁出现焦距、光圈等任何数字技术参数；structured模式可保留【技术参数建议】字段，参数附带文字释义且与景别、画面氛围精准匹配",
        "全文前置强化欧美女性面部特征：深邃双眼皮、深眼窝、高鼻梁、立体面部轮廓、蓝/绿/棕色瞳孔、自然雀斑肌理，提升AI识别优先级",
        "姿态与表情完整还原动态抓拍过程，体现真实情绪流动，展现松弛慵懒、温柔自信的状态，全程规避刻意模特摆姿、僵硬造型",
        "场景与人物有机互动，不自动生成无关道具、行人、装饰，环境为叙事载体而非单纯背景",
        "光线全部采用具象生活化光源描写，替换空泛修辞，规避舞台式强光与虚假光影",
        "双重肤质约束叠加，保留毛孔、细纹、肤色不均、自然雀斑、淡痣等真实肌理，杜绝虚假光滑肤质",
        "严格执行70%/25%/5%色彩配比，标注饱和度层级，视觉留白舒适，无高饱和撞色堆砌",
        "natural模式输出2-3段自然叙事段落（300-600字），structured模式完整分层输出（不超1500字），无冗余空洞抒情内容",
        "三维度视角生成遵循用户输入优先规则，用户明确指定的景别、方位、俯仰角度必须严格沿用；未指定维度从对应风格的合规视角池中随机组合"
    ],
    "constraints": {
        "max_length": 1500,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_ai_face": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "Portra", "Ektar", "胶片型号", "毛孔三维", "凹坑结构", "毛细血管红晕", "完美对称", "快门速度", "ISO", "AF-S", "AF-C", "测光", "曝光补偿", "红晕"],
        "grounding_support": True,
        "language": "zh",
        "natural_mode_forbidden_params": ["mm", "f/", "f1.", "f2.", "f4.", "f5.6", "镜头焦距", "光圈"],
        "structured_param_allowance": "仅允许在【技术参数建议】字段使用焦距 (mm)、光圈 (f/) 和镜头类型，搭配文字效果释义，禁止使用快门、ISO等数值参数，其余字段禁止所有光学数字参数"
    },
    "positive_constraints": "真实欧美女性面部,左右眉眼眉毛唇形天然轻微不对称,深邃双眼皮,深眼窝,高立体鼻梁,清晰立体面部轮廓,蓝绿棕系天然瞳孔,自然毛孔,淡细纹,细微肤色不均,自然雀斑,面部淡痣,原生真实肌肤质感,自然毛躁碎发,生活化发丝痕迹,画面干净简洁,环境仅衬托人物主体,姿态松弛自然,抓拍真实情绪,无刻意摆拍痕迹,拍摄视角符合纪实人像真实拍摄逻辑,三维度组合自然协调,无透视畸变与违和角度",
    "negative_prompts": "完美对称五官,零瑕疵皮肤,人工对称双眼皮,厚重匀肤磨皮,塑料光滑哑光假皮,过度光滑肌肤,完全对称眉眼,厚重美颜,统一匀肤,过度美化皮肤,精致无瑕疵脸蛋,多余绿植,无关摆件,路人,装饰杂物,多余花草,多余家具,杂乱背景,大量装饰,多余人物,空洞假笑,僵硬摆拍,过度锐化,高饱和撞色,人工完美肌理,刻意模特摆姿,多余肢体动作,无神凝视,舞台强光,画面堆砌元素,虚假面部肌理,光滑无毛孔皮肤,无雀斑肤质,规整僵硬发丝,完美无瑕面容,鸟瞰视角,虫眼视角,极端大俯大仰,透视畸变,肢体比例失调",
    "examples": [
        {
            "category": "职场/通勤",
            "natural": "写字楼大堂通透简约，冷白自然光与室内暖光温柔交织，地面铺展柔和几何光影，环境干净极简。一位二十八岁的欧美女性轻靠金属立柱，身姿舒展松弛，是通勤间隙自然放空的抓拍瞬间。她身着米白色修腰西装，内搭黑色高领针织衫，金色长卷发自然垂落肩侧，发丝带生活化微毛躁质感。双臂交叉贴于胸前，身体重心自然偏移，头部微微侧转，目光平视前方，神情从容笃定，唇角带浅淡自然弧度。面部具备典型欧美女性特质，立体轮廓、深邃双眼皮与清晰眼窝，搭配高挺鼻梁。颧骨与面颊散落细碎浅褐色雀斑，眼尾有细微细纹，肌肤保留自然毛孔与轻微肤色不均，无刻意磨皮的虚假质感。柔和侧光在面部形成自然光影分区，完美勾勒立体五官。整体画面以米白、黑色、浅灰为主色调，主色中性冷调占70%、黑色辅助色占25%、金属微光点缀色占5%，色调干净高级。",
            "structured": "【类别】职场/通勤\n【全局肤质正向约束】\n  - 面部基础：二十八岁，欧美立体脸型，天然面部非对称，左眉尾稍浅，右眼眼裂略宽，唇形左右厚薄轻微差异\n  - 皮肤肌理：自然通透原生肤色，面颊浅褐色雀斑错落分布，眼尾细微细纹，面部轻微肤色不均，毛孔细腻可见\n  - 毛发细节：金色长卷发层次蓬松，发梢微干，鬓角碎发自然散落\n【画面构图】\n  - 视觉引导：幕墙竖向线条与走廊纵深线条双重引导，视线聚焦人物面部从容神态\n  - 主体位置：水平50%居中，垂直42%偏上，人物占据70%视觉面积，环境仅占30%\n  - 画面比例：3:2\n  - 画面精简约束：仅保留写字楼大堂、金属立柱、玻璃幕墙\n【景别】\n  - 类型：肩特写\n  - 取景范围与裁切位置：头部至肩下，完整呈现肩部轮廓与上半身姿态\n【视角与景深感知】\n  - 距离维度：中近距离拍摄，聚焦面部神态与职场气质\n  - 水平方位维度：四分之三斜侧角度，自然呈现面部明暗层次\n  - 垂直俯仰维度：平视正面视角，营造平等亲和的交流感\n  - 景深氛围：人物面部与肩部清晰细腻，大堂远景适度虚化\n【人物描述】\n  - 外貌特征：二十八岁，欧美立体轮廓脸型，深邃双眼皮，深眼窝，蓝灰色瞳孔，金色长卷发\n  - 姿态动作：轻靠立柱自然站立，双臂交叉胸前，重心偏移单侧腿部，头部微侧\n  - 表情神态：从容笃定，眼神平和悠远，神情淡然沉稳\n  - 服装造型：米白色修腰西装主色70%，黑色高领针织衫辅助色25%，金属腕表点缀色5%\n【肌肤与细节】\n  - 肤质状态：原生通透肤色，面颊雀斑自然分布，眼尾细纹舒展，毛孔清晰可见\n  - 毛发质感：金色卷发蓬松有层次，发梢微干带自然毛躁感\n  - 面部特征：深邃双眼皮、深眼窝、高挺鼻梁、立体面部轮廓\n【环境与氛围】\n  - 空间场景：现代极简写字楼大堂，落地玻璃幕墙、灰色大理石地面、金属立柱\n  - 光线来源与方向：正面混合柔光，冷白自然光叠加室内暖光，形成面部柔和三角光区\n  - 色调与色彩：主色米白、浅灰70%，辅助黑色25%，金属冷调微光点缀5%\n  - 细节元素：金属腕表反光、西装面料纹理\n【技术参数建议】\n  - 建议焦距：85mm（标准特写焦段，精准突出面部雀斑、细纹等真实细节）\n  - 建议光圈：f/2.2（适度虚化远景环境，聚焦人物神态与肤质细节）\n  - 镜头类型：长焦定焦镜头\n【风格标签】都市优雅、从容纪实、自然光肖像、高级职场风\n【画面收尾精简约束】画面无多余行人、绿植、装饰摆件、杂物"
        },
        {
            "category": "运动/健身",
            "natural": "工业风健身房硬朗简约，金属器械质感冷冽，顶部格栅灯洒下均匀柔和光线，环境干净无冗余装饰。一位二十四岁的欧美女性悬于单杠之上，处于引体向上发力瞬间，是日常训练最自然的抓拍画面。身姿笔直紧绷，双臂发力撑开，背部肌肉线条舒展清晰，健康小麦色肌肤布满细密汗珠，顺着肌肉纹理缓缓滑落。金色高马尾微微晃动，几缕碎发汗湿贴于颈侧。头部微仰，下颌线条紧绷，双唇微张，眉头轻蹙，眼神坚定锁定前方，神情极致专注。面颊与鼻梁分布自然浅淡雀斑，在光线映衬下清晰可见，肌肤毛孔舒展，保留运动后真实肌理。顶光柔和勾勒肌肉轮廓，明暗阴影过渡自然。整体画面以黑、深灰、金属银为主色调，主色冷色系占70%、肌肤暖调辅助色占25%、汗珠微光点缀色占5%，冷暖交织。",
            "structured": "【类别】运动/健身\n【全局肤质正向约束】\n  - 面部基础：二十四岁，欧美利落立体脸型，天然面部非对称，发力时眉眼褶皱不均，唇形紧绷弧度不一\n  - 皮肤肌理：健康小麦色原生肤质，面颊鼻梁浅雀斑自然分布，运动后毛孔舒展，全身细密汗珠通透\n  - 毛发细节：金色高马尾利落紧致，鬓角碎发汗湿贴肤\n【画面构图】\n  - 视觉引导：人物垂直发力身姿与单杠横线形成视觉张力，视线聚焦面部专注神态与背部肌肉线条\n  - 主体位置：水平50%居中，垂直45%居中，人物占据70%视觉面积，环境仅占30%\n  - 画面比例：3:2\n  - 画面精简约束：仅保留单杠、金属健身器械、格栅灯\n【景别】\n  - 类型：七分人像\n  - 取景范围与裁切位置：头顶至大腿中部，完整保留手部握杠姿态与背部发力肌理\n【视角与景深感知】\n  - 距离维度：中距离拍摄，完整呈现运动姿态与肌肉线条\n  - 水平方位维度：正面微侧角度，清晰展现背部与核心发力状态\n  - 垂直俯仰维度：低角度小仰视角，增强力量感与悬空感\n  - 景深氛围：人物主体与单杠清晰锐利，背景器械轻微虚化\n【人物描述】\n  - 外貌特征：二十四岁，欧美立体脸型，深邃双眼皮，深眼窝，浅棕瞳孔，金色高马尾\n  - 姿态动作：单杠引体向上发力姿态，双手正握单杠，身体笔直悬空，背部肌肉完全舒展收紧\n  - 表情神态：极致专注坚韧，眉头微蹙，双唇微张发力，眼神坚定直视前方\n  - 服装造型：黑色无袖运动背心主色70%，灰色紧身短裤辅助色25%，黑色护腕点缀5%\n【肌肤与细节】\n  - 肤质状态：小麦色健康肌肤，雀斑肌理清晰自然，运动汗珠均匀分布，毛孔舒展通透\n  - 毛发质感：高马尾紧致利落，颈侧碎发汗湿灵动\n  - 面部特征：深邃双眼皮、深眼窝、高挺鼻梁、立体面部轮廓\n【环境与氛围】\n  - 空间场景：工业风健身房，金属健身器械、防滑橡胶地面、顶部金属格栅灯\n  - 光线来源与方向：顶部垂直柔光顶光，光线均匀冷润\n  - 色调与色彩：主色黑、深灰70%，金属银灰辅助色25%，肌肤暖调、汗珠微光点缀5%\n  - 细节元素：晶莹汗珠、肌肉凹凸肌理、器械金属反光\n【技术参数建议】\n  - 建议焦距：35mm（广角焦段，完整捕捉人物发力动态与健身房整体氛围）\n  - 建议光圈：f/2.8（中度虚化背景器械，突出人物力量主体）\n  - 镜头类型：广角定焦镜头\n【风格标签】真实训练纪实、温柔力量、专注坚韧、工业风写实\n【画面收尾精简约束】画面无多余绿植、装饰摆件、闲置器械、路人杂物"
        },
        {
            "category": "艺术人体",
            "natural": "纯白极简的专业摄影空间内，柔和的侧逆光从左侧大面积窗纱透入，在空气中形成细腻的光柱。一位二十七岁的欧美女性侧身站立，身体呈优雅的S形曲线，光影在她的肌肤上自然流动，勾勒出肩颈、腰线与臀部的柔美弧度。侧逆光将她的轮廓边缘镀上一层柔和的金边，胸前与腹部的肌肉线条在明暗交错中若隐若现，大腿内侧的阴影过渡自然而富有层次。她的金色长发随意披散，几缕发丝在逆光中呈现半透明的质感。面部具备典型欧美女性特质，立体轮廓、深邃双眼皮与清晰眼窝，搭配高挺鼻梁，颧骨与面颊散落细碎浅褐色雀斑，眼尾有细微细纹，肌肤保留自然毛孔与轻微肤色不均。整体画面以纯白与肤色为主色调，主色占70%、浅灰背景与阴影辅助色25%、发丝与唇色点缀5%，低饱和冷调，纯净典雅。",
            "structured": "【类别】艺术人体\n【全局肤质正向约束】\n  - 面部基础：二十七岁，欧美立体脸型，天然面部非对称，左眉尾稍浅，右眼眼裂略宽，唇形左右厚薄轻微差异\n  - 皮肤肌理：自然通透原生肤色，面颊浅褐色雀斑错落分布，眼尾细微细纹，面部轻微肤色不均，毛孔细腻可见\n  - 毛发细节：金色长发层次蓬松，发梢微干，鬓角碎发自然散落\n【画面构图】\n  - 视觉引导：侧逆光轮廓引导视线浏览人体曲线，明暗交界线形成自然的视觉流动\n  - 主体位置：水平50%居中，垂直50%居中，人物占据70%视觉面积，环境仅占30%\n  - 画面比例：3:4\n  - 画面精简约束：仅保留纯白摄影空间、窗纱\n【景别】\n  - 类型：九分人像\n  - 取景范围与裁切位置：头顶至脚踝，完整展现人体曲线\n【视角与景深感知】\n  - 距离维度：中距离拍摄，完整呈现人体曲线与光影雕塑\n  - 水平方位维度：正侧面角度，完整展现身体轮廓与曲线\n  - 垂直俯仰维度：平视视角，自然观察角度\n  - 景深氛围：人物清晰细腻，背景轻柔虚化\n【人物描述】\n  - 外貌特征：二十七岁，欧美立体轮廓脸型，深邃双眼皮，深眼窝，蓝灰色瞳孔，金色长发\n  - 姿态动作：侧身站立呈S形曲线，身体舒展优雅\n  - 表情神态：自然宁静，眼神平和，神情放松\n  - 服装造型：无衣物，展现人体自然之美\n【肌肤与细节】\n  - 肤质状态：原生通透肤色，面颊雀斑自然分布，眼尾细纹舒展，毛孔清晰可见\n  - 毛发质感：金色长发自然垂落，逆光下发丝边缘半透明\n  - 身体特征：肩颈线条流畅，腰线纤细，臀部圆润，腿部线条修长\n【环境与氛围】\n  - 空间场景：纯白极简摄影空间，大面积窗纱透光\n  - 光线来源与方向：柔和侧逆光，从左侧窗纱透入，形成轮廓光与光影雕塑效果\n  - 色调与色彩：主色纯白、肤色70%，浅灰背景与阴影辅助色25%，发丝与唇色点缀5%\n  - 细节元素：光柱中的尘埃、肌肤上的光影渐层\n【技术参数建议】\n  - 建议焦距：50mm（标准中焦镜头，精准还原人体曲线与光影过渡）\n  - 建议光圈：f/2.8（中景深，人物清晰背景柔和虚化）\n  - 镜头类型：标准定焦镜头\n【风格标签】艺术人体、光影雕塑、极简纯净、人体美学\n【画面收尾精简约束】画面无多余道具、装饰、杂物"
        },
        {
            "category": "婚纱/礼服",
            "natural": "日落海滨静谧温柔，渐变天际铺满暖橙与粉白余晖，海面波光细碎闪烁，晚风轻柔拂面，环境干净纯粹。一位二十三岁的欧美新娘伫立细软沙滩，是海边日落自然驻足的抓拍瞬间，姿态松弛优雅。她身着象牙白拖尾婚纱，轻盈蕾丝面料通透细腻，多层薄纱裙摆被晚风轻轻拂动。金色长卷发被海风撩起，几缕发丝贴于脸颊，简约头纱向后轻扬，逆光下边缘通透轻盈。身体微侧，脸庞望向远方海天交界处，眼神温柔宁静，神情恬淡治愈。立体饱满的五官极具欧美女性特质，深邃双眼皮、灰蓝色通透瞳孔、高挺鼻梁勾勒出极致侧脸轮廓，面颊散落淡色细碎雀斑，在暖夕阳光线下格外真实治愈。逆光为人物勾勒通透金色轮廓线，面部柔和补光弱化生硬阴影，保留自然肤质肌理。整体画面以象牙白、暖金为主色调，主色暖调浅色系占70%、晚霞粉橙辅助色占25%、海面波光点缀色占5%，色调温柔浪漫。",
            "structured": "【类别】婚纱/礼服\n【全局肤质正向约束】\n  - 面部基础：二十三岁，欧美精致立体脸型，天然面部非对称，左右眼睑开合程度不一，唇角弧度轻微差异\n  - 皮肤肌理：白皙通透原生肤色，面颊淡雀斑错落分布，肤质细腻通透，轻微肤色不均\n  - 毛发细节：金色长卷发蓬松灵动，海风拂动发丝层次丰富，头纱轻薄通透\n【画面构图】\n  - 视觉引导：人物远眺视线与飘逸裙摆形成动态动线，引导视线聚焦温柔神态与婚纱质感\n  - 主体位置：水平45%偏左，垂直40%偏上，人物占据70%视觉面积，环境仅占30%\n  - 画面比例：3:2\n  - 画面精简约束：仅保留沙滩、海面、晚霞天际\n【景别】\n  - 类型：九分人像\n  - 取景范围与裁切位置：头顶至小腿中段，完整展现婚纱裙摆与海边伫立姿态\n【视角与景深感知】\n  - 距离维度：中远距离拍摄，完整呈现人物身形与环境氛围\n  - 水平方位维度：四分之三背面角度，展现侧脸轮廓与飘逸头纱\n  - 垂直俯仰维度：平视视角，营造旁观者温柔记录的叙事感\n  - 景深氛围：人物清晰精致，海面与晚霞自然虚化\n【人物描述】\n  - 外貌特征：二十三岁，欧美立体精致脸型，深邃双眼皮，深眼窝，灰蓝色瞳孔，金色长卷发\n  - 姿态动作：沙滩自然伫立，双手轻提裙摆两侧，身体微侧转头远眺\n  - 表情神态：温柔宁静，眼神悠远恬淡，神情治愈浪漫\n  - 服装造型：象牙白拖尾婚纱主色70%，蕾丝纹理、薄纱裙摆辅助色25%，透明头纱、微光点缀5%\n【肌肤与细节】\n  - 肤质状态：白皙通透原生肌肤，面颊淡雀斑自然分布，肌肤肌理细腻\n  - 毛发质感：金色卷发蓬松有层次，海风动态飘逸，碎发灵动贴脸\n  - 面部特征：深邃双眼皮、深眼窝、高挺鼻梁、饱满唇形\n【环境与氛围】\n  - 空间场景：日落海边沙滩，细软白沙、波光海面、渐变晚霞天际\n  - 光线来源与方向：背后日落逆光，金色轮廓光柔和通透，面部柔光补色\n  - 色调与色彩：主色象牙白、暖金70%，晚霞粉橙、浅蓝辅助色25%，海面波光点缀5%\n  - 细节元素：蕾丝婚纱纹理、透明头纱、沙滩浅脚印\n【技术参数建议】\n  - 建议焦距：50mm（标准中焦镜头，精准还原婚纱通透质感与人物温柔神态）\n  - 建议光圈：f/2.0（适度虚化海面晚霞，聚焦人物主体）\n  - 镜头类型：标准定焦镜头\n【风格标签】电影感婚纱、自然纪实、温柔浪漫、日落氛围感\n【画面收尾精简约束】画面无多余装饰摆件、行人、杂物"
        }
    ]
}

WESTERN_FEMALE_EN = {
    "name": "Realistic Western Female Portrait Master",
    "description": "Professional Western female portrait photography guide crafting natural, emotionally resonant descriptions. Semantic weight priority: facial skin & features > pose & styling > lighting & color > scene > composition > parameters. Supports 3D angle-controlled composition with user-specified priority.",
    "input_template": "Step-by-step expand Western female portraiture, semantic weight: facial skin & freckle constraints → ethnicity & style & clothing & dynamics → scene & lighting & color → composition & angle → color scheme → mode output. 6 steps:1) Ethnicity & style: Western female/General; match Western facial features, skin, hair traits (deep-set eyes, high nose bridge, sculpted contours, blue/green/brown eyes, natural freckles); reject template distortion; determine clothing style (business/casual, sport/fitness, wedding/formal, streetwear, swimwear, general); unmatched create same structure;2) Scene & lighting: choose lifestyle real space matching clothing; concrete vocabulary for natural light (window light, afternoon sun, overcast soft light, indoor warm light), scene materials & atmosphere; delete abstract lyrical expressions; only specified scene objects;3) Pose & expression: describe complete dynamic process, emphasize candid moments; relaxed, languid, confident, gentle natural state; body, hand, hair coordination; capture authentic subtle emotions; no fake smiles, vacant stares;4) 3D angle & framing: subject as origin; distance, horizontal orbit, vertical tilt; prioritize user-specified; unspecified randomly from compliant pool; framings: macro/standard/shoulder close-up, three-quarter, seven-eighths, full-length; azimuth: front, three-quarter side, profile, three-quarter back; tilt: slight high, eye-level, slight low;5) Color scheme: 70% main, 25% secondary, 5% accent; mark saturation; ensure harmonious unified tone;6) Output: natural 2-3 paragraphs (environment & light → pose & expression → skin & color details), no numerical parameters; structured parameters with Chinese descriptions.\nUser input: #\n\nCore principles:\n  - Poses describe complete dynamic processes, restore candid life moments, relaxed languid natural state; no static posing\n  - Expressions capture concrete subtle emotions: lowered gaze, half-closed eyelids, slight smile; no fake smiles, vacant stares\n  - Scene integrates with subject, environment serves narrative; no auto-generated irrelevant props, decorations, passersby\n  - Lighting uses concrete lifestyle sources; delete abstract rhetoric; no stage-like over-lighting\n  - Color strictly 70%/25%/5%; mark saturation; unified harmonious tone; comfortable white space\n  - Prioritize Western female features: deep-set eyes, high nose bridge, sculpted contours, blue/green/brown eyes, natural freckles\n  - Reject AI fake faces; dual skin constraints; preserve pores, fine lines, uneven tone, moles, freckles\n  - Angle generation: user-specified priority; unspecified randomly compliant with documentary aesthetics; natural combinations",
    "output_format_suffix": {
        "natural": "Natural 2-3 paragraphs: scene & light → pose & expression → skin/freckle/color details. Plain language with strong visual imagery; no numerical parameters; emphasize facial asymmetry, natural skin, freckles, hair details; built-in scene simplification.",
        "structured": "[Category]Style category\n[Skin Texture Constraints]\n  - Facial: Western female native features, natural asymmetry (brow height, eye size, lip thickness), deep-set eyes, high nose bridge, sculpted contours\n  - Skin: natural native texture, visible pores, fine lines, slight uneven tone, natural freckles, small moles\n  - Hair: natural layers, flyaways, frizzy ends, no industrial smoothness\n[Composition]\n  - Visual guidance: gaze, body orientation, environmental lines\n  - Subject position: horizontal% + vertical%; subject 70%, environment 30%\n  - Aspect ratio: 3:2 / 4:3 / 16:9 / 1:1\n  - Simplification: only specified scene/props; no extra plants, ornaments, passersby\n[Framing]\n  - Type: macro/standard/shoulder close-up, three-quarter, seven-eighths, full-length\n  - Crop: clearly indicate included parts and boundaries\n[Angle & Depth]\n  - Distance: corresponding to framing\n  - Horizontal: front/three-quarter side/profile/three-quarter back\n  - Vertical: slight high/eye-level/slight low\n  - DOF: subject sharp+background blur / all sharp / partial environment\n[Subject]\n  - Appearance: facial contour, eye shape (deep-set), eye color, skin tone, hairstyle, hair color\n  - Pose: complete dynamic with hand coordination, relaxed natural\n  - Expression: gaze point, subtle changes, authentic emotion\n  - Costume: style, color, fabric, tailoring; main/secondary/accent color %\n[Skin & Details]\n  - Skin: native texture, natural sheen, fine lines, vellus hair; retain pores, freckles, moles, uneven tone\n  - Hair: distinct layers, flyaways/frizzy, backlit translucent strands\n  - Facial: emphasize asymmetry, deep-set eyes, high nose bridge, sculpted contours\n[Environment]\n  - Space: precise location and features\n  - Light: natural/mixed light; hardness, position, color temperature\n  - Color: 70%/25%/5% ratio; main/accent colors clearly divided\n  - Details: few narrative-serving texture objects\n[Technical Parameters]\n  - Focal length: by framing (macro 100-150mm, standard 85mm, shoulder 50mm, three-quarter 35mm, seven-eighths 28mm, full 24mm)\n  - Aperture: by DOF (strong blur f/1.4-2.8, moderate f/2.8-4, sharp f/5.6-8)\n  - Lens: standard/telephoto/wide/macro/tilt-shift\n  - Prohibitions: no shutter speed, ISO, metering, focus modes\n[Style Tags]Overall temperament keywords\n[Scene Constraint]No extra people, plants, ornaments, cluttered background"
    },
    "task_requirements": [
        "natural mode: lifestyle descriptive language, no numerical parameters; structured mode: [Technical Parameters] with text explanations matching framing/atmosphere",
        "Prioritize Western female facial features: deep-set eyes, high nose bridge, sculpted contours, blue/green/brown eyes, natural freckles; improve AI recognition",
        "Pose & expression restore dynamic candid process, genuine emotion; relaxed, gentle, confident; no posed modeling, stiff styling",
        "Scene integrates with subject; no irrelevant props/passersby/decorations; environment serves narrative",
        "Lighting uses concrete lifestyle sources; replace abstract rhetoric; no stage strong light, fake lighting",
        "Dual skin constraints; preserve pores, fine lines, uneven tone, freckles, moles; no fake smooth skin",
        "70%/25%/5% color ratio; mark saturation; comfortable white space; no high-saturation clashing",
        "Natural 2-3 paragraphs (300-600 words); structured ≤1500 words; no redundant empty content",
        "3D angle: user-specified priority; unspecified random from compliant pool; combinations follow documentary photography logic"
    ],
    "constraints": {
        "max_length": 1500,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_ai_face": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "Portra", "Ektar", "film types", "3D pores", "pit structures", "capillary redness", "perfect symmetry", "shutter speed", "ISO", "AF-S", "AF-C", "metering", "exposure compensation", "redness"],
        "grounding_support": True,
        "language": "en",
        "natural_mode_forbidden_params": ["mm", "f/", "f1.", "f2.", "f4.", "f5.6", "lens focal length", "aperture"],
        "structured_param_allowance": "Only allowed in the [Technical Parameters] field to use focal length (mm), aperture (f/) and lens type, with textual effect explanations; prohibit shutter speed, ISO and other numerical parameters; all other fields prohibit optical numerical parameters"
    },
    "positive_constraints": "authentic Western female face,natural asymmetry eyes brows lips,deep-set eyes,high sculpted nose bridge,defined facial contours,blue green brown natural eyes,native skin texture,visible pores,fine lines,slight uneven tone,natural freckles,small facial moles,realistic skin texture,natural hair frizz flyaways,lifestyle hair details,clean composition,environment only complements subject,relaxed natural poses,candid genuine emotion,no posed modeling,angles follow documentary portrait logic,3D coordination,no perspective distortion awkward angles",
    "negative_prompts": "perfectly symmetrical features,zero-flaw skin,artificial symmetrical eyelids,heavy smoothing,plastic fake skin,overly smooth skin,perfectly symmetrical brows eyes,heavy beautification,uniform skin tone,over-beautified skin,flawless face,redundant plants,irrelevant ornaments,passersby,decorative clutter,extra flowers,furniture,cluttered background,excessive decoration,extra people,empty fake smile,stiff posing,over-sharpening,high-saturation clashing,artificial perfect texture,posed modeling,redundant movements,vacant stare,stage strong light,piled-up elements,fake facial texture,poreless smooth skin,freckle-free skin,stiff regular hair,perfect flawless face,bird's-eye view,worm's-eye view,extreme angles,perspective distortion,disproportionate body",
    "examples": [
        {
            "category": "Business/Casual",
            "natural": "Modern office lobby with clean minimalist design, cool white natural light blending with warm interior lighting, casting soft geometric patterns on the floor. A 28-year-old Western woman leans casually against a metal column, posture relaxed and open—a candid moment captured during her commute break. She wears a tailored cream blazer over a black turtleneck, her golden curls falling naturally to her shoulders with subtle lifestyle frizz. Arms crossed loosely, weight shifted to one leg, head turned slightly, gaze steady ahead with a calm confident expression and faint natural smile. Typical Western features: high cheekbones, deep-set eyes, sculpted nose bridge. Light brown freckles scattered across cheeks and nose, fine lines at the corners of her eyes, skin showing natural pores and slight tone variations—no heavy smoothing. Soft side light creates natural dimensionality on her face, perfectly highlighting her features. Color palette: cream, black, soft gray—70% neutral tones, 25% black accent, 5% metallic highlights.",
            "structured": "[Category]Business/Casual\n[Skin Texture Constraints]\n  - Facial: 28-year-old Western woman, sculpted face shape, natural asymmetry—left brow slightly lighter, right eye slightly wider, lip thickness varies\n  - Skin: natural translucent complexion, light brown freckles on cheeks/nose, fine lines around eyes, slight uneven tone, visible pores\n  - Hair: golden curls with natural volume, slightly dry ends, flyaways framing face\n[Composition]\n  - Visual guidance: vertical lines of curtain wall + corridor depth, focusing on calm facial expression\n  - Subject position: horizontal 50% center, vertical 42% upper, subject 70%, environment 30%\n  - Aspect ratio: 3:2\n  - Simplification: only office lobby, metal column, glass curtain wall\n[Framing]\n  - Type: shoulder close-up\n  - Crop: head to below shoulders, complete shoulder contour and upper body posture\n[Angle & Depth]\n  - Distance: medium close-up, focusing on facial expression and professional demeanor\n  - Horizontal: three-quarter angle, natural facial dimension\n  - Vertical: eye-level, equal and approachable\n  - DOF: sharp face/shoulders, lobby background softly blurred\n[Subject]\n  - Appearance: 28-year-old, sculpted features, deep-set eyes, hazel-gray eyes, golden curls\n  - Pose: leaning on column, arms crossed, weight shifted, head slightly turned\n  - Expression: calm confident, steady gaze, faint natural smile\n  - Costume: cream blazer 70%, black turtleneck 25%, metallic watch 5%\n[Skin & Details]\n  - Skin: natural translucent tone, freckles, fine lines, visible pores\n  - Hair: golden curls with volume, dry ends, natural frizz\n  - Facial: deep-set eyes, high nose bridge, sculpted contours\n[Environment]\n  - Space: modern minimalist office lobby, glass curtain wall, gray marble floor\n  - Light: front mixed soft light, cool natural + warm interior, triangular lighting pattern\n  - Color: cream/gray 70%, black 25%, metallic 5%\n  - Details: watch reflection, blazer fabric texture\n[Technical Parameters]\n  - Focal length: 85mm (portrait prime, capturing freckles and fine lines)\n  - Aperture: f/2.2 (soft background blur, focus on expression and skin)\n  - Lens: telephoto prime\n[Style Tags]urban elegance, candid documentary, natural light portrait, professional chic\n[Scene Constraint]No extra people, plants, ornaments, clutter"
        },
        {
            "category": "Sport/Fitness",
            "natural": "Industrial gym with clean functional design, cool metal equipment, soft overhead grid lighting, no unnecessary decoration. A 24-year-old Western woman hangs suspended on a pull-up bar, mid-exertion—an authentic training moment captured naturally. Body straight and taut, arms fully extended, back muscles defined and flexed, warm tan skin glistening with fine sweat droplets tracing down muscle contours. Golden ponytail swings slightly, strands clinging to her neck. Head tilted back, jaw clenched, lips parted, brow furrowed, eyes locked ahead with intense focus. Natural light freckles visible across cheeks and nose, pores open from exertion, skin showing real post-workout texture. Soft overhead light sculpts muscle definition with natural shadows. Color palette: black, dark gray, metallic silver—70% cool tones, 25% warm skin tones, 5% sweat highlights.",
            "structured": "[Category]Sport/Fitness\n[Skin Texture Constraints]\n  - Facial: 24-year-old Western woman, angular features, natural asymmetry—facial creases differ with exertion, lip tension varies\n  - Skin: warm tan complexion, light freckles on cheeks/nose, open pores from sweat, fine sweat droplets across body\n  - Hair: golden ponytail, tight and neat, damp strands at nape\n[Composition]\n  - Visual guidance: vertical body vs horizontal bar creates tension, focus on intense expression and back muscles\n  - Subject position: horizontal 50% center, vertical 45% center, subject 70%, environment 30%\n  - Aspect ratio: 3:2\n  - Simplification: only pull-up bar, metal equipment, grid lighting\n[Framing]\n  - Type: three-quarter shot\n  - Crop: top of head to mid-thigh, complete pull-up posture and back definition\n[Angle & Depth]\n  - Distance: medium shot, complete athletic posture and muscle lines\n  - Horizontal: slight front angle, clear back/core definition\n  - Vertical: low slight upward angle, enhancing strength and suspension\n  - DOF: sharp subject + bar, background equipment softly blurred\n[Subject]\n  - Appearance: 24-year-old, angular features, deep-set eyes, light brown eyes, golden ponytail\n  - Pose: pull-up mid-exertion, hands gripping bar, body straight, back muscles flexed\n  - Expression: intense focus, brow furrowed, lips parted, determined gaze\n  - Costume: black sports tank 70%, gray leggings 25%, black wristband 5%\n[Skin & Details]\n  - Skin: warm tan, freckles visible, sweat droplets, open pores\n  - Hair: tight ponytail, damp neck strands\n  - Facial: deep-set eyes, high nose bridge, sculpted features\n[Environment]\n  - Space: industrial gym, metal equipment, rubber flooring, overhead grid lights\n  - Light: overhead soft lighting, cool even illumination\n  - Color: black/dark gray 70%, metallic silver 25%, skin/sweat 5%\n  - Details: sweat droplets, muscle definition, equipment reflections\n[Technical Parameters]\n  - Focal length: 35mm (wide-angle, capturing full dynamic and gym atmosphere)\n  - Aperture: f/2.8 (moderate background blur, emphasizing strength)\n  - Lens: wide-angle prime\n[Style Tags]authentic training, gentle strength, focused determination, industrial realism\n[Scene Constraint]No extra plants, ornaments, idle equipment, passersby"
        },
        {
            "category": "Art Nude",
            "natural": "Within a pure white minimalist professional photography studio, soft side-backlight filters through a large window screen on the left, creating delicate light beams in the air. A 27-year-old Western woman stands in profile, her body forming an elegant S-curve. Light and shadow flow naturally across her skin, outlining the graceful contours of her shoulders, waistline, and hips. The side-backlight gilds her silhouette with a soft golden edge; muscle lines of her chest and abdomen subtly emerge through the interplay of light and shadow, with natural layered transitions in the shadows of her inner thighs. Her golden hair falls casually, a few strands catching the backlight with translucent quality. Typical Western features: sculpted cheekbones, deep-set eyes, defined eye sockets, high sculpted nose bridge. Light brown freckles scattered across her cheekbones and cheeks, fine lines at the corners of her eyes, skin showing natural pores and slight tone variations. Color palette: pure white and natural skin tones dominate at 70%, light gray background and shadows provide secondary contrast at 25%, and hair and lip color serve as accents at 5%. Low saturation, pure and elegant.",
            "structured": "[Category]Art Nude\n[Skin Texture Constraints]\n  - Facial: 27-year-old Western woman, sculpted face shape, natural asymmetry—left brow slightly lighter, right eye slightly wider, lip thickness varies\n  - Skin: natural translucent complexion, light brown freckles on cheekbones/cheeks, fine lines around eyes, slight uneven tone, visible pores\n  - Hair: golden hair with natural volume, slightly dry ends, flyaways framing face\n[Composition]\n  - Visual guidance: side-backlight silhouette guides eye along body curves, light-shadow boundary creates natural visual flow\n  - Subject position: horizontal 50% center, vertical 50% center, subject 70%, environment 30%\n  - Aspect ratio: 3:4\n  - Simplification: only pure white studio, window screen\n[Framing]\n  - Type: seven-eighths shot\n  - Crop: top of head to ankles, complete body curve presentation\n[Angle & Depth]\n  - Distance: medium shot, fully capturing body curves and light sculpture\n  - Horizontal: profile view, complete body silhouette and curves\n  - Vertical: eye-level, natural viewing perspective\n  - DOF: sharp subject, softly blurred background\n[Subject]\n  - Appearance: 27-year-old, sculpted features, deep-set eyes, hazel-gray eyes, golden hair\n  - Pose: profile standing, body in S-curve, graceful and relaxed\n  - Expression: natural serene, calm gaze, relaxed demeanor\n  - Costume: nude body, no clothing, showcasing natural human beauty\n[Skin & Details]\n  - Skin: natural translucent tone, freckles, fine lines, visible pores\n  - Hair: golden hair falling naturally, translucent edges in backlight\n  - Body: smooth shoulder line, slender waist, rounded hips, long elegant legs\n[Environment]\n  - Space: pure white minimalist photography studio, large window screen\n  - Light: soft side-backlight from left window screen, creating rim light and light sculpture effect\n  - Color: pure white/skin tone 70%, light gray background/shadows 25%, hair/lip color 5%\n  - Details: light beams in air, soft shadow transitions across body contours\n[Technical Parameters]\n  - Focal length: 50mm (standard prime, capturing body curves and light transitions)\n  - Aperture: f/2.8 (medium depth, sharp subject with soft background)\n  - Lens: standard prime\n[Style Tags]Art Nude, light sculpture, minimalist purity, human body aesthetics\n[Scene Constraint]No extra props, decorations, clutter"
        },
        {
            "category": "Wedding/Formal",
            "natural": "Sunset beach with tranquil atmosphere, sky painted in warm orange and soft pink hues, ocean shimmering with golden light, gentle breeze—pure and serene environment. A 23-year-old Western bride stands on soft sand, a natural candid moment as she pauses to gaze at the horizon. She wears an ivory off-the-shoulder wedding gown with delicate lace overlay and flowing multi-layered skirt caught by the wind. Golden waves cascade down, strands brushing her cheeks, simple veil fluttering behind, translucent edges catching the backlight. Body slightly turned, face toward the horizon, eyes soft and dreamy, expression peaceful and tender. Classic Western features: defined cheekbones, deep-set eyes, striking gray-blue eyes, sculpted nose creating perfect profile. Soft freckles dusting her cheeks glow in the warm sunset light—authentic and heartfelt. Backlight creates a golden halo, soft fill light minimizes harsh shadows, preserving natural skin texture. Color palette: ivory, warm gold—70% soft warm tones, 25% sunset pink/orange, 5% ocean shimmer.",
            "structured": "[Category]Wedding/Formal\n[Skin Texture Constraints]\n  - Facial: 23-year-old Western woman, refined features, natural asymmetry—eyelid opening varies, lip curve differs\n  - Skin: fair translucent complexion, soft freckles on cheeks, delicate texture, slight uneven tone\n  - Hair: golden waves with natural volume, wind-tousled layers, lightweight veil\n[Composition]\n  - Visual guidance: horizon gaze + flowing skirt creates dynamic line, focus on tender expression and gown texture\n  - Subject position: horizontal 45% left, vertical 40% upper, subject 70%, environment 30%\n  - Aspect ratio: 3:2\n  - Simplification: only sand, ocean, sunset sky\n[Framing]\n  - Type: seven-eighths shot\n  - Crop: top of head to mid-calf, complete gown silhouette and beach stance\n[Angle & Depth]\n  - Distance: medium-long shot, complete figure and environment\n  - Horizontal: three-quarter back angle, showcasing profile and veil\n  - Vertical: eye-level, gentle observer perspective\n  - DOF: sharp subject, ocean/sky softly blurred\n[Subject]\n  - Appearance: 23-year-old, refined features, deep-set eyes, gray-blue eyes, golden waves\n  - Pose: standing on sand, hands gently holding skirt, body slightly turned, gaze to horizon\n  - Expression: peaceful tender, dreamy eyes, serene romantic\n  - Costume: ivory wedding gown 70%, lace/veil 25%, subtle shimmer 5%\n[Skin & Details]\n  - Skin: fair translucent, soft freckles, delicate natural texture\n  - Hair: golden waves, wind-tousled, veil translucent edges\n  - Facial: deep-set eyes, high nose bridge, full lips\n[Environment]\n  - Space: sunset beach, soft sand, shimmering ocean, colored sky\n  - Light: backlight sunset, golden rim light, soft fill light\n  - Color: ivory/gold 70%, sunset pink/orange 25%, ocean shimmer 5%\n  - Details: lace texture, veil transparency, sand footprints\n[Technical Parameters]\n  - Focal length: 50mm (standard lens, capturing gown texture and tender expression)\n  - Aperture: f/2.0 (soft ocean/sky blur, focusing on subject)\n  - Lens: standard prime\n[Style Tags]cinematic wedding, natural documentary, tender romance, sunset atmosphere\n[Scene Constraint]No extra ornaments, passersby, clutter"
        }
    ]
}

WESTERN_MALE_ZH = {
    "name": "真实感欧美男性人像摄影大师",
    "description": "专业欧美男性人像摄影指导，打造真实自然、富有男性魅力与故事感的人像描述。语义权重优先级：面部肤质五官胡须＞人物姿态服饰＞光影色彩＞场景环境＞构图景别＞摄影参数。支持三维度视角受控组合，用户指定优先沿用。",
    "input_template": "逐步思考扩写欧美男性人像，遵循语义权重：面部肤质胡须强制约束→人种风格服饰人物动态→场景光影色彩→构图景别视角→色彩方案→模式输出。执行 6 步扩写：1）人种风格判断（欧美男性/通用类）；匹配欧美男性五官、肤质、毛发、胡须核心特征（深邃双眼皮、深眼窝、高鼻梁、立体轮廓、蓝/绿/棕瞳色、胡茬青印、自然雀斑），拒绝模板化失真；同步判断服饰风格类别（职场/通勤、运动/健身、正装/商务、街头/潮牌、休闲、通用类），未匹配则自主创建并沿用相同字段结构；2）场景与光影：选择与服饰风格匹配的生活化真实空间，用具象词汇描述自然光源（窗光、午后斜阳、阴天柔光、室内暖灯）、场景材质与氛围，删除纯文学化抽象抒情，约束画面仅保留指定场景物件；3）姿态与表情：完整描述动态过程而非静态造型，强调自然抓拍瞬间，展现沉稳、自信、坚毅、内敛的生活化状态，搭配肢体、手部、发丝联动动态，捕捉真实细微情绪，杜绝空洞假笑、无神凝视；4）三维度视角与景别：以人物为中心原点，按距离远近、水平环绕、垂直俯仰三维度生成视角；优先沿用用户指定的景别、方位与俯仰，未指定从合规视角池随机抽取；景别限微距特写/标准特写/肩特写/七分/九分/全景人像，水平方位限正面/四分之三斜侧/正侧面/四分之三背面，垂直俯仰限小俯/平视/小仰视角；5）色彩方案：严格遵循主色70%、辅助色25%、点缀色5%面积配比，标注饱和度层级，保证整体色调和谐统一；6）模式输出：自然模式采用2-3段（环境与实体光线→主体动态姿态微表情→肤质肌理色彩细节），剔除全部数字光学参数；结构化模式光学参数搭配中文释义。\n用户输入： #\n\n核心原则：\n  - 姿态必须完整描述动态过程，还原生活抓拍瞬间，展现沉稳自信的生活化状态，禁止静态摆拍表述\n  - 表情捕捉具象细微真实情绪，使用眼神坚定、眼帘微垂、下颌紧绷等细节描写，杜绝假笑或空洞凝视\n  - 场景与人物有机融合，环境服务于人物叙事而非单纯背景板，全程规避自动新增无关道具、装饰、行人\n  - 光线采用生活化实体光源描述，删除空泛抽象光影修辞，规避过度打光造成的舞台感\n  - 色彩严格执行70%/25%/5%面积配比，统一标注饱和度高低，色调统一不杂乱，视觉留有舒适留白\n  - 全文优先强化欧美男性特征：深邃双眼皮、深眼窝、高鼻梁、立体面部轮廓、蓝/绿/棕色瞳孔、胡茬青印纹理\n  - 拒绝AI虚假人脸：双重肤质约束强化真实肌理，保留毛孔、细纹、肤色不均、淡痣、胡茬长短与剃须青印等生活痕迹\n  - 视角生成遵循用户输入优先原则，指定维度直接沿用，未指定维度按纪实风格审美合规随机，组合符合真实生活拍摄逻辑",
    "output_format_suffix": {
        "natural": "自然段落（2-3 段）：首段描述实体场景环境与明确光源光线氛围，次段刻画人物完整动态姿态与细微表情神态，末段补充肤色肌理、胡茬质感、面料色彩细节。语言平实有画面感，全程无数字技术参数，强化面部不对称、原生肌肤、胡茬细节与发丝质感，自带画面精简约束。",
        "structured": "【类别】风格类别\n【全局肤质正向约束】\n  - 面部基础：欧美男性原生五官，天然面部非对称，深眼窝、高鼻梁、立体轮廓\n  - 皮肤肌理：自然原生肤质，鼻翼可见细微毛孔，眼尾浅细纹，轻微肤色不均，面部带有自然分布雀斑、淡痣，胡茬长短不一、剃须青印、生长不均\n  - 毛发细节：发丝层次自然，存在碎发、毛躁发梢，无工业级顺滑质感\n【画面构图】\n  - 视觉引导：依托人物目光、肢体朝向、环境线条三重引导\n  - 主体位置：水平百分比 + 垂直百分比，人物占据 70% 视觉权重，环境仅占 30%\n  - 画面比例：3:2 / 4:3 / 16:9 / 1:1\n  - 画面精简约束：仅保留指定场景、道具\n【景别】\n  - 类型：微距特写 / 标准特写 / 肩特写 / 七分人像 / 九分人像 / 全景人像\n  - 取景范围与裁切位置：明确拍到哪些部位、画面裁切边界\n【视角与景深感知】\n  - 距离维度：对应景别类型\n  - 水平方位维度：正面/四分之三斜侧/正侧面/四分之三背面\n  - 垂直俯仰维度：小俯/平视/小仰视角\n  - 景深氛围：主体清晰背景虚化 / 前后景都清晰 / 局部保留环境细节\n【人物描述】\n  - 外貌特征：面部轮廓、眼型（深邃双眼皮）、瞳色、肤色、发型、发色、胡须状态\n  - 姿态动作：完整身体动态与手部联动细节，姿态沉稳自然\n  - 表情神态：眼神落点、细微面部变化，标注清晰真实情绪\n  - 服装造型：款式、颜色、面料材质、版型，标注主色/辅助色/点缀色占比\n【肌肤与细节】\n  - 肤质状态：原生肤色纹理，轻微自然光泽、淡纹路、细小绒毛，保留毛孔、自然雀斑、淡痣、肤色不均、胡茬青印\n  - 毛发质感：发丝层次分明，存在碎发或毛躁感，逆光发丝半透明\n  - 面部特征：强化双眼、眉毛、唇形不对称细节，凸显深眼窝、高鼻梁、立体面部轮廓、胡茬质感\n【环境与氛围】\n  - 空间场景：精准具体地点及环境特征\n  - 光线来源与方向：自然光/混合光，光线软硬与具体光位，标注冷暖色温\n  - 色调与色彩：主色调与点缀色明确划分，严格遵循70%/25%/5%面积配比\n  - 细节元素：少量服务叙事的质感物件\n【技术参数建议】\n  - 建议焦距：根据景别适配（微距特写100mm-150mm，标准特写85mm，肩特写50mm，七分35mm，九分28mm，全景24mm）\n  - 建议光圈：根据景深气氛需求（强烈虚化f/1.4-f/2.8，适度虚化f/2.8-f/4，环境清晰f/5.6-f/8）\n  - 镜头类型：标准定焦/长焦/广角/微距/移轴等\n  - 技术禁止项：不出现快门速度、ISO数值、测光模式、对焦模式\n【风格标签】整体气质关键词\n【画面收尾精简约束】画面无额外人物、无关花草、多余摆件、杂乱背景装饰"
    },
    "task_requirements": [
        "natural模式使用生活化描述语言，严禁出现焦距、光圈等任何数字技术参数；structured模式可保留【技术参数建议】字段，参数附带文字释义且与景别、画面氛围精准匹配",
        "全文前置强化欧美男性面部特征：深邃双眼皮、深眼窝、高鼻梁、立体面部轮廓、蓝/绿/棕色瞳孔、胡茬青印纹理，提升AI识别优先级",
        "姿态与表情完整还原动态抓拍过程，体现真实情绪流动，展现沉稳自信、坚毅内敛的状态，全程规避刻意模特摆姿、僵硬造型",
        "场景与人物有机互动，不自动生成无关道具、行人、装饰，环境为叙事载体而非单纯背景",
        "光线全部采用具象生活化光源描写，替换空泛修辞，规避舞台式强光与虚假光影",
        "双重肤质约束叠加，保留毛孔、细纹、肤色不均、自然雀斑、淡痣、胡茬青印等真实肌理，杜绝虚假光滑肤质",
        "严格执行70%/25%/5%色彩配比，标注饱和度层级，视觉留白舒适，无高饱和撞色堆砌",
        "natural模式输出2-3段自然叙事段落（300-600字），structured模式完整分层输出（不超1500字），无冗余空洞抒情内容",
        "三维度视角生成遵循用户输入优先规则，用户明确指定的景别、方位、俯仰角度必须严格沿用；未指定维度从对应风格的合规视角池中随机组合"
    ],
    "constraints": {
        "max_length": 1500,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_ai_face": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "Portra", "Ektar", "胶片型号", "毛孔三维", "凹坑结构", "毛细血管红晕", "完美对称", "快门速度", "ISO", "AF-S", "AF-C", "测光", "曝光补偿", "红晕"],
        "grounding_support": True,
        "language": "zh",
        "natural_mode_forbidden_params": ["mm", "f/", "f1.", "f2.", "f4.", "f5.6", "镜头焦距", "光圈"],
        "structured_param_allowance": "仅允许在【技术参数建议】字段使用焦距 (mm)、光圈 (f/) 和镜头类型，搭配文字效果释义，禁止使用快门、ISO等数值参数，其余字段禁止所有光学数字参数"
    },
    "positive_constraints": "真实欧美男性面部,左右眉眼眉毛唇形天然轻微不对称,深邃双眼皮,深眼窝,高立体鼻梁,清晰立体面部轮廓,蓝绿棕系天然瞳孔,自然毛孔,淡细纹,细微肤色不均,自然雀斑,面部淡痣,胡茬长短不一,剃须青印,生长不均,原生真实肌肤质感,自然毛躁碎发,生活化发丝痕迹,画面干净简洁,环境仅衬托人物主体,姿态沉稳自然,抓拍真实情绪,无刻意摆拍痕迹,拍摄视角符合纪实人像真实拍摄逻辑,三维度组合自然协调,无透视畸变与违和角度",
    "negative_prompts": "完美对称五官,零瑕疵皮肤,人工对称双眼皮,厚重匀肤磨皮,塑料光滑哑光假皮,过度光滑肌肤,完全对称眉眼,厚重美颜,统一匀肤,过度美化皮肤,精致无瑕疵脸蛋,多余绿植,无关摆件,路人,装饰杂物,多余花草,多余家具,杂乱背景,大量装饰,多余人物,空洞假笑,僵硬摆拍,过度锐化,高饱和撞色,人工完美肌理,刻意模特摆姿,多余肢体动作,无神凝视,舞台强光,画面堆砌元素,虚假面部肌理,光滑无毛孔皮肤,无雀斑肤质,规整僵硬发丝,完美无瑕面容,鸟瞰视角,虫眼视角,极端大俯大仰,透视畸变,肢体比例失调",
    "examples": [
        {
            "category": "职场/通勤",
            "natural": "写字楼大堂通透简约，冷白自然光与室内暖光温柔交织，地面铺展柔和几何光影，环境干净极简。一位三十岁的欧美男性斜靠金属立柱，身姿舒展沉稳，是通勤间隙自然放空的抓拍瞬间。他身着深灰色修身西装，内搭白色衬衫，领口随意解开两颗纽扣，深棕色短发打理整齐却保留自然纹理。单手插兜，身体重心自然偏移，头部微微侧转，目光平视前方，神情从容笃定，下颌线条紧绷有力。面部具备典型欧美男性特质，立体轮廓、深邃双眼皮与清晰眼窝，搭配高挺鼻梁。上唇与下颌分布短胡茬，呈现自然剃须青印与生长不均质感，面颊散落细碎浅褐色雀斑，眼尾有细微细纹，肌肤保留自然毛孔与轻微肤色不均，无刻意磨皮的虚假质感。柔和侧光在面部形成自然光影分区，完美勾勒立体五官。整体画面以深灰、白色、浅棕为主色调，主色中性冷调占70%、白色辅助色占25%、金属微光点缀色占5%，色调干净高级。",
            "structured": "【类别】职场/通勤\n【全局肤质正向约束】\n  - 面部基础：三十岁，欧美立体脸型，天然面部非对称，左眉尾稍浅，右眼眼裂略宽，唇形左右厚薄轻微差异\n  - 皮肤肌理：自然通透原生肤色，面颊浅褐色雀斑错落分布，眼尾细微细纹，面部轻微肤色不均，毛孔细腻可见，上唇短胡茬、下颌青印、生长不均\n  - 毛发细节：深棕色短发层次分明，鬓角自然，发根清晰可见\n【画面构图】\n  - 视觉引导：幕墙竖向线条与走廊纵深线条双重引导，视线聚焦人物面部从容神态\n  - 主体位置：水平50%居中，垂直42%偏上，人物占据70%视觉面积，环境仅占30%\n  - 画面比例：3:2\n  - 画面精简约束：仅保留写字楼大堂、金属立柱、玻璃幕墙\n【景别】\n  - 类型：肩特写\n  - 取景范围与裁切位置：头部至肩下，完整呈现肩部轮廓与上半身姿态\n【视角与景深感知】\n  - 距离维度：中近距离拍摄，聚焦面部神态与职场气质\n  - 水平方位维度：四分之三斜侧角度，自然呈现面部明暗层次\n  - 垂直俯仰维度：平视正面视角，营造平等亲和的交流感\n  - 景深氛围：人物面部与肩部清晰细腻，大堂远景适度虚化\n【人物描述】\n  - 外貌特征：三十岁，欧美立体轮廓脸型，深邃双眼皮，深眼窝，蓝灰色瞳孔，深棕色短发\n  - 姿态动作：斜靠立柱自然站立，单手插兜，重心偏移单侧腿部，头部微侧\n  - 表情神态：从容笃定，眼神平和悠远，神情淡然沉稳\n  - 服装造型：深灰色修身西装主色70%，白色衬衫辅助色25%，银色腕表点缀色5%\n【肌肤与细节】\n  - 肤质状态：原生通透肤色，面颊雀斑自然分布，眼尾细纹舒展，毛孔清晰可见，胡茬青印自然\n  - 毛发质感：深棕短发整齐有层次，鬓角自然\n  - 面部特征：深邃双眼皮、深眼窝、高挺鼻梁、立体面部轮廓、胡茬质感\n【环境与氛围】\n  - 空间场景：现代极简写字楼大堂，落地玻璃幕墙、灰色大理石地面、金属立柱\n  - 光线来源与方向：正面混合柔光，冷白自然光叠加室内暖光，形成面部柔和三角光区\n  - 色调与色彩：主色深灰、浅灰70%，辅助白色25%，金属冷调微光点缀5%\n  - 细节元素：银色腕表反光、西装面料纹理\n【技术参数建议】\n  - 建议焦距：85mm（标准特写焦段，精准突出面部雀斑、细纹、胡茬等真实细节）\n  - 建议光圈：f/2.2（适度虚化远景环境，聚焦人物神态与肤质细节）\n  - 镜头类型：长焦定焦镜头\n【风格标签】都市儒雅、从容纪实、自然光肖像、高级职场风\n【画面收尾精简约束】画面无多余行人、绿植、装饰摆件、杂物"
        },
        {
            "category": "运动/健身",
            "natural": "工业风健身房硬朗简约，金属器械质感冷冽，顶部格栅灯洒下均匀柔和光线，环境干净无冗余装饰。一位二十六岁的欧美男性俯身做俯卧撑，处于肘部发力撑起瞬间，是日常训练最自然的抓拍画面。背部肌肉线条舒展清晰，健康小麦色肌肤布满细密汗珠，顺着肌肉纹理缓缓滑落。深棕色短发紧贴头皮，几缕碎发汗湿贴于额头。头部微抬，下颌线条紧绷，双唇紧闭，眉头微蹙，眼神坚定锁定前方，神情极致专注。上唇留有短胡茬，呈现自然剃须青印质感，面颊与鼻梁分布自然浅淡雀斑，在光线映衬下清晰可见，肌肤毛孔舒展，保留运动后真实肌理。顶光柔和勾勒肌肉轮廓，明暗阴影过渡自然。整体画面以黑、深灰、金属银为主色调，主色冷色系占70%、肌肤暖调辅助色占25%、汗珠微光点缀色占5%，冷暖交织。",
            "structured": "【类别】运动/健身\n【全局肤质正向约束】\n  - 面部基础：二十六岁，欧美利落立体脸型，天然面部非对称，发力时眉眼褶皱不均，唇形紧绷弧度不一\n  - 皮肤肌理：健康小麦色原生肤质，面颊鼻梁浅雀斑自然分布，运动后毛孔舒展，全身细密汗珠通透，上唇短胡茬、青印明显\n  - 毛发细节：深棕色短发利落，额前碎发汗湿贴肤\n【画面构图】\n  - 视觉引导：人物俯身姿态与地面形成视觉张力，视线聚焦面部专注神态与背部肌肉线条\n  - 主体位置：水平50%居中，垂直45%居中，人物占据70%视觉面积，环境仅占30%\n  - 画面比例：3:2\n  - 画面精简约束：仅保留俯卧撑地面、金属健身器械、格栅灯\n【景别】\n  - 类型：七分人像\n  - 取景范围与裁切位置：头顶至大腿中部，完整保留俯卧撑姿态与背部发力肌理\n【视角与景深感知】\n  - 距离维度：中距离拍摄，完整呈现运动姿态与肌肉线条\n  - 水平方位维度：正面微侧角度，清晰展现背部与核心发力状态\n  - 垂直俯仰维度：低角度小仰视角，增强力量感\n  - 景深氛围：人物主体清晰锐利，背景器械轻微虚化\n【人物描述】\n  - 外貌特征：二十六岁，欧美立体脸型，深邃双眼皮，深眼窝，浅棕瞳孔，深棕色短发\n  - 姿态动作：俯卧撑肘部撑起姿态，双手撑地，身体呈直线，背部肌肉完全舒展收紧\n  - 表情神态：极致专注坚韧，眉头微蹙，双唇紧闭，眼神坚定直视前方\n  - 服装造型：黑色运动背心主色70%，深灰运动短裤辅助色25%，黑色护腕点缀5%\n【肌肤与细节】\n  - 肤质状态：小麦色健康肌肤，雀斑肌理清晰自然，运动汗珠均匀分布，毛孔舒展通透，胡茬青印明显\n  - 毛发质感：短发紧致利落，额头碎发汗湿\n  - 面部特征：深邃双眼皮、深眼窝、高挺鼻梁、立体面部轮廓、胡茬质感\n【环境与氛围】\n  - 空间场景：工业风健身房，金属健身器械、防滑橡胶地面、顶部金属格栅灯\n  - 光线来源与方向：顶部垂直柔光顶光，光线均匀冷润\n  - 色调与色彩：主色黑、深灰70%，金属银灰辅助色25%，肌肤暖调、汗珠微光点缀5%\n  - 细节元素：晶莹汗珠、肌肉凹凸肌理、器械金属反光\n【技术参数建议】\n  - 建议焦距：35mm（广角焦段，完整捕捉人物发力动态与健身房整体氛围）\n  - 建议光圈：f/2.8（中度虚化背景器械，突出人物力量主体）\n  - 镜头类型：广角定焦镜头\n【风格标签】真实训练纪实、力量美学、专注坚韧、工业风写实\n【画面收尾精简约束】画面无多余绿植、装饰摆件、闲置器械、路人杂物"
        },
        {
            "category": "正装/商务",
            "natural": "高档酒店宴会厅华丽简约，水晶吊灯散发柔和暖光，大理石地面光洁映人，环境优雅精致。一位三十五岁的欧美男性站在落地窗前，身姿挺拔沉稳，是商务晚宴间隙远眺的抓拍瞬间。他身着黑色定制西装，内搭白色礼服衬衫，黑色领结整齐系好，深棕色短发梳理得体，发顶有自然分缝。单手轻轻搭在窗台边缘，身体微微侧转，脸庞望向窗外城市夜景，眼神深邃内敛，神情从容自信。立体分明的五官极具欧美男性特质，深邃双眼皮、浅蓝色通透瞳孔、高挺鼻梁勾勒出精致侧脸轮廓，上唇留有精心修剪的短胡茬，呈现自然剃须青印质感，面颊散落淡色细碎雀斑，在暖光映衬下格外真实。柔和暖光均匀铺洒面部，保留自然肤质肌理与胡茬细节。整体画面以黑色、白色、暖金为主色调，主色暗调占70%、白色辅助色占25%、暖金微光点缀色占5%，色调沉稳高级。",
            "structured": "【类别】正装/商务\n【全局肤质正向约束】\n  - 面部基础：三十五岁，欧美精致立体脸型，天然面部非对称，左右眼睑开合程度不一，唇角弧度轻微差异\n  - 皮肤肌理：白皙通透原生肤色，面颊淡雀斑错落分布，肤质细腻通透，轻微肤色不均，上唇短胡茬、青印清晰\n  - 毛发细节：深棕色短发梳理整齐，发顶自然分缝，鬓角修剪利落\n【画面构图】\n  - 视觉引导：人物远眺视线与窗台线条形成动态动线，引导视线聚焦沉稳神态与西装质感\n  - 主体位置：水平45%偏左，垂直40%偏上，人物占据70%视觉面积，环境仅占30%\n  - 画面比例：3:2\n  - 画面精简约束：仅保留酒店宴会厅、落地窗、城市夜景\n【景别】\n  - 类型：九分人像\n  - 取景范围与裁切位置：头顶至小腿中段，完整展现西装版型与站立姿态\n【视角与景深感知】\n  - 距离维度：中远距离拍摄，完整呈现人物身形与环境氛围\n  - 水平方位维度：四分之三斜侧角度，展现侧脸轮廓与西装质感\n  - 垂直俯仰维度：平视视角，营造旁观者沉稳记录的叙事感\n  - 景深氛围：人物清晰精致，窗外城市夜景自然虚化\n【人物描述】\n  - 外貌特征：三十五岁，欧美立体精致脸型，深邃双眼皮，深眼窝，浅蓝色瞳孔，深棕色短发\n  - 姿态动作：窗边自然站立，单手搭窗台，身体微侧转头远眺\n  - 表情神态：深邃内敛，眼神沉稳自信，神情从容大气\n  - 服装造型：黑色定制西装主色70%，白色礼服衬衫、领结辅助色25%，银色袖扣微光点缀5%\n【肌肤与细节】\n  - 肤质状态：白皙通透原生肌肤，面颊淡雀斑自然分布，肌肤肌理细腻，胡茬青印清晰\n  - 毛发质感：深棕短发整齐有层次，鬓角修剪利落\n  - 面部特征：深邃双眼皮、深眼窝、高挺鼻梁、立体面部轮廓、胡茬质感\n【环境与氛围】\n  - 空间场景：高档酒店宴会厅，落地窗、城市夜景、水晶吊灯\n  - 光线来源与方向：室内暖光混合夜景光线，柔和均匀铺洒面部\n  - 色调与色彩：主色黑色、暗调70%，白色辅助色25%，暖金微光点缀5%\n  - 细节元素：水晶吊灯柔光、西装面料质感、银色袖扣反光\n【技术参数建议】\n  - 建议焦距：50mm（标准中焦镜头，精准还原西装质感与人物沉稳神态）\n  - 建议光圈：f/2.0（适度虚化窗外夜景，聚焦人物主体）\n  - 镜头类型：标准定焦镜头\n【风格标签】商务精英、沉稳大气、晚宴纪实、高级质感\n【画面收尾精简约束】画面无多余装饰摆件、行人、杂物"
        }
    ]
}

WESTERN_MALE_EN = {
    "name": "Realistic Western Male Portrait Master",
    "description": "Professional Western male portrait photography guide crafting natural, masculine, emotionally resonant descriptions. Semantic weight priority: facial skin & features & stubble > pose & styling > lighting & color > scene > composition > parameters. Supports 3D angle-controlled composition with user-specified priority.",
    "input_template": "Step-by-step expand Western male portraiture, semantic weight: facial skin & stubble constraints → ethnicity & style & clothing & dynamics → scene & lighting & color → composition & angle → color scheme → mode output. 6 steps:1) Ethnicity & style: Western male/General; match Western facial features, skin, hair, stubble traits (deep-set eyes, high nose bridge, sculpted contours, blue/green/brown eyes, stubble shadow, natural freckles); reject template distortion; determine clothing style (business/casual, sport/fitness, formal/business, streetwear, casual, general); unmatched create same structure;2) Scene & lighting: choose lifestyle real space matching clothing; concrete vocabulary for natural light (window light, afternoon sun, overcast soft light, indoor warm light), scene materials & atmosphere; delete abstract lyrical expressions; only specified scene objects;3) Pose & expression: describe complete dynamic process, emphasize candid moments; calm, confident, determined, reserved natural state; body, hand, hair coordination; capture authentic subtle emotions; no fake smiles, vacant stares;4) 3D angle & framing: subject as origin; distance, horizontal orbit, vertical tilt; prioritize user-specified; unspecified randomly from compliant pool; framings: macro/standard/shoulder close-up, three-quarter, seven-eighths, full-length; azimuth: front, three-quarter side, profile, three-quarter back; tilt: slight high, eye-level, slight low;5) Color scheme: 70% main, 25% secondary, 5% accent; mark saturation; ensure harmonious unified tone;6) Output: natural 2-3 paragraphs (environment & light → pose & expression → skin & stubble & color details), no numerical parameters; structured parameters with Chinese descriptions.\nUser input: #\n\nCore principles:\n  - Poses describe complete dynamic processes, restore candid life moments, calm confident natural state; no static posing\n  - Expressions capture concrete subtle emotions: determined gaze, lowered eyelids, tight jaw; no fake smiles, vacant stares\n  - Scene integrates with subject, environment serves narrative; no auto-generated irrelevant props, decorations, passersby\n  - Lighting uses concrete lifestyle sources; delete abstract rhetoric; no stage-like over-lighting\n  - Color strictly 70%/25%/5%; mark saturation; unified harmonious tone; comfortable white space\n  - Prioritize Western male features: deep-set eyes, high nose bridge, sculpted contours, blue/green/brown eyes, stubble shadow\n  - Reject AI fake faces; dual skin constraints; preserve pores, fine lines, uneven tone, moles, freckles, stubble\n  - Angle generation: user-specified priority; unspecified randomly compliant with documentary aesthetics; natural combinations",
    "output_format_suffix": {
        "natural": "Natural 2-3 paragraphs: scene & light → pose & expression → skin/stubble/color details. Plain language with strong visual imagery; no numerical parameters; emphasize facial asymmetry, natural skin, stubble, hair details; built-in scene simplification.",
        "structured": "[Category]Style category\n[Skin Texture Constraints]\n  - Facial: Western male native features, natural asymmetry (brow height, eye size, lip thickness), deep-set eyes, high nose bridge, sculpted contours\n  - Skin: natural native texture, visible pores, fine lines, slight uneven tone, natural freckles, small moles, stubble shadow, uneven growth\n  - Hair: natural layers, flyaways, frizzy ends, no industrial smoothness\n[Composition]\n  - Visual guidance: gaze, body orientation, environmental lines\n  - Subject position: horizontal% + vertical%; subject 70%, environment 30%\n  - Aspect ratio: 3:2 / 4:3 / 16:9 / 1:1\n  - Simplification: only specified scene/props; no extra plants, ornaments, passersby\n[Framing]\n  - Type: macro/standard/shoulder close-up, three-quarter, seven-eighths, full-length\n  - Crop: clearly indicate included parts and boundaries\n[Angle & Depth]\n  - Distance: corresponding to framing\n  - Horizontal: front/three-quarter side/profile/three-quarter back\n  - Vertical: slight high/eye-level/slight low\n  - DOF: subject sharp+background blur / all sharp / partial environment\n[Subject]\n  - Appearance: facial contour, eye shape (deep-set), eye color, skin tone, hairstyle, hair color, stubble status\n  - Pose: complete dynamic with hand coordination, calm natural\n  - Expression: gaze point, subtle changes, authentic emotion\n  - Costume: style, color, fabric, tailoring; main/secondary/accent color %\n[Skin & Details]\n  - Skin: native texture, natural sheen, fine lines, vellus hair; retain pores, freckles, moles, uneven tone, stubble shadow\n  - Hair: distinct layers, flyaways/frizzy, backlit translucent strands\n  - Facial: emphasize asymmetry, deep-set eyes, high nose bridge, sculpted contours, stubble texture\n[Environment]\n  - Space: precise location and features\n  - Light: natural/mixed light; hardness, position, color temperature\n  - Color: 70%/25%/5% ratio; main/accent colors clearly divided\n  - Details: few narrative-serving texture objects\n[Technical Parameters]\n  - Focal length: by framing (macro 100-150mm, standard 85mm, shoulder 50mm, three-quarter 35mm, seven-eighths 28mm, full 24mm)\n  - Aperture: by DOF (strong blur f/1.4-2.8, moderate f/2.8-4, sharp f/5.6-8)\n  - Lens: standard/telephoto/wide/macro/tilt-shift\n  - Prohibitions: no shutter speed, ISO, metering, focus modes\n[Style Tags]Overall temperament keywords\n[Scene Constraint]No extra people, plants, ornaments, cluttered background"
    },
    "task_requirements": [
        "natural mode: lifestyle descriptive language, no numerical parameters; structured mode: [Technical Parameters] with text explanations matching framing/atmosphere",
        "Prioritize Western male facial features: deep-set eyes, high nose bridge, sculpted contours, blue/green/brown eyes, stubble shadow; improve AI recognition",
        "Pose & expression restore dynamic candid process, genuine emotion; calm, confident, determined; no posed modeling, stiff styling",
        "Scene integrates with subject; no irrelevant props/passersby/decorations; environment serves narrative",
        "Lighting uses concrete lifestyle sources; replace abstract rhetoric; no stage strong light, fake lighting",
        "Dual skin constraints; preserve pores, fine lines, uneven tone, freckles, moles, stubble; no fake smooth skin",
        "70%/25%/5% color ratio; mark saturation; comfortable white space; no high-saturation clashing",
        "Natural 2-3 paragraphs (300-600 words); structured ≤1500 words; no redundant empty content",
        "3D angle: user-specified priority; unspecified random from compliant pool; combinations follow documentary photography logic"
    ],
    "constraints": {
        "max_length": 1500,
        "dense_description": True,
        "no_purple_prose": True,
        "avoid_technical_parameters": True,
        "avoid_ai_face": True,
        "avoid_over_sharpening": True,
        "natural_color_transition": True,
        "forbidden_words": ["8K", "4K", "Portra", "Ektar", "film types", "3D pores", "pit structures", "capillary redness", "perfect symmetry", "shutter speed", "ISO", "AF-S", "AF-C", "metering", "exposure compensation", "redness"],
        "grounding_support": True,
        "language": "en",
        "natural_mode_forbidden_params": ["mm", "f/", "f1.", "f2.", "f4.", "f5.6", "lens focal length", "aperture"],
        "structured_param_allowance": "Only allowed in the [Technical Parameters] field to use focal length (mm), aperture (f/) and lens type, with textual effect explanations; prohibit shutter speed, ISO and other numerical parameters; all other fields prohibit optical numerical parameters"
    },
    "positive_constraints": "authentic Western male face,natural asymmetry eyes brows lips,deep-set eyes,high sculpted nose bridge,defined facial contours,blue green brown natural eyes,native skin texture,visible pores,fine lines,slight uneven tone,natural freckles,small facial moles,stubble shadow uneven growth,realistic skin texture,natural hair frizz flyaways,lifestyle hair details,clean composition,environment only complements subject,calm natural poses,candid genuine emotion,no posed modeling,angles follow documentary portrait logic,3D coordination,no perspective distortion awkward angles",
    "negative_prompts": "perfectly symmetrical features,zero-flaw skin,artificial symmetrical eyelids,heavy smoothing,plastic fake skin,overly smooth skin,perfectly symmetrical brows eyes,heavy beautification,uniform skin tone,over-beautified skin,flawless face,redundant plants,irrelevant ornaments,passersby,decorative clutter,extra flowers,furniture,cluttered background,excessive decoration,extra people,empty fake smile,stiff posing,over-sharpening,high-saturation clashing,artificial perfect texture,posed modeling,redundant movements,vacant stare,stage strong light,piled-up elements,fake facial texture,poreless smooth skin,freckle-free skin,stiff regular hair,perfect flawless face,bird's-eye view,worm's-eye view,extreme angles,perspective distortion,disproportionate body",
    "examples": [
        {
            "category": "Business/Casual",
            "natural": "Modern office lobby with clean minimalist design, cool white natural light blending with warm interior lighting, casting soft geometric patterns on the floor. A 30-year-old Western man leans casually against a metal column, posture relaxed yet composed—a candid moment captured during his commute break. He wears a tailored dark gray suit over a white dress shirt, collar casually unbuttoned at the neck, his dark brown hair neatly styled with natural texture. One hand in pocket, weight shifted to one leg, head turned slightly, gaze steady ahead with a calm confident expression. Typical Western features: strong jawline, deep-set eyes, sculpted nose bridge. Light brown freckles scattered across cheeks and nose, fine lines at the corners of his eyes, skin showing natural pores and slight tone variations—no heavy smoothing. Stubble shadow visible on upper lip and jaw, uneven growth pattern. Soft side light creates natural dimensionality on his face, perfectly highlighting his features. Color palette: dark gray, white, soft brown—70% neutral tones, 25% white accent, 5% metallic highlights.",
            "structured": "[Category]Business/Casual\n[Skin Texture Constraints]\n  - Facial: 30-year-old Western man, sculpted face shape, natural asymmetry—left brow slightly lighter, right eye slightly wider, lip thickness varies\n  - Skin: natural translucent complexion, light brown freckles on cheeks/nose, fine lines around eyes, slight uneven tone, visible pores, stubble shadow on upper lip and jaw\n  - Hair: dark brown hair with natural volume, slightly textured ends, natural styling\n[Composition]\n  - Visual guidance: vertical lines of curtain wall + corridor depth, focusing on calm facial expression\n  - Subject position: horizontal 50% center, vertical 42% upper, subject 70%, environment 30%\n  - Aspect ratio: 3:2\n  - Simplification: only office lobby, metal column, glass curtain wall\n[Framing]\n  - Type: shoulder close-up\n  - Crop: head to below shoulders, complete shoulder contour and upper body posture\n[Angle & Depth]\n  - Distance: medium close-up, focusing on facial expression and professional demeanor\n  - Horizontal: three-quarter angle, natural facial dimension\n  - Vertical: eye-level, equal and approachable\n  - DOF: sharp face/shoulders, lobby background softly blurred\n[Subject]\n  - Appearance: 30-year-old, sculpted features, deep-set eyes, hazel-gray eyes, dark brown hair\n  - Pose: leaning on column, one hand in pocket, weight shifted, head slightly turned\n  - Expression: calm confident, steady gaze, composed demeanor\n  - Costume: dark gray suit 70%, white shirt 25%, silver watch 5%\n[Skin & Details]\n  - Skin: natural translucent tone, freckles, fine lines, visible pores, stubble shadow\n  - Hair: dark brown with volume, natural texture\n  - Facial: deep-set eyes, high nose bridge, sculpted contours, stubble texture\n[Environment]\n  - Space: modern minimalist office lobby, glass curtain wall, gray marble floor\n  - Light: front mixed soft light, cool natural + warm interior, triangular lighting pattern\n  - Color: dark gray/white 70%, white 25%, metallic 5%\n  - Details: watch reflection, suit fabric texture\n[Technical Parameters]\n  - Focal length: 85mm (portrait prime, capturing freckles and fine lines)\n  - Aperture: f/2.2 (soft background blur, focus on expression and skin)\n  - Lens: telephoto prime\n[Style Tags]urban elegance, candid documentary, natural light portrait, professional chic\n[Scene Constraint]No extra people, plants, ornaments, clutter"
        },
        {
            "category": "Sport/Fitness",
            "natural": "Industrial gym with clean functional design, cool metal equipment, soft overhead grid lighting, no unnecessary decoration. A 26-year-old Western man performs push-ups, mid-exertion as he pushes himself up—an authentic training moment captured naturally. Body straight and taut, arms fully extended, back muscles defined and flexed, warm tan skin glistening with fine sweat droplets tracing down muscle contours. Dark brown hair short and neat, strands clinging to his forehead from sweat. Head slightly lifted, jaw clenched, lips pressed together, brow furrowed, eyes locked ahead with intense focus. Natural light freckles visible across cheeks and nose, pores open from exertion, skin showing real post-workout texture. Stubble shadow visible on upper lip, distinct razor shadow pattern. Soft overhead light sculpts muscle definition with natural shadows. Color palette: black, dark gray, metallic silver—70% cool tones, 25% warm skin tones, 5% sweat highlights.",
            "structured": "[Category]Sport/Fitness\n[Skin Texture Constraints]\n  - Facial: 26-year-old Western man, angular features, natural asymmetry—facial creases differ with exertion, lip tension varies\n  - Skin: warm tan complexion, light freckles on cheeks/nose, open pores from sweat, fine sweat droplets across body, stubble shadow on upper lip\n  - Hair: dark brown short hair, neat, damp strands at forehead\n[Composition]\n  - Visual guidance: horizontal push-up posture creates tension, focus on intense expression and back muscles\n  - Subject position: horizontal 50% center, vertical 45% center, subject 70%, environment 30%\n  - Aspect ratio: 3:2\n  - Simplification: only push-up area, metal equipment, grid lighting\n[Framing]\n  - Type: three-quarter shot\n  - Crop: top of head to mid-thigh, complete push-up posture and back definition\n[Angle & Depth]\n  - Distance: medium shot, complete athletic posture and muscle lines\n  - Horizontal: slight front angle, clear back/core definition\n  - Vertical: low slight upward angle, enhancing strength\n  - DOF: sharp subject, background equipment softly blurred\n[Subject]\n  - Appearance: 26-year-old, angular features, deep-set eyes, light brown eyes, dark brown short hair\n  - Pose: push-up mid-exertion, hands on floor, body straight, back muscles flexed\n  - Expression: intense focus, brow furrowed, lips pressed, determined gaze\n  - Costume: black sports tank 70%, dark gray shorts 25%, black wristband 5%\n[Skin & Details]\n  - Skin: warm tan, freckles visible, sweat droplets, open pores, stubble shadow\n  - Hair: short dark brown, damp forehead strands\n  - Facial: deep-set eyes, high nose bridge, sculpted features, stubble texture\n[Environment]\n  - Space: industrial gym, metal equipment, rubber flooring, overhead grid lights\n  - Light: overhead soft lighting, cool even illumination\n  - Color: black/dark gray 70%, metallic silver 25%, skin/sweat 5%\n  - Details: sweat droplets, muscle definition, equipment reflections\n[Technical Parameters]\n  - Focal length: 35mm (wide-angle, capturing full dynamic and gym atmosphere)\n  - Aperture: f/2.8 (moderate background blur, emphasizing strength)\n  - Lens: wide-angle prime\n[Style Tags]authentic training, strength aesthetics, focused determination, industrial realism\n[Scene Constraint]No extra plants, ornaments, idle equipment, passersby"
        },
        {
            "category": "Formal/Business",
            "natural": "Elegant hotel ballroom with refined simplicity, crystal chandelier casting warm soft light, polished marble floors reflecting the ambiance—pure and sophisticated environment. A 35-year-old Western man stands by the floor-to-ceiling window, posture straight and composed, a natural candid moment as he pauses to gaze at the city skyline. He wears a tailored black tuxedo over a crisp white dress shirt, black bow tie perfectly knotted, his dark brown hair neatly combed with a natural part. One hand resting lightly on the window ledge, body slightly turned, face toward the horizon, eyes deep and thoughtful, expression calm and confident. Classic Western features: defined cheekbones, deep-set eyes, striking light blue eyes, sculpted nose creating perfect profile. Short stubble on upper lip, distinct razor shadow—authentic and realistic. Soft warm light evenly illuminates his face, preserving natural skin texture and stubble details. Color palette: black, white, warm gold—70% dark tones, 25% white accent, 5% warm gold highlights.",
            "structured": "[Category]Formal/Business\n[Skin Texture Constraints]\n  - Facial: 35-year-old Western man, refined features, natural asymmetry—eyelid opening varies, lip curve differs\n  - Skin: fair translucent complexion, soft freckles on cheeks, delicate texture, slight uneven tone, short stubble on upper lip with razor shadow\n  - Hair: dark brown hair neatly combed, natural part, clean styling\n[Composition]\n  - Visual guidance: horizon gaze + window line creates dynamic line, focus on composed expression and tuxedo texture\n  - Subject position: horizontal 45% left, vertical 40% upper, subject 70%, environment 30%\n  - Aspect ratio: 3:2\n  - Simplification: only ballroom, window, city skyline\n[Framing]\n  - Type: seven-eighths shot\n  - Crop: top of head to mid-calf, complete tuxedo silhouette and stance\n[Angle & Depth]\n  - Distance: medium-long shot, complete figure and environment\n  - Horizontal: three-quarter side angle, showcasing profile and tuxedo\n  - Vertical: eye-level, calm observer perspective\n  - DOF: sharp subject, city skyline softly blurred\n[Subject]\n  - Appearance: 35-year-old, refined features, deep-set eyes, light blue eyes, dark brown hair\n  - Pose: standing by window, one hand on ledge, body slightly turned, gaze to horizon\n  - Expression: calm confident, thoughtful eyes, composed demeanor\n  - Costume: black tuxedo 70%, white shirt/bow tie 25%, silver cufflinks 5%\n[Skin & Details]\n  - Skin: fair translucent, soft freckles, delicate natural texture, stubble shadow\n  - Hair: dark brown neatly styled, natural part\n  - Facial: deep-set eyes, high nose bridge, sculpted features, stubble texture\n[Environment]\n  - Space: elegant hotel ballroom, floor-to-ceiling window, city skyline\n  - Light: warm interior light, soft even illumination\n  - Color: black/white 70%, white 25%, warm gold 5%\n  - Details: chandelier glow, suit fabric texture, cufflinks reflection\n[Technical Parameters]\n  - Focal length: 50mm (standard lens, capturing tuxedo texture and composed expression)\n  - Aperture: f/2.0 (soft city blur, focusing on subject)\n  - Lens: standard prime\n[Style Tags]business elite, composed elegance, formal documentary, premium quality\n[Scene Constraint]No extra ornaments, passersby, clutter"
        }
    ]
}